//! Signals

pub trait Signal<T> {}

pub trait I2cSmba {}
pub trait SignalI2cSmba<T> {}
pub trait I2cScl {}
pub trait SignalI2cScl<T> {}
pub trait I2cSda {}
pub trait SignalI2cSda<T> {}
pub trait Etr {}
pub trait SignalEtr<T> {}
pub trait Tim {}
pub trait SignalTim<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Cts {}
pub trait SignalCts<T> {}
pub trait Rts {}
pub trait SignalRts<T> {}
pub trait Ck {}
pub trait SignalCk<T> {}
pub trait SpiNss {}
pub trait SignalSpiNss<T> {}
pub trait SpiMiso {}
pub trait SignalSpiMiso<T> {}
pub trait SpiMosi {}
pub trait SignalSpiMosi<T> {}
pub trait SpiSck {}
pub trait SignalSpiSck<T> {}
pub trait Adc {}
pub trait SignalAdc<T> {}

pub struct I2c1Smba {}
pub struct I2c1Scl {}
pub struct I2c1Sda {}
pub struct Tim2Etr {}
pub struct Tim2Ch1 {}
pub struct Tim2Ch2 {}
pub struct Tim2Ch3 {}
pub struct Tim2Ch4 {}
pub struct Tim3Ch1 {}
pub struct Tim3Ch2 {}
pub struct Tim3Ch3 {}
pub struct Tim3Ch4 {}
pub struct Tim4Ch1 {}
pub struct Tim4Ch2 {}
pub struct Tim4Ch3 {}
pub struct Tim4Ch4 {}
pub struct Tim5Ch1 {}
pub struct Tim5Ch2 {}
pub struct Tim5Ch3 {}
pub struct Tim5Ch4 {}
pub struct Tim21Etr {}
pub struct Tim21Ch1 {}
pub struct Tim21Ch2 {}
pub struct Tim22Etr {}
pub struct Tim22Ch1 {}
pub struct Tim22Ch2 {}
pub struct Usart1Tx {}
pub struct Usart1Rx {}
pub struct Usart1Cts {}
pub struct Usart1Rts {}
pub struct Usart1Ck {}
pub struct Usart2Tx {}
pub struct Usart2Rx {}
pub struct Usart2Cts {}
pub struct Usart2Rts {}
pub struct Usart2Ck {}
pub struct Usart3Tx {}
pub struct Usart3Rx {}
pub struct Usart3Cts {}
pub struct Usart3Rts {}
pub struct Usart3Ck {}
pub struct Uart4Tx {}
pub struct Uart4Rx {}
pub struct Uart4Cts {}
pub struct Uart4Rts {}
pub struct Uart4Ck {}
pub struct Uart5Tx {}
pub struct Uart5Rx {}
pub struct Uart5Cts {}
pub struct Uart5Rts {}
pub struct Uart5Ck {}
pub struct Lpuart1Tx {}
pub struct Lpuart1Rx {}
pub struct Lpuart1Cts {}
pub struct Lpuart1Rts {}
pub struct Spi1Nss {}
pub struct Spi1Miso {}
pub struct Spi1Mosi {}
pub struct Spi1Sck {}
pub struct Adc1In0 {}
pub struct Adc1In1 {}
pub struct Adc1In2 {}
pub struct Adc1In3 {}
pub struct Adc1In4 {}
pub struct Adc1In5 {}
pub struct Adc1In6 {}
pub struct Adc1In7 {}
pub struct Adc1In8 {}
pub struct Adc1In9 {}
pub struct Adc1In10 {}
pub struct Adc1In11 {}
pub struct Adc1In12 {}
pub struct Adc1In13 {}
pub struct Adc1In14 {}
pub struct Adc1In15 {}
pub struct Lptim1In1 {}
pub struct Comp1Out {}
pub struct Eventout {}
pub struct Lptim1In2 {}
pub struct Comp2Out {}
pub struct Uart2Ck {}
pub struct Lptim1Etr {}
pub struct Lptim1Out {}
pub struct Mco {}
pub struct Spi1Mio {}
pub struct Swdio {}
pub struct Swclk {}
pub struct RtcOut {}
pub struct RtcRefin {}
