#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;
pub use super::gpio::*;

pin!(PA0, Pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, 0);
pin!(PA1, Pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, 1);
pin!(PA2, Pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, 2);
pin!(PA3, Pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, 3);
pin!(PA4, Pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, 4);
pin!(PA5, Pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, 5);
pin!(PA6, Pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, 6);
pin!(PA7, Pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, 7);
pin!(PA8, Pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, 8);
pin!(PA9, Pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, 9);
pin!(PA10, Pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, 10);
pin!(PA11, Pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, 11);
pin!(PA12, Pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, 12);
pin!(PA13, Pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, 13);
pin!(PA14, Pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, 14);
pin!(PA15, Pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, 15);
pin!(PA16, Pa16, GPIOA, Gpioa, PA16_PIN, GpioPin, GPIOA_PERIPH, 16);
pin!(PA17, Pa17, GPIOA, Gpioa, PA17_PIN, GpioPin, GPIOA_PERIPH, 17);
pin!(PA18, Pa18, GPIOA, Gpioa, PA18_PIN, GpioPin, GPIOA_PERIPH, 18);
pin!(PA19, Pa19, GPIOA, Gpioa, PA19_PIN, GpioPin, GPIOA_PERIPH, 19);
pin!(PA24, Pa24, GPIOA, Gpioa, PA24_PIN, GpioPin, GPIOA_PERIPH, 24);
pin!(PA25, Pa25, GPIOA, Gpioa, PA25_PIN, GpioPin, GPIOA_PERIPH, 25);
pin!(PA26, Pa26, GPIOA, Gpioa, PA26_PIN, GpioPin, GPIOA_PERIPH, 26);
pin!(PA27, Pa27, GPIOA, Gpioa, PA27_PIN, GpioPin, GPIOA_PERIPH, 27);
pin!(PA28, Pa28, GPIOA, Gpioa, PA28_PIN, GpioPin, GPIOA_PERIPH, 28);
pin!(PA29, Pa29, GPIOA, Gpioa, PA29_PIN, GpioPin, GPIOA_PERIPH, 29);
pin!(PB0, Pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, 0);
pin!(PB1, Pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, 1);
pin!(PB2, Pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, 2);
pin!(PB3, Pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, 3);
pin!(PB4, Pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, 4);
pin!(PB5, Pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, 5);
pin!(PB6, Pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, 6);
pin!(PB7, Pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, 7);
pin!(PB8, Pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, 8);
pin!(PB9, Pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, 9);
pin!(PB10, Pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, 10);
pin!(PB11, Pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, 11);
pin!(PB12, Pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, 12);
pin!(PB13, Pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, 13);
pin!(PB16, Pb16, GPIOB, Gpiob, PB16_PIN, GpioPin, GPIOB_PERIPH, 16);
pin!(PB17, Pb17, GPIOB, Gpiob, PB17_PIN, GpioPin, GPIOB_PERIPH, 17);
pin!(PB18, Pb18, GPIOB, Gpiob, PB18_PIN, GpioPin, GPIOB_PERIPH, 18);
pin!(PB19, Pb19, GPIOB, Gpiob, PB19_PIN, GpioPin, GPIOB_PERIPH, 19);
pin!(PB20, Pb20, GPIOB, Gpiob, PB20_PIN, GpioPin, GPIOB_PERIPH, 20);
pin!(PB21, Pb21, GPIOB, Gpiob, PB21_PIN, GpioPin, GPIOB_PERIPH, 21);
pin!(PB22, Pb22, GPIOB, Gpiob, PB22_PIN, GpioPin, GPIOB_PERIPH, 22);
pin!(PB23, Pb23, GPIOB, Gpiob, PB23_PIN, GpioPin, GPIOB_PERIPH, 23);
pin!(PC0, Pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, 0);
pin!(PC1, Pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, 1);
pin!(PC2, Pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, 2);
pin!(PC3, Pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, 3);
pin!(PC4, Pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, 4);
pin!(PC5, Pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, 5);
pin!(PC6, Pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, 6);
pin!(PC7, Pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, 7);
pin!(PC8, Pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, 8);
pin!(PC9, Pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, 9);
pin!(PC10, Pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, 10);
pin!(PC11, Pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, 11);
pin!(PC12, Pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, 12);
pin!(PC13, Pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, 13);
pin!(PC14, Pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, 14);
pin!(PC15, Pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, 15);
pin!(PC16, Pc16, GPIOC, Gpioc, PC16_PIN, GpioPin, GPIOC_PERIPH, 16);
pin!(PC17, Pc17, GPIOC, Gpioc, PC17_PIN, GpioPin, GPIOC_PERIPH, 17);
pin!(PC18, Pc18, GPIOC, Gpioc, PC18_PIN, GpioPin, GPIOC_PERIPH, 18);
pin!(PC19, Pc19, GPIOC, Gpioc, PC19_PIN, GpioPin, GPIOC_PERIPH, 19);
pin!(PD0, Pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, 0);
pin!(PD1, Pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, 1);
pin!(PD2, Pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, 2);
pin!(PD3, Pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, 3);
pin!(PD4, Pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, 4);
pin!(PD5, Pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, 5);
pin!(PD6, Pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, 6);
pin!(PD7, Pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, 7);
pin!(PD8, Pd8, GPIOD, Gpiod, PD8_PIN, GpioPin, GPIOD_PERIPH, 8);
pin!(PD9, Pd9, GPIOD, Gpiod, PD9_PIN, GpioPin, GPIOD_PERIPH, 9);
pin!(PD10, Pd10, GPIOD, Gpiod, PD10_PIN, GpioPin, GPIOD_PERIPH, 10);
pin!(PD11, Pd11, GPIOD, Gpiod, PD11_PIN, GpioPin, GPIOD_PERIPH, 11);
pin!(PD12, Pd12, GPIOD, Gpiod, PD12_PIN, GpioPin, GPIOD_PERIPH, 12);
pin!(PD13, Pd13, GPIOD, Gpiod, PD13_PIN, GpioPin, GPIOD_PERIPH, 13);
pin!(PD14, Pd14, GPIOD, Gpiod, PD14_PIN, GpioPin, GPIOD_PERIPH, 14);
pin!(PD15, Pd15, GPIOD, Gpiod, PD15_PIN, GpioPin, GPIOD_PERIPH, 15);
pin!(PE0, Pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, 0);
pin!(PE1, Pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, 1);
pin!(PE2, Pe2, GPIOE, Gpioe, PE2_PIN, GpioPin, GPIOE_PERIPH, 2);
pin!(PE3, Pe3, GPIOE, Gpioe, PE3_PIN, GpioPin, GPIOE_PERIPH, 3);
pin!(PE4, Pe4, GPIOE, Gpioe, PE4_PIN, GpioPin, GPIOE_PERIPH, 4);
pin!(PE5, Pe5, GPIOE, Gpioe, PE5_PIN, GpioPin, GPIOE_PERIPH, 5);
pin!(PE6, Pe6, GPIOE, Gpioe, PE6_PIN, GpioPin, GPIOE_PERIPH, 6);
pin!(PE7, Pe7, GPIOE, Gpioe, PE7_PIN, GpioPin, GPIOE_PERIPH, 7);
pin!(PE8, Pe8, GPIOE, Gpioe, PE8_PIN, GpioPin, GPIOE_PERIPH, 8);
pin!(PE9, Pe9, GPIOE, Gpioe, PE9_PIN, GpioPin, GPIOE_PERIPH, 9);
pin!(PE10, Pe10, GPIOE, Gpioe, PE10_PIN, GpioPin, GPIOE_PERIPH, 10);
pin!(PE11, Pe11, GPIOE, Gpioe, PE11_PIN, GpioPin, GPIOE_PERIPH, 11);
pin!(PE12, Pe12, GPIOE, Gpioe, PE12_PIN, GpioPin, GPIOE_PERIPH, 12);
pin!(PE24, Pe24, GPIOE, Gpioe, PE24_PIN, GpioPin, GPIOE_PERIPH, 24);
pin!(PE25, Pe25, GPIOE, Gpioe, PE25_PIN, GpioPin, GPIOE_PERIPH, 25);
pin!(PE26, Pe26, GPIOE, Gpioe, PE26_PIN, GpioPin, GPIOE_PERIPH, 26);
pin!(PE27, Pe27, GPIOE, Gpioe, PE27_PIN, GpioPin, GPIOE_PERIPH, 27);
pin!(PE28, Pe28, GPIOE, Gpioe, PE28_PIN, GpioPin, GPIOE_PERIPH, 28);
pub use super::port::*;

pin!(PTA0, Pta0, PORTA, Porta, PTA0_PIN, PortPin, PORTA_PERIPH, 0);
   pin_source!(Pta0, super::ftm::Ftm0Ch5, super::sig::SigFtm, 3);
pin!(PTA1, Pta1, PORTA, Porta, PTA1_PIN, PortPin, PORTA_PERIPH, 1);
   pin_source!(Pta1, super::uart::Uart0, super::sig::SigUartRx, 2);
   pin_source!(Pta1, super::ftm::Ftm0Ch6, super::sig::SigFtm, 3);
pin!(PTA2, Pta2, PORTA, Porta, PTA2_PIN, PortPin, PORTA_PERIPH, 2);
   pin_source!(Pta2, super::uart::Uart0, super::sig::SigUartTx, 2);
   pin_source!(Pta2, super::ftm::Ftm0Ch7, super::sig::SigFtm, 3);
pin!(PTA3, Pta3, PORTA, Porta, PTA3_PIN, PortPin, PORTA_PERIPH, 3);
   pin_source!(Pta3, super::ftm::Ftm0Ch0, super::sig::SigFtm, 3);
pin!(PTA4, Pta4, PORTA, Porta, PTA4_PIN, PortPin, PORTA_PERIPH, 4);
   pin_source!(Pta4, super::ftm::Ftm0Ch1, super::sig::SigFtm, 3);
pin!(PTA5, Pta5, PORTA, Porta, PTA5_PIN, PortPin, PORTA_PERIPH, 5);
   pin_source!(Pta5, super::ftm::Ftm0Ch2, super::sig::SigFtm, 3);
pin!(PTA6, Pta6, PORTA, Porta, PTA6_PIN, PortPin, PORTA_PERIPH, 6);
   pin_source!(Pta6, super::ftm::Ftm0Ch3, super::sig::SigFtm, 3);
pin!(PTA7, Pta7, PORTA, Porta, PTA7_PIN, PortPin, PORTA_PERIPH, 7);
   pin_source!(Pta7, super::adc::Adc0Ch10, super::sig::SigAdc, 0);
   pin_source!(Pta7, super::ftm::Ftm0Ch4, super::sig::SigFtm, 3);
pin!(PTA8, Pta8, PORTA, Porta, PTA8_PIN, PortPin, PORTA_PERIPH, 8);
   pin_source!(Pta8, super::adc::Adc0Ch11, super::sig::SigAdc, 0);
   pin_source!(Pta8, super::ftm::Ftm1Ch0, super::sig::SigFtm, 3);
pin!(PTA9, Pta9, PORTA, Porta, PTA9_PIN, PortPin, PORTA_PERIPH, 9);
   pin_source!(Pta9, super::ftm::Ftm1Ch1, super::sig::SigFtm, 3);
pin!(PTA10, Pta10, PORTA, Porta, PTA10_PIN, PortPin, PORTA_PERIPH, 10);
   pin_source!(Pta10, super::ftm::Ftm2Ch0, super::sig::SigFtm, 3);
pin!(PTA11, Pta11, PORTA, Porta, PTA11_PIN, PortPin, PORTA_PERIPH, 11);
   pin_source!(Pta11, super::ftm::Ftm2Ch1, super::sig::SigFtm, 3);
pin!(PTA12, Pta12, PORTA, Porta, PTA12_PIN, PortPin, PORTA_PERIPH, 12);
   pin_source!(Pta12, super::ftm::Ftm1Ch0, super::sig::SigFtm, 3);
pin!(PTA13, Pta13, PORTA, Porta, PTA13_PIN, PortPin, PORTA_PERIPH, 13);
   pin_source!(Pta13, super::ftm::Ftm1Ch1, super::sig::SigFtm, 3);
pin!(PTA14, Pta14, PORTA, Porta, PTA14_PIN, PortPin, PORTA_PERIPH, 14);
   pin_source!(Pta14, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Pta14, super::uart::Uart0, super::sig::SigUartTx, 3);
pin!(PTA15, Pta15, PORTA, Porta, PTA15_PIN, PortPin, PORTA_PERIPH, 15);
   pin_source!(Pta15, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Pta15, super::uart::Uart0, super::sig::SigUartRx, 3);
pin!(PTA16, Pta16, PORTA, Porta, PTA16_PIN, PortPin, PORTA_PERIPH, 16);
   pin_source!(Pta16, super::spi::Spi0, super::sig::SigSpiSout, 2);
pin!(PTA17, Pta17, PORTA, Porta, PTA17_PIN, PortPin, PORTA_PERIPH, 17);
   pin_source!(Pta17, super::adc::Adc1Ch17, super::sig::SigAdc, 0);
   pin_source!(Pta17, super::spi::Spi0, super::sig::SigSpiSin, 2);
pin!(PTA18, Pta18, PORTA, Porta, PTA18_PIN, PortPin, PORTA_PERIPH, 18);
pin!(PTA19, Pta19, PORTA, Porta, PTA19_PIN, PortPin, PORTA_PERIPH, 19);
pin!(PTA24, Pta24, PORTA, Porta, PTA24_PIN, PortPin, PORTA_PERIPH, 24);
pin!(PTA25, Pta25, PORTA, Porta, PTA25_PIN, PortPin, PORTA_PERIPH, 25);
pin!(PTA26, Pta26, PORTA, Porta, PTA26_PIN, PortPin, PORTA_PERIPH, 26);
pin!(PTA27, Pta27, PORTA, Porta, PTA27_PIN, PortPin, PORTA_PERIPH, 27);
pin!(PTA28, Pta28, PORTA, Porta, PTA28_PIN, PortPin, PORTA_PERIPH, 28);
pin!(PTA29, Pta29, PORTA, Porta, PTA29_PIN, PortPin, PORTA_PERIPH, 29);
pin!(PTB0, Ptb0, PORTB, Portb, PTB0_PIN, PortPin, PORTB_PERIPH, 0);
   pin_source!(Ptb0, super::adc::Adc0Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::adc::Adc1Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptb0, super::ftm::Ftm1Ch0, super::sig::SigFtm, 3);
pin!(PTB1, Ptb1, PORTB, Portb, PTB1_PIN, PortPin, PORTB_PERIPH, 1);
   pin_source!(Ptb1, super::adc::Adc0Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::adc::Adc1Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptb1, super::ftm::Ftm1Ch1, super::sig::SigFtm, 3);
pin!(PTB2, Ptb2, PORTB, Portb, PTB2_PIN, PortPin, PORTB_PERIPH, 2);
   pin_source!(Ptb2, super::adc::Adc0Ch12, super::sig::SigAdc, 0);
   pin_source!(Ptb2, super::i2c::I2c0, super::sig::SigI2cScl, 2);
pin!(PTB3, Ptb3, PORTB, Portb, PTB3_PIN, PortPin, PORTB_PERIPH, 3);
   pin_source!(Ptb3, super::adc::Adc0Ch13, super::sig::SigAdc, 0);
   pin_source!(Ptb3, super::i2c::I2c0, super::sig::SigI2cSda, 2);
pin!(PTB4, Ptb4, PORTB, Portb, PTB4_PIN, PortPin, PORTB_PERIPH, 4);
   pin_source!(Ptb4, super::adc::Adc1Ch10, super::sig::SigAdc, 0);
pin!(PTB5, Ptb5, PORTB, Portb, PTB5_PIN, PortPin, PORTB_PERIPH, 5);
   pin_source!(Ptb5, super::adc::Adc1Ch11, super::sig::SigAdc, 0);
pin!(PTB6, Ptb6, PORTB, Portb, PTB6_PIN, PortPin, PORTB_PERIPH, 6);
   pin_source!(Ptb6, super::adc::Adc1Ch12, super::sig::SigAdc, 0);
pin!(PTB7, Ptb7, PORTB, Portb, PTB7_PIN, PortPin, PORTB_PERIPH, 7);
   pin_source!(Ptb7, super::adc::Adc1Ch13, super::sig::SigAdc, 0);
pin!(PTB8, Ptb8, PORTB, Portb, PTB8_PIN, PortPin, PORTB_PERIPH, 8);
pin!(PTB9, Ptb9, PORTB, Portb, PTB9_PIN, PortPin, PORTB_PERIPH, 9);
   pin_source!(Ptb9, super::spi::Spi1, super::sig::SigSpiPcs1, 2);
pin!(PTB10, Ptb10, PORTB, Portb, PTB10_PIN, PortPin, PORTB_PERIPH, 10);
   pin_source!(Ptb10, super::adc::Adc1Ch14, super::sig::SigAdc, 0);
   pin_source!(Ptb10, super::spi::Spi1, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptb10, super::uart::Uart3, super::sig::SigUartRx, 3);
pin!(PTB11, Ptb11, PORTB, Portb, PTB11_PIN, PortPin, PORTB_PERIPH, 11);
   pin_source!(Ptb11, super::adc::Adc1Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptb11, super::spi::Spi1, super::sig::SigSpiSck, 2);
   pin_source!(Ptb11, super::uart::Uart3, super::sig::SigUartTx, 3);
pin!(PTB12, Ptb12, PORTB, Portb, PTB12_PIN, PortPin, PORTB_PERIPH, 12);
   pin_source!(Ptb12, super::ftm::Ftm1Ch0, super::sig::SigFtm, 3);
   pin_source!(Ptb12, super::ftm::Ftm0Ch4, super::sig::SigFtm, 4);
pin!(PTB13, Ptb13, PORTB, Portb, PTB13_PIN, PortPin, PORTB_PERIPH, 13);
   pin_source!(Ptb13, super::ftm::Ftm1Ch1, super::sig::SigFtm, 3);
   pin_source!(Ptb13, super::ftm::Ftm0Ch5, super::sig::SigFtm, 4);
pin!(PTB16, Ptb16, PORTB, Portb, PTB16_PIN, PortPin, PORTB_PERIPH, 16);
   pin_source!(Ptb16, super::spi::Spi1, super::sig::SigSpiSout, 2);
   pin_source!(Ptb16, super::uart::Uart0, super::sig::SigUartRx, 3);
pin!(PTB17, Ptb17, PORTB, Portb, PTB17_PIN, PortPin, PORTB_PERIPH, 17);
   pin_source!(Ptb17, super::spi::Spi1, super::sig::SigSpiSin, 2);
   pin_source!(Ptb17, super::uart::Uart0, super::sig::SigUartTx, 3);
pin!(PTB18, Ptb18, PORTB, Portb, PTB18_PIN, PortPin, PORTB_PERIPH, 18);
   pin_source!(Ptb18, super::ftm::Ftm2Ch0, super::sig::SigFtm, 3);
pin!(PTB19, Ptb19, PORTB, Portb, PTB19_PIN, PortPin, PORTB_PERIPH, 19);
   pin_source!(Ptb19, super::ftm::Ftm2Ch1, super::sig::SigFtm, 3);
pin!(PTB20, Ptb20, PORTB, Portb, PTB20_PIN, PortPin, PORTB_PERIPH, 20);
   pin_source!(Ptb20, super::spi::Spi2, super::sig::SigSpiPcs0, 2);
pin!(PTB21, Ptb21, PORTB, Portb, PTB21_PIN, PortPin, PORTB_PERIPH, 21);
   pin_source!(Ptb21, super::spi::Spi2, super::sig::SigSpiSck, 2);
pin!(PTB22, Ptb22, PORTB, Portb, PTB22_PIN, PortPin, PORTB_PERIPH, 22);
   pin_source!(Ptb22, super::spi::Spi2, super::sig::SigSpiSout, 2);
pin!(PTB23, Ptb23, PORTB, Portb, PTB23_PIN, PortPin, PORTB_PERIPH, 23);
   pin_source!(Ptb23, super::spi::Spi2, super::sig::SigSpiSin, 2);
   pin_source!(Ptb23, super::spi::Spi0, super::sig::SigSpiPcs5, 3);
pin!(PTC0, Ptc0, PORTC, Portc, PTC0_PIN, PortPin, PORTC_PERIPH, 0);
   pin_source!(Ptc0, super::adc::Adc0Ch14, super::sig::SigAdc, 0);
   pin_source!(Ptc0, super::spi::Spi0, super::sig::SigSpiPcs4, 2);
pin!(PTC1, Ptc1, PORTC, Portc, PTC1_PIN, PortPin, PORTC_PERIPH, 1);
   pin_source!(Ptc1, super::adc::Adc0Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptc1, super::spi::Spi0, super::sig::SigSpiPcs3, 2);
   pin_source!(Ptc1, super::ftm::Ftm0Ch0, super::sig::SigFtm, 4);
pin!(PTC2, Ptc2, PORTC, Portc, PTC2_PIN, PortPin, PORTC_PERIPH, 2);
   pin_source!(Ptc2, super::adc::Adc0Ch4, super::sig::SigAdcSeb, 0);
   pin_source!(Ptc2, super::spi::Spi0, super::sig::SigSpiPcs2, 2);
   pin_source!(Ptc2, super::ftm::Ftm0Ch1, super::sig::SigFtm, 4);
pin!(PTC3, Ptc3, PORTC, Portc, PTC3_PIN, PortPin, PORTC_PERIPH, 3);
   pin_source!(Ptc3, super::spi::Spi0, super::sig::SigSpiPcs1, 2);
   pin_source!(Ptc3, super::uart::Uart1, super::sig::SigUartRx, 3);
   pin_source!(Ptc3, super::ftm::Ftm0Ch2, super::sig::SigFtm, 4);
pin!(PTC4, Ptc4, PORTC, Portc, PTC4_PIN, PortPin, PORTC_PERIPH, 4);
   pin_source!(Ptc4, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptc4, super::uart::Uart1, super::sig::SigUartTx, 3);
   pin_source!(Ptc4, super::ftm::Ftm0Ch3, super::sig::SigFtm, 4);
pin!(PTC5, Ptc5, PORTC, Portc, PTC5_PIN, PortPin, PORTC_PERIPH, 5);
   pin_source!(Ptc5, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Ptc5, super::ftm::Ftm0Ch2, super::sig::SigFtm, 7);
pin!(PTC6, Ptc6, PORTC, Portc, PTC6_PIN, PortPin, PORTC_PERIPH, 6);
   pin_source!(Ptc6, super::spi::Spi0, super::sig::SigSpiSout, 2);
pin!(PTC7, Ptc7, PORTC, Portc, PTC7_PIN, PortPin, PORTC_PERIPH, 7);
   pin_source!(Ptc7, super::spi::Spi0, super::sig::SigSpiSin, 2);
pin!(PTC8, Ptc8, PORTC, Portc, PTC8_PIN, PortPin, PORTC_PERIPH, 8);
   pin_source!(Ptc8, super::adc::Adc1Ch4, super::sig::SigAdcSeb, 0);
pin!(PTC9, Ptc9, PORTC, Portc, PTC9_PIN, PortPin, PORTC_PERIPH, 9);
   pin_source!(Ptc9, super::adc::Adc1Ch5, super::sig::SigAdcSeb, 0);
pin!(PTC10, Ptc10, PORTC, Portc, PTC10_PIN, PortPin, PORTC_PERIPH, 10);
   pin_source!(Ptc10, super::adc::Adc1Ch6, super::sig::SigAdcSeb, 0);
   pin_source!(Ptc10, super::i2c::I2c1, super::sig::SigI2cScl, 2);
pin!(PTC11, Ptc11, PORTC, Portc, PTC11_PIN, PortPin, PORTC_PERIPH, 11);
   pin_source!(Ptc11, super::adc::Adc1Ch7, super::sig::SigAdcSeb, 0);
   pin_source!(Ptc11, super::i2c::I2c1, super::sig::SigI2cSda, 2);
pin!(PTC12, Ptc12, PORTC, Portc, PTC12_PIN, PortPin, PORTC_PERIPH, 12);
pin!(PTC13, Ptc13, PORTC, Portc, PTC13_PIN, PortPin, PORTC_PERIPH, 13);
pin!(PTC14, Ptc14, PORTC, Portc, PTC14_PIN, PortPin, PORTC_PERIPH, 14);
   pin_source!(Ptc14, super::uart::Uart4, super::sig::SigUartRx, 3);
pin!(PTC15, Ptc15, PORTC, Portc, PTC15_PIN, PortPin, PORTC_PERIPH, 15);
   pin_source!(Ptc15, super::uart::Uart4, super::sig::SigUartTx, 3);
pin!(PTC16, Ptc16, PORTC, Portc, PTC16_PIN, PortPin, PORTC_PERIPH, 16);
   pin_source!(Ptc16, super::uart::Uart3, super::sig::SigUartRx, 3);
pin!(PTC17, Ptc17, PORTC, Portc, PTC17_PIN, PortPin, PORTC_PERIPH, 17);
   pin_source!(Ptc17, super::uart::Uart3, super::sig::SigUartTx, 3);
pin!(PTC18, Ptc18, PORTC, Portc, PTC18_PIN, PortPin, PORTC_PERIPH, 18);
pin!(PTC19, Ptc19, PORTC, Portc, PTC19_PIN, PortPin, PORTC_PERIPH, 19);
pin!(PTD0, Ptd0, PORTD, Portd, PTD0_PIN, PortPin, PORTD_PERIPH, 0);
   pin_source!(Ptd0, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
pin!(PTD1, Ptd1, PORTD, Portd, PTD1_PIN, PortPin, PORTD_PERIPH, 1);
   pin_source!(Ptd1, super::adc::Adc0Ch5, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd1, super::spi::Spi0, super::sig::SigSpiSck, 2);
pin!(PTD2, Ptd2, PORTD, Portd, PTD2_PIN, PortPin, PORTD_PERIPH, 2);
   pin_source!(Ptd2, super::spi::Spi0, super::sig::SigSpiSout, 2);
   pin_source!(Ptd2, super::uart::Uart2, super::sig::SigUartRx, 3);
   pin_source!(Ptd2, super::i2c::I2c0, super::sig::SigI2cScl, 7);
pin!(PTD3, Ptd3, PORTD, Portd, PTD3_PIN, PortPin, PORTD_PERIPH, 3);
   pin_source!(Ptd3, super::spi::Spi0, super::sig::SigSpiSin, 2);
   pin_source!(Ptd3, super::uart::Uart2, super::sig::SigUartTx, 3);
   pin_source!(Ptd3, super::i2c::I2c0, super::sig::SigI2cSda, 7);
pin!(PTD4, Ptd4, PORTD, Portd, PTD4_PIN, PortPin, PORTD_PERIPH, 4);
   pin_source!(Ptd4, super::spi::Spi0, super::sig::SigSpiPcs1, 2);
   pin_source!(Ptd4, super::ftm::Ftm0Ch4, super::sig::SigFtm, 4);
   pin_source!(Ptd4, super::spi::Spi1, super::sig::SigSpiPcs0, 7);
pin!(PTD5, Ptd5, PORTD, Portd, PTD5_PIN, PortPin, PORTD_PERIPH, 5);
   pin_source!(Ptd5, super::adc::Adc0Ch6, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd5, super::spi::Spi0, super::sig::SigSpiPcs2, 2);
   pin_source!(Ptd5, super::ftm::Ftm0Ch5, super::sig::SigFtm, 4);
   pin_source!(Ptd5, super::spi::Spi1, super::sig::SigSpiSck, 7);
pin!(PTD6, Ptd6, PORTD, Portd, PTD6_PIN, PortPin, PORTD_PERIPH, 6);
   pin_source!(Ptd6, super::adc::Adc0Ch7, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd6, super::spi::Spi0, super::sig::SigSpiPcs3, 2);
   pin_source!(Ptd6, super::uart::Uart0, super::sig::SigUartRx, 3);
   pin_source!(Ptd6, super::ftm::Ftm0Ch6, super::sig::SigFtm, 4);
   pin_source!(Ptd6, super::spi::Spi1, super::sig::SigSpiSout, 7);
pin!(PTD7, Ptd7, PORTD, Portd, PTD7_PIN, PortPin, PORTD_PERIPH, 7);
   pin_source!(Ptd7, super::uart::Uart0, super::sig::SigUartTx, 3);
   pin_source!(Ptd7, super::ftm::Ftm0Ch7, super::sig::SigFtm, 4);
   pin_source!(Ptd7, super::spi::Spi1, super::sig::SigSpiSin, 7);
pin!(PTD8, Ptd8, PORTD, Portd, PTD8_PIN, PortPin, PORTD_PERIPH, 8);
   pin_source!(Ptd8, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptd8, super::uart::Uart5, super::sig::SigUartRx, 3);
pin!(PTD9, Ptd9, PORTD, Portd, PTD9_PIN, PortPin, PORTD_PERIPH, 9);
   pin_source!(Ptd9, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptd9, super::uart::Uart5, super::sig::SigUartTx, 3);
pin!(PTD10, Ptd10, PORTD, Portd, PTD10_PIN, PortPin, PORTD_PERIPH, 10);
pin!(PTD11, Ptd11, PORTD, Portd, PTD11_PIN, PortPin, PORTD_PERIPH, 11);
   pin_source!(Ptd11, super::spi::Spi2, super::sig::SigSpiPcs0, 2);
pin!(PTD12, Ptd12, PORTD, Portd, PTD12_PIN, PortPin, PORTD_PERIPH, 12);
   pin_source!(Ptd12, super::spi::Spi2, super::sig::SigSpiSck, 2);
pin!(PTD13, Ptd13, PORTD, Portd, PTD13_PIN, PortPin, PORTD_PERIPH, 13);
   pin_source!(Ptd13, super::spi::Spi2, super::sig::SigSpiSout, 2);
pin!(PTD14, Ptd14, PORTD, Portd, PTD14_PIN, PortPin, PORTD_PERIPH, 14);
   pin_source!(Ptd14, super::spi::Spi2, super::sig::SigSpiSin, 2);
pin!(PTD15, Ptd15, PORTD, Portd, PTD15_PIN, PortPin, PORTD_PERIPH, 15);
   pin_source!(Ptd15, super::spi::Spi2, super::sig::SigSpiPcs1, 2);
pin!(PTE0, Pte0, PORTE, Porte, PTE0_PIN, PortPin, PORTE_PERIPH, 0);
   pin_source!(Pte0, super::adc::Adc1Ch4, super::sig::SigAdcSea, 0);
   pin_source!(Pte0, super::spi::Spi1, super::sig::SigSpiPcs1, 2);
   pin_source!(Pte0, super::uart::Uart1, super::sig::SigUartTx, 3);
   pin_source!(Pte0, super::i2c::I2c1, super::sig::SigI2cSda, 6);
pin!(PTE1, Pte1, PORTE, Porte, PTE1_PIN, PortPin, PORTE_PERIPH, 1);
   pin_source!(Pte1, super::adc::Adc1Ch5, super::sig::SigAdcSea, 0);
   pin_source!(Pte1, super::spi::Spi1, super::sig::SigSpiSout, 2);
   pin_source!(Pte1, super::uart::Uart1, super::sig::SigUartRx, 3);
   pin_source!(Pte1, super::i2c::I2c1, super::sig::SigI2cScl, 6);
   pin_source!(Pte1, super::spi::Spi1, super::sig::SigSpiSin, 7);
pin!(PTE2, Pte2, PORTE, Porte, PTE2_PIN, PortPin, PORTE_PERIPH, 2);
   pin_source!(Pte2, super::adc::Adc0Ch2, super::sig::SigAdcDp, 0);
   pin_source!(Pte2, super::adc::Adc1Ch6, super::sig::SigAdcSea, 0);
   pin_source!(Pte2, super::spi::Spi1, super::sig::SigSpiSck, 2);
pin!(PTE3, Pte3, PORTE, Porte, PTE3_PIN, PortPin, PORTE_PERIPH, 3);
   pin_source!(Pte3, super::adc::Adc0Ch2, super::sig::SigAdcDm, 0);
   pin_source!(Pte3, super::adc::Adc1Ch7, super::sig::SigAdcSea, 0);
   pin_source!(Pte3, super::spi::Spi1, super::sig::SigSpiSin, 2);
   pin_source!(Pte3, super::spi::Spi1, super::sig::SigSpiSout, 7);
pin!(PTE4, Pte4, PORTE, Porte, PTE4_PIN, PortPin, PORTE_PERIPH, 4);
   pin_source!(Pte4, super::spi::Spi1, super::sig::SigSpiPcs0, 2);
   pin_source!(Pte4, super::uart::Uart3, super::sig::SigUartTx, 3);
pin!(PTE5, Pte5, PORTE, Porte, PTE5_PIN, PortPin, PORTE_PERIPH, 5);
   pin_source!(Pte5, super::spi::Spi1, super::sig::SigSpiPcs2, 2);
   pin_source!(Pte5, super::uart::Uart3, super::sig::SigUartRx, 3);
pin!(PTE6, Pte6, PORTE, Porte, PTE6_PIN, PortPin, PORTE_PERIPH, 6);
   pin_source!(Pte6, super::spi::Spi1, super::sig::SigSpiPcs3, 2);
pin!(PTE7, Pte7, PORTE, Porte, PTE7_PIN, PortPin, PORTE_PERIPH, 7);
pin!(PTE8, Pte8, PORTE, Porte, PTE8_PIN, PortPin, PORTE_PERIPH, 8);
   pin_source!(Pte8, super::uart::Uart5, super::sig::SigUartTx, 3);
pin!(PTE9, Pte9, PORTE, Porte, PTE9_PIN, PortPin, PORTE_PERIPH, 9);
   pin_source!(Pte9, super::uart::Uart5, super::sig::SigUartRx, 3);
pin!(PTE10, Pte10, PORTE, Porte, PTE10_PIN, PortPin, PORTE_PERIPH, 10);
pin!(PTE11, Pte11, PORTE, Porte, PTE11_PIN, PortPin, PORTE_PERIPH, 11);
pin!(PTE12, Pte12, PORTE, Porte, PTE12_PIN, PortPin, PORTE_PERIPH, 12);
pin!(PTE24, Pte24, PORTE, Porte, PTE24_PIN, PortPin, PORTE_PERIPH, 24);
   pin_source!(Pte24, super::adc::Adc0Ch17, super::sig::SigAdc, 0);
   pin_source!(Pte24, super::uart::Uart4, super::sig::SigUartTx, 3);
   pin_source!(Pte24, super::i2c::I2c0, super::sig::SigI2cScl, 5);
pin!(PTE25, Pte25, PORTE, Porte, PTE25_PIN, PortPin, PORTE_PERIPH, 25);
   pin_source!(Pte25, super::adc::Adc0Ch18, super::sig::SigAdc, 0);
   pin_source!(Pte25, super::uart::Uart4, super::sig::SigUartRx, 3);
   pin_source!(Pte25, super::i2c::I2c0, super::sig::SigI2cSda, 5);
pin!(PTE26, Pte26, PORTE, Porte, PTE26_PIN, PortPin, PORTE_PERIPH, 26);
pin!(PTE27, Pte27, PORTE, Porte, PTE27_PIN, PortPin, PORTE_PERIPH, 27);
pin!(PTE28, Pte28, PORTE, Porte, PTE28_PIN, PortPin, PORTE_PERIPH, 28);
