#[allow(unused_imports)] use bobbin_common::*;

// PeripheralGroup { name: "FLEXCAN", peripherals: [Peripheral { derived_from: None, group_name: None, name: "CAN0", address: 1073889280, size: None, access: None, reset_value: None, reset_mask: None, description: Some("Flex Controller Area Network module"), modules: [], features: [], links: [], interrupts: [Interrupt { name: "CAN0_ORed", types: ["CAN"], value: 78, description: None }, Interrupt { name: "CAN0_Error", types: ["CAN_ERROR"], value: 79, description: None }, Interrupt { name: "CAN0_Wake_Up", types: ["CAN_WAKE_UP"], value: 80, description: None }, Interrupt { name: "CAN0_ORed_0_15_MB", types: ["CAN_0_15"], value: 81, description: None }, Interrupt { name: "CAN0_ORed_16_31_MB", types: ["CAN_16_31"], value: 82, description: None }], clusters: [], registers: [], descriptors: [], signals: [], pins: [], channels: [], dim: None, dim_increment: None, dim_index: None }, Peripheral { derived_from: None, group_name: None, name: "CAN1", address: 1073893376, size: None, access: None, reset_value: None, reset_mask: None, description: Some("Flex Controller Area Network module"), modules: [], features: [], links: [], interrupts: [Interrupt { name: "CAN1_ORed", types: ["CAN"], value: 85, description: None }, Interrupt { name: "CAN1_Error", types: ["CAN_ERROR"], value: 86, description: None }, Interrupt { name: "CAN1_ORed_0_15_MB", types: ["CAN_0_15"], value: 88, description: None }], clusters: [], registers: [], descriptors: [], signals: [], pins: [], channels: [], dim: None, dim_increment: None, dim_index: None }, Peripheral { derived_from: None, group_name: None, name: "CAN2", address: 1073917952, size: None, access: None, reset_value: None, reset_mask: None, description: Some("Flex Controller Area Network module"), modules: [], features: [], links: [], interrupts: [Interrupt { name: "CAN2_ORed", types: ["CAN"], value: 92, description: None }, Interrupt { name: "CAN2_Error", types: ["CAN_ERROR"], value: 93, description: None }, Interrupt { name: "CAN2_ORed_0_15_MB", types: ["CAN_0_15"], value: 95, description: None }], clusters: [], registers: [], descriptors: [], signals: [], pins: [], channels: [], dim: None, dim_increment: None, dim_index: None }], prototype: None, modules: [Module { name: "kinetis_common::chip::flexcan::*", _as: None }], has_pins: false, has_channels: false, description: None }
pub use kinetis_common::chip::flexcan::*;

periph!( CAN0, Can0, _CAN0, FlexcanPeriph, 0x40024000);
periph!( CAN1, Can1, _CAN1, FlexcanPeriph, 0x40025000);
periph!( CAN2, Can2, _CAN2, FlexcanPeriph, 0x4002b000);





