#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;

pub use super::port::*;

pin!(PTA0, Pta0, pta0, PORTA, Porta, PTA0_PIN, PortPin, PORTA_PERIPH, PTA0_OWNED, PTA0_REF_COUNT, 0);
   pin_source!(Pta0, super::adc::Adc0Ch0, super::sig::SigAdc, 0);
   pin_source!(Pta0, super::ftm::Ftm2Ch1, super::sig::SigFtm, 2);
   pin_source!(Pta0, super::lpi2c::Lpi2c0, super::sig::SigI2cScls, 3);
   pin_source!(Pta0, super::lpuart::Lpuart0, super::sig::SigCts, 6);
pin!(PTA1, Pta1, pta1, PORTA, Porta, PTA1_PIN, PortPin, PORTA_PERIPH, PTA1_OWNED, PTA1_REF_COUNT, 1);
   pin_source!(Pta1, super::adc::Adc0Ch1, super::sig::SigAdc, 0);
   pin_source!(Pta1, super::ftm::Ftm1Ch1, super::sig::SigFtm, 2);
   pin_source!(Pta1, super::lpi2c::Lpi2c0, super::sig::SigI2cSdas, 3);
   pin_source!(Pta1, super::lpuart::Lpuart0, super::sig::SigRts, 6);
pin!(PTA2, Pta2, pta2, PORTA, Porta, PTA2_PIN, PortPin, PORTA_PERIPH, PTA2_OWNED, PTA2_REF_COUNT, 2);
   pin_source!(Pta2, super::adc::Adc1Ch0, super::sig::SigAdc, 0);
   pin_source!(Pta2, super::ftm::Ftm3Ch0, super::sig::SigFtm, 2);
   pin_source!(Pta2, super::lpi2c::Lpi2c0, super::sig::SigI2cSda, 3);
   pin_source!(Pta2, super::lpuart::Lpuart0, super::sig::SigRx, 6);
pin!(PTA3, Pta3, pta3, PORTA, Porta, PTA3_PIN, PortPin, PORTA_PERIPH, PTA3_OWNED, PTA3_REF_COUNT, 3);
   pin_source!(Pta3, super::adc::Adc1Ch1, super::sig::SigAdc, 0);
   pin_source!(Pta3, super::ftm::Ftm3Ch1, super::sig::SigFtm, 2);
   pin_source!(Pta3, super::lpi2c::Lpi2c0, super::sig::SigI2cScl, 3);
   pin_source!(Pta3, super::lpuart::Lpuart0, super::sig::SigTx, 6);
pin!(PTA4, Pta4, pta4, PORTA, Porta, PTA4_PIN, PortPin, PORTA_PERIPH, PTA4_OWNED, PTA4_REF_COUNT, 4);
pin!(PTA5, Pta5, pta5, PORTA, Porta, PTA5_PIN, PortPin, PORTA_PERIPH, PTA5_OWNED, PTA5_REF_COUNT, 5);
pin!(PTA6, Pta6, pta6, PORTA, Porta, PTA6_PIN, PortPin, PORTA_PERIPH, PTA6_OWNED, PTA6_REF_COUNT, 6);
   pin_source!(Pta6, super::adc::Adc0Ch2, super::sig::SigAdc, 0);
   pin_source!(Pta6, super::lpspi::Lpspi1, super::sig::SigSpiPcs1, 3);
   pin_source!(Pta6, super::lpuart::Lpuart1, super::sig::SigCts, 6);
pin!(PTA7, Pta7, pta7, PORTA, Porta, PTA7_PIN, PortPin, PORTA_PERIPH, PTA7_OWNED, PTA7_REF_COUNT, 7);
   pin_source!(Pta7, super::adc::Adc0Ch3, super::sig::SigAdc, 0);
   pin_source!(Pta7, super::lpuart::Lpuart1, super::sig::SigRts, 6);
pin!(PTA8, Pta8, pta8, PORTA, Porta, PTA8_PIN, PortPin, PORTA_PERIPH, PTA8_OWNED, PTA8_REF_COUNT, 8);
   pin_source!(Pta8, super::lpuart::Lpuart2, super::sig::SigRx, 2);
   pin_source!(Pta8, super::lpspi::Lpspi2, super::sig::SigSpiSout, 3);
pin!(PTA9, Pta9, pta9, PORTA, Porta, PTA9_PIN, PortPin, PORTA_PERIPH, PTA9_OWNED, PTA9_REF_COUNT, 9);
   pin_source!(Pta9, super::lpuart::Lpuart2, super::sig::SigTx, 2);
   pin_source!(Pta9, super::lpspi::Lpspi2, super::sig::SigSpiPcs0, 3);
pin!(PTA10, Pta10, pta10, PORTA, Porta, PTA10_PIN, PortPin, PORTA_PERIPH, PTA10_OWNED, PTA10_REF_COUNT, 10);
   pin_source!(Pta10, super::ftm::Ftm1Ch4, super::sig::SigFtm, 2);
pin!(PTA11, Pta11, pta11, PORTA, Porta, PTA11_PIN, PortPin, PORTA_PERIPH, PTA11_OWNED, PTA11_REF_COUNT, 11);
   pin_source!(Pta11, super::ftm::Ftm1Ch5, super::sig::SigFtm, 2);
pin!(PTA12, Pta12, pta12, PORTA, Porta, PTA12_PIN, PortPin, PORTA_PERIPH, PTA12_OWNED, PTA12_REF_COUNT, 12);
   pin_source!(Pta12, super::ftm::Ftm1Ch6, super::sig::SigFtm, 2);
pin!(PTA13, Pta13, pta13, PORTA, Porta, PTA13_PIN, PortPin, PORTA_PERIPH, PTA13_OWNED, PTA13_REF_COUNT, 13);
   pin_source!(Pta13, super::ftm::Ftm1Ch7, super::sig::SigFtm, 2);
pin!(PTA14, Pta14, pta14, PORTA, Porta, PTA14_PIN, PortPin, PORTA_PERIPH, PTA14_OWNED, PTA14_REF_COUNT, 14);
pin!(PTA15, Pta15, pta15, PORTA, Porta, PTA15_PIN, PortPin, PORTA_PERIPH, PTA15_OWNED, PTA15_REF_COUNT, 15);
   pin_source!(Pta15, super::adc::Adc1Ch12, super::sig::SigAdc, 0);
   pin_source!(Pta15, super::ftm::Ftm1Ch2, super::sig::SigFtm, 2);
   pin_source!(Pta15, super::lpspi::Lpspi0, super::sig::SigSpiPcs3, 3);
   pin_source!(Pta15, super::lpspi::Lpspi2, super::sig::SigSpiPcs3, 4);
pin!(PTA16, Pta16, pta16, PORTA, Porta, PTA16_PIN, PortPin, PORTA_PERIPH, PTA16_OWNED, PTA16_REF_COUNT, 16);
   pin_source!(Pta16, super::adc::Adc1Ch13, super::sig::SigAdc, 0);
   pin_source!(Pta16, super::ftm::Ftm1Ch3, super::sig::SigFtm, 2);
   pin_source!(Pta16, super::lpspi::Lpspi1, super::sig::SigSpiPcs2, 3);
pin!(PTA17, Pta17, pta17, PORTA, Porta, PTA17_PIN, PortPin, PORTA_PERIPH, PTA17_OWNED, PTA17_REF_COUNT, 17);
   pin_source!(Pta17, super::ftm::Ftm0Ch6, super::sig::SigFtm, 2);
pin!(PTB0, Ptb0, ptb0, PORTB, Portb, PTB0_PIN, PortPin, PORTB_PERIPH, PTB0_OWNED, PTB0_REF_COUNT, 0);
   pin_source!(Ptb0, super::adc::Adc0Ch4, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::adc::Adc1Ch14, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::lpuart::Lpuart0, super::sig::SigRx, 2);
   pin_source!(Ptb0, super::lpspi::Lpspi0, super::sig::SigSpiPcs0, 3);
pin!(PTB1, Ptb1, ptb1, PORTB, Portb, PTB1_PIN, PortPin, PORTB_PERIPH, PTB1_OWNED, PTB1_REF_COUNT, 1);
   pin_source!(Ptb1, super::adc::Adc0Ch5, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::adc::Adc1Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::lpuart::Lpuart0, super::sig::SigTx, 2);
   pin_source!(Ptb1, super::lpspi::Lpspi0, super::sig::SigSpiSout, 3);
pin!(PTB2, Ptb2, ptb2, PORTB, Portb, PTB2_PIN, PortPin, PORTB_PERIPH, PTB2_OWNED, PTB2_REF_COUNT, 2);
   pin_source!(Ptb2, super::adc::Adc0Ch6, super::sig::SigAdc, 0);
   pin_source!(Ptb2, super::ftm::Ftm1Ch0, super::sig::SigFtm, 2);
   pin_source!(Ptb2, super::lpspi::Lpspi0, super::sig::SigSpiSck, 3);
pin!(PTB3, Ptb3, ptb3, PORTB, Portb, PTB3_PIN, PortPin, PORTB_PERIPH, PTB3_OWNED, PTB3_REF_COUNT, 3);
   pin_source!(Ptb3, super::adc::Adc0Ch7, super::sig::SigAdc, 0);
   pin_source!(Ptb3, super::ftm::Ftm1Ch1, super::sig::SigFtm, 2);
   pin_source!(Ptb3, super::lpspi::Lpspi0, super::sig::SigSpiSin, 3);
pin!(PTB4, Ptb4, ptb4, PORTB, Portb, PTB4_PIN, PortPin, PORTB_PERIPH, PTB4_OWNED, PTB4_REF_COUNT, 4);
   pin_source!(Ptb4, super::ftm::Ftm0Ch4, super::sig::SigFtm, 2);
   pin_source!(Ptb4, super::lpspi::Lpspi0, super::sig::SigSpiSout, 3);
pin!(PTB5, Ptb5, ptb5, PORTB, Portb, PTB5_PIN, PortPin, PORTB_PERIPH, PTB5_OWNED, PTB5_REF_COUNT, 5);
   pin_source!(Ptb5, super::ftm::Ftm0Ch5, super::sig::SigFtm, 2);
   pin_source!(Ptb5, super::lpspi::Lpspi0, super::sig::SigSpiPcs1, 3);
   pin_source!(Ptb5, super::lpspi::Lpspi0, super::sig::SigSpiPcs0, 4);
pin!(PTB6, Ptb6, ptb6, PORTB, Portb, PTB6_PIN, PortPin, PORTB_PERIPH, PTB6_OWNED, PTB6_REF_COUNT, 6);
   pin_source!(Ptb6, super::lpi2c::Lpi2c0, super::sig::SigI2cSda, 2);
pin!(PTB7, Ptb7, ptb7, PORTB, Portb, PTB7_PIN, PortPin, PORTB_PERIPH, PTB7_OWNED, PTB7_REF_COUNT, 7);
   pin_source!(Ptb7, super::lpi2c::Lpi2c0, super::sig::SigI2cScl, 2);
pin!(PTB8, Ptb8, ptb8, PORTB, Portb, PTB8_PIN, PortPin, PORTB_PERIPH, PTB8_OWNED, PTB8_REF_COUNT, 8);
   pin_source!(Ptb8, super::ftm::Ftm3Ch0, super::sig::SigFtm, 2);
pin!(PTB9, Ptb9, ptb9, PORTB, Portb, PTB9_PIN, PortPin, PORTB_PERIPH, PTB9_OWNED, PTB9_REF_COUNT, 9);
   pin_source!(Ptb9, super::ftm::Ftm3Ch1, super::sig::SigFtm, 2);
   pin_source!(Ptb9, super::lpi2c::Lpi2c0, super::sig::SigI2cScls, 3);
pin!(PTB10, Ptb10, ptb10, PORTB, Portb, PTB10_PIN, PortPin, PORTB_PERIPH, PTB10_OWNED, PTB10_REF_COUNT, 10);
   pin_source!(Ptb10, super::ftm::Ftm3Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptb10, super::lpi2c::Lpi2c0, super::sig::SigI2cSdas, 3);
pin!(PTB11, Ptb11, ptb11, PORTB, Portb, PTB11_PIN, PortPin, PORTB_PERIPH, PTB11_OWNED, PTB11_REF_COUNT, 11);
   pin_source!(Ptb11, super::ftm::Ftm3Ch3, super::sig::SigFtm, 2);
   pin_source!(Ptb11, super::lpi2c::Lpi2c0, super::sig::SigI2cHreq, 3);
pin!(PTB12, Ptb12, ptb12, PORTB, Portb, PTB12_PIN, PortPin, PORTB_PERIPH, PTB12_OWNED, PTB12_REF_COUNT, 12);
   pin_source!(Ptb12, super::adc::Adc1Ch7, super::sig::SigAdc, 0);
   pin_source!(Ptb12, super::ftm::Ftm0Ch0, super::sig::SigFtm, 2);
pin!(PTB13, Ptb13, ptb13, PORTB, Portb, PTB13_PIN, PortPin, PORTB_PERIPH, PTB13_OWNED, PTB13_REF_COUNT, 13);
   pin_source!(Ptb13, super::adc::Adc1Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb13, super::adc::Adc0Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb13, super::ftm::Ftm0Ch1, super::sig::SigFtm, 2);
pin!(PTB14, Ptb14, ptb14, PORTB, Portb, PTB14_PIN, PortPin, PORTB_PERIPH, PTB14_OWNED, PTB14_REF_COUNT, 14);
   pin_source!(Ptb14, super::adc::Adc1Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb14, super::adc::Adc0Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb14, super::ftm::Ftm0Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptb14, super::lpspi::Lpspi1, super::sig::SigSpiSck, 3);
pin!(PTB15, Ptb15, ptb15, PORTB, Portb, PTB15_PIN, PortPin, PORTB_PERIPH, PTB15_OWNED, PTB15_REF_COUNT, 15);
   pin_source!(Ptb15, super::adc::Adc1Ch14, super::sig::SigAdc, 0);
   pin_source!(Ptb15, super::ftm::Ftm0Ch3, super::sig::SigFtm, 2);
   pin_source!(Ptb15, super::lpspi::Lpspi1, super::sig::SigSpiSin, 3);
pin!(PTB16, Ptb16, ptb16, PORTB, Portb, PTB16_PIN, PortPin, PORTB_PERIPH, PTB16_OWNED, PTB16_REF_COUNT, 16);
   pin_source!(Ptb16, super::adc::Adc1Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptb16, super::ftm::Ftm0Ch4, super::sig::SigFtm, 2);
   pin_source!(Ptb16, super::lpspi::Lpspi1, super::sig::SigSpiSout, 3);
pin!(PTB17, Ptb17, ptb17, PORTB, Portb, PTB17_PIN, PortPin, PORTB_PERIPH, PTB17_OWNED, PTB17_REF_COUNT, 17);
   pin_source!(Ptb17, super::ftm::Ftm0Ch5, super::sig::SigFtm, 2);
   pin_source!(Ptb17, super::lpspi::Lpspi1, super::sig::SigSpiPcs3, 3);
pin!(PTC0, Ptc0, ptc0, PORTC, Portc, PTC0_PIN, PortPin, PORTC_PERIPH, PTC0_OWNED, PTC0_REF_COUNT, 0);
   pin_source!(Ptc0, super::adc::Adc0Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptc0, super::ftm::Ftm0Ch0, super::sig::SigFtm, 2);
   pin_source!(Ptc0, super::lpspi::Lpspi2, super::sig::SigSpiSin, 3);
   pin_source!(Ptc0, super::ftm::Ftm1Ch6, super::sig::SigFtm, 6);
pin!(PTC1, Ptc1, ptc1, PORTC, Portc, PTC1_PIN, PortPin, PORTC_PERIPH, PTC1_OWNED, PTC1_REF_COUNT, 1);
   pin_source!(Ptc1, super::adc::Adc0Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptc1, super::ftm::Ftm0Ch1, super::sig::SigFtm, 2);
   pin_source!(Ptc1, super::lpspi::Lpspi2, super::sig::SigSpiSout, 3);
   pin_source!(Ptc1, super::ftm::Ftm1Ch7, super::sig::SigFtm, 6);
pin!(PTC2, Ptc2, ptc2, PORTC, Portc, PTC2_PIN, PortPin, PORTC_PERIPH, PTC2_OWNED, PTC2_REF_COUNT, 2);
   pin_source!(Ptc2, super::adc::Adc0Ch10, super::sig::SigAdc, 0);
   pin_source!(Ptc2, super::ftm::Ftm0Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptc2, super::lpuart::Lpuart0, super::sig::SigRx, 4);
pin!(PTC3, Ptc3, ptc3, PORTC, Portc, PTC3_PIN, PortPin, PORTC_PERIPH, PTC3_OWNED, PTC3_REF_COUNT, 3);
   pin_source!(Ptc3, super::adc::Adc0Ch11, super::sig::SigAdc, 0);
   pin_source!(Ptc3, super::ftm::Ftm0Ch3, super::sig::SigFtm, 2);
   pin_source!(Ptc3, super::lpuart::Lpuart0, super::sig::SigTx, 4);
pin!(PTC4, Ptc4, ptc4, PORTC, Portc, PTC4_PIN, PortPin, PORTC_PERIPH, PTC4_OWNED, PTC4_REF_COUNT, 4);
   pin_source!(Ptc4, super::ftm::Ftm1Ch0, super::sig::SigFtm, 2);
pin!(PTC5, Ptc5, ptc5, PORTC, Portc, PTC5_PIN, PortPin, PORTC_PERIPH, PTC5_OWNED, PTC5_REF_COUNT, 5);
   pin_source!(Ptc5, super::ftm::Ftm2Ch0, super::sig::SigFtm, 2);
pin!(PTC6, Ptc6, ptc6, PORTC, Portc, PTC6_PIN, PortPin, PORTC_PERIPH, PTC6_OWNED, PTC6_REF_COUNT, 6);
   pin_source!(Ptc6, super::adc::Adc1Ch4, super::sig::SigAdc, 0);
   pin_source!(Ptc6, super::lpuart::Lpuart1, super::sig::SigRx, 2);
   pin_source!(Ptc6, super::ftm::Ftm3Ch2, super::sig::SigFtm, 4);
pin!(PTC7, Ptc7, ptc7, PORTC, Portc, PTC7_PIN, PortPin, PORTC_PERIPH, PTC7_OWNED, PTC7_REF_COUNT, 7);
   pin_source!(Ptc7, super::adc::Adc1Ch5, super::sig::SigAdc, 0);
   pin_source!(Ptc7, super::lpuart::Lpuart1, super::sig::SigTx, 2);
   pin_source!(Ptc7, super::ftm::Ftm3Ch3, super::sig::SigFtm, 4);
pin!(PTC8, Ptc8, ptc8, PORTC, Portc, PTC8_PIN, PortPin, PORTC_PERIPH, PTC8_OWNED, PTC8_REF_COUNT, 8);
   pin_source!(Ptc8, super::lpuart::Lpuart1, super::sig::SigRx, 2);
   pin_source!(Ptc8, super::lpuart::Lpuart0, super::sig::SigCts, 6);
pin!(PTC9, Ptc9, ptc9, PORTC, Portc, PTC9_PIN, PortPin, PORTC_PERIPH, PTC9_OWNED, PTC9_REF_COUNT, 9);
   pin_source!(Ptc9, super::lpuart::Lpuart1, super::sig::SigTx, 2);
   pin_source!(Ptc9, super::lpuart::Lpuart0, super::sig::SigRts, 6);
pin!(PTC10, Ptc10, ptc10, PORTC, Portc, PTC10_PIN, PortPin, PORTC_PERIPH, PTC10_OWNED, PTC10_REF_COUNT, 10);
   pin_source!(Ptc10, super::ftm::Ftm3Ch4, super::sig::SigFtm, 2);
pin!(PTC11, Ptc11, ptc11, PORTC, Portc, PTC11_PIN, PortPin, PORTC_PERIPH, PTC11_OWNED, PTC11_REF_COUNT, 11);
   pin_source!(Ptc11, super::ftm::Ftm3Ch5, super::sig::SigFtm, 2);
pin!(PTC12, Ptc12, ptc12, PORTC, Portc, PTC12_PIN, PortPin, PORTC_PERIPH, PTC12_OWNED, PTC12_REF_COUNT, 12);
   pin_source!(Ptc12, super::ftm::Ftm3Ch6, super::sig::SigFtm, 2);
   pin_source!(Ptc12, super::ftm::Ftm2Ch6, super::sig::SigFtm, 3);
   pin_source!(Ptc12, super::lpuart::Lpuart2, super::sig::SigCts, 4);
pin!(PTC13, Ptc13, ptc13, PORTC, Portc, PTC13_PIN, PortPin, PORTC_PERIPH, PTC13_OWNED, PTC13_REF_COUNT, 13);
   pin_source!(Ptc13, super::ftm::Ftm3Ch7, super::sig::SigFtm, 2);
   pin_source!(Ptc13, super::ftm::Ftm2Ch7, super::sig::SigFtm, 3);
   pin_source!(Ptc13, super::lpuart::Lpuart2, super::sig::SigRts, 4);
pin!(PTC14, Ptc14, ptc14, PORTC, Portc, PTC14_PIN, PortPin, PORTC_PERIPH, PTC14_OWNED, PTC14_REF_COUNT, 14);
   pin_source!(Ptc14, super::adc::Adc0Ch12, super::sig::SigAdc, 0);
   pin_source!(Ptc14, super::ftm::Ftm1Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptc14, super::lpspi::Lpspi2, super::sig::SigSpiPcs0, 3);
pin!(PTC15, Ptc15, ptc15, PORTC, Portc, PTC15_PIN, PortPin, PORTC_PERIPH, PTC15_OWNED, PTC15_REF_COUNT, 15);
   pin_source!(Ptc15, super::adc::Adc0Ch13, super::sig::SigAdc, 0);
   pin_source!(Ptc15, super::ftm::Ftm1Ch3, super::sig::SigFtm, 2);
   pin_source!(Ptc15, super::lpspi::Lpspi2, super::sig::SigSpiSck, 3);
pin!(PTC16, Ptc16, ptc16, PORTC, Portc, PTC16_PIN, PortPin, PORTC_PERIPH, PTC16_OWNED, PTC16_REF_COUNT, 16);
   pin_source!(Ptc16, super::adc::Adc0Ch14, super::sig::SigAdc, 0);
pin!(PTC17, Ptc17, ptc17, PORTC, Portc, PTC17_PIN, PortPin, PORTC_PERIPH, PTC17_OWNED, PTC17_REF_COUNT, 17);
   pin_source!(Ptc17, super::adc::Adc0Ch15, super::sig::SigAdc, 0);
pin!(PTD0, Ptd0, ptd0, PORTD, Portd, PTD0_PIN, PortPin, PORTD_PERIPH, PTD0_OWNED, PTD0_REF_COUNT, 0);
   pin_source!(Ptd0, super::ftm::Ftm0Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptd0, super::lpspi::Lpspi1, super::sig::SigSpiSck, 3);
   pin_source!(Ptd0, super::ftm::Ftm2Ch0, super::sig::SigFtm, 4);
pin!(PTD1, Ptd1, ptd1, PORTD, Portd, PTD1_PIN, PortPin, PORTD_PERIPH, PTD1_OWNED, PTD1_REF_COUNT, 1);
   pin_source!(Ptd1, super::ftm::Ftm0Ch3, super::sig::SigFtm, 2);
   pin_source!(Ptd1, super::lpspi::Lpspi1, super::sig::SigSpiSin, 3);
   pin_source!(Ptd1, super::ftm::Ftm2Ch1, super::sig::SigFtm, 4);
pin!(PTD2, Ptd2, ptd2, PORTD, Portd, PTD2_PIN, PortPin, PORTD_PERIPH, PTD2_OWNED, PTD2_REF_COUNT, 2);
   pin_source!(Ptd2, super::adc::Adc1Ch2, super::sig::SigAdc, 0);
   pin_source!(Ptd2, super::ftm::Ftm3Ch4, super::sig::SigFtm, 2);
   pin_source!(Ptd2, super::lpspi::Lpspi1, super::sig::SigSpiSout, 3);
pin!(PTD3, Ptd3, ptd3, PORTD, Portd, PTD3_PIN, PortPin, PORTD_PERIPH, PTD3_OWNED, PTD3_REF_COUNT, 3);
   pin_source!(Ptd3, super::adc::Adc1Ch3, super::sig::SigAdc, 0);
   pin_source!(Ptd3, super::ftm::Ftm3Ch5, super::sig::SigFtm, 2);
   pin_source!(Ptd3, super::lpspi::Lpspi1, super::sig::SigSpiPcs0, 3);
pin!(PTD4, Ptd4, ptd4, PORTD, Portd, PTD4_PIN, PortPin, PORTD_PERIPH, PTD4_OWNED, PTD4_REF_COUNT, 4);
   pin_source!(Ptd4, super::adc::Adc1Ch6, super::sig::SigAdc, 0);
pin!(PTD5, Ptd5, ptd5, PORTD, Portd, PTD5_PIN, PortPin, PORTD_PERIPH, PTD5_OWNED, PTD5_REF_COUNT, 5);
   pin_source!(Ptd5, super::ftm::Ftm2Ch3, super::sig::SigFtm, 2);
pin!(PTD6, Ptd6, ptd6, PORTD, Portd, PTD6_PIN, PortPin, PORTD_PERIPH, PTD6_OWNED, PTD6_REF_COUNT, 6);
   pin_source!(Ptd6, super::lpuart::Lpuart2, super::sig::SigRx, 2);
pin!(PTD7, Ptd7, ptd7, PORTD, Portd, PTD7_PIN, PortPin, PORTD_PERIPH, PTD7_OWNED, PTD7_REF_COUNT, 7);
   pin_source!(Ptd7, super::lpuart::Lpuart2, super::sig::SigTx, 2);
pin!(PTD8, Ptd8, ptd8, PORTD, Portd, PTD8_PIN, PortPin, PORTD_PERIPH, PTD8_OWNED, PTD8_REF_COUNT, 8);
   pin_source!(Ptd8, super::ftm::Ftm1Ch4, super::sig::SigFtm, 6);
pin!(PTD9, Ptd9, ptd9, PORTD, Portd, PTD9_PIN, PortPin, PORTD_PERIPH, PTD9_OWNED, PTD9_REF_COUNT, 9);
   pin_source!(Ptd9, super::ftm::Ftm1Ch5, super::sig::SigFtm, 6);
pin!(PTD10, Ptd10, ptd10, PORTD, Portd, PTD10_PIN, PortPin, PORTD_PERIPH, PTD10_OWNED, PTD10_REF_COUNT, 10);
   pin_source!(Ptd10, super::ftm::Ftm2Ch0, super::sig::SigFtm, 2);
pin!(PTD11, Ptd11, ptd11, PORTD, Portd, PTD11_PIN, PortPin, PORTD_PERIPH, PTD11_OWNED, PTD11_REF_COUNT, 11);
   pin_source!(Ptd11, super::ftm::Ftm2Ch1, super::sig::SigFtm, 2);
   pin_source!(Ptd11, super::lpuart::Lpuart2, super::sig::SigCts, 6);
pin!(PTD12, Ptd12, ptd12, PORTD, Portd, PTD12_PIN, PortPin, PORTD_PERIPH, PTD12_OWNED, PTD12_REF_COUNT, 12);
   pin_source!(Ptd12, super::ftm::Ftm2Ch2, super::sig::SigFtm, 2);
   pin_source!(Ptd12, super::lpuart::Lpuart2, super::sig::SigRts, 6);
pin!(PTD13, Ptd13, ptd13, PORTD, Portd, PTD13_PIN, PortPin, PORTD_PERIPH, PTD13_OWNED, PTD13_REF_COUNT, 13);
   pin_source!(Ptd13, super::ftm::Ftm2Ch4, super::sig::SigFtm, 2);
   pin_source!(Ptd13, super::lpuart::Lpuart1, super::sig::SigRx, 3);
pin!(PTD14, Ptd14, ptd14, PORTD, Portd, PTD14_PIN, PortPin, PORTD_PERIPH, PTD14_OWNED, PTD14_REF_COUNT, 14);
   pin_source!(Ptd14, super::ftm::Ftm2Ch5, super::sig::SigFtm, 2);
   pin_source!(Ptd14, super::lpuart::Lpuart1, super::sig::SigTx, 3);
pin!(PTD15, Ptd15, ptd15, PORTD, Portd, PTD15_PIN, PortPin, PORTD_PERIPH, PTD15_OWNED, PTD15_REF_COUNT, 15);
   pin_source!(Ptd15, super::ftm::Ftm0Ch0, super::sig::SigFtm, 2);
   pin_source!(Ptd15, super::lpspi::Lpspi0, super::sig::SigSpiSck, 4);
pin!(PTD16, Ptd16, ptd16, PORTD, Portd, PTD16_PIN, PortPin, PORTD_PERIPH, PTD16_OWNED, PTD16_REF_COUNT, 16);
   pin_source!(Ptd16, super::ftm::Ftm0Ch1, super::sig::SigFtm, 2);
   pin_source!(Ptd16, super::lpspi::Lpspi0, super::sig::SigSpiSin, 4);
pin!(PTD17, Ptd17, ptd17, PORTD, Portd, PTD17_PIN, PortPin, PORTD_PERIPH, PTD17_OWNED, PTD17_REF_COUNT, 17);
   pin_source!(Ptd17, super::lpuart::Lpuart2, super::sig::SigRx, 3);
pin!(PTE0, Pte0, pte0, PORTE, Porte, PTE0_PIN, PortPin, PORTE_PERIPH, PTE0_OWNED, PTE0_REF_COUNT, 0);
   pin_source!(Pte0, super::lpspi::Lpspi0, super::sig::SigSpiSck, 2);
   pin_source!(Pte0, super::lpspi::Lpspi1, super::sig::SigSpiSout, 5);
pin!(PTE1, Pte1, pte1, PORTE, Porte, PTE1_PIN, PortPin, PORTE_PERIPH, PTE1_OWNED, PTE1_REF_COUNT, 1);
   pin_source!(Pte1, super::lpspi::Lpspi0, super::sig::SigSpiSin, 2);
   pin_source!(Pte1, super::lpi2c::Lpi2c0, super::sig::SigI2cHreq, 3);
   pin_source!(Pte1, super::lpspi::Lpspi1, super::sig::SigSpiPcs0, 5);
pin!(PTE2, Pte2, pte2, PORTE, Porte, PTE2_PIN, PortPin, PORTE_PERIPH, PTE2_OWNED, PTE2_REF_COUNT, 2);
   pin_source!(Pte2, super::adc::Adc1Ch10, super::sig::SigAdc, 0);
   pin_source!(Pte2, super::lpspi::Lpspi0, super::sig::SigSpiSout, 2);
   pin_source!(Pte2, super::ftm::Ftm3Ch6, super::sig::SigFtm, 4);
   pin_source!(Pte2, super::lpuart::Lpuart1, super::sig::SigCts, 6);
pin!(PTE3, Pte3, pte3, PORTE, Porte, PTE3_PIN, PortPin, PORTE_PERIPH, PTE3_OWNED, PTE3_REF_COUNT, 3);
   pin_source!(Pte3, super::lpuart::Lpuart2, super::sig::SigRts, 3);
pin!(PTE4, Pte4, pte4, PORTE, Porte, PTE4_PIN, PortPin, PORTE_PERIPH, PTE4_OWNED, PTE4_REF_COUNT, 4);
   pin_source!(Pte4, super::ftm::Ftm2Ch2, super::sig::SigFtm, 4);
pin!(PTE5, Pte5, pte5, PORTE, Porte, PTE5_PIN, PortPin, PORTE_PERIPH, PTE5_OWNED, PTE5_REF_COUNT, 5);
   pin_source!(Pte5, super::ftm::Ftm2Ch3, super::sig::SigFtm, 4);
pin!(PTE6, Pte6, pte6, PORTE, Porte, PTE6_PIN, PortPin, PORTE_PERIPH, PTE6_OWNED, PTE6_REF_COUNT, 6);
   pin_source!(Pte6, super::adc::Adc1Ch11, super::sig::SigAdc, 0);
   pin_source!(Pte6, super::lpspi::Lpspi0, super::sig::SigSpiPcs2, 2);
   pin_source!(Pte6, super::ftm::Ftm3Ch7, super::sig::SigFtm, 4);
   pin_source!(Pte6, super::lpuart::Lpuart1, super::sig::SigRts, 6);
pin!(PTE7, Pte7, pte7, PORTE, Porte, PTE7_PIN, PortPin, PORTE_PERIPH, PTE7_OWNED, PTE7_REF_COUNT, 7);
   pin_source!(Pte7, super::ftm::Ftm0Ch7, super::sig::SigFtm, 2);
pin!(PTE8, Pte8, pte8, PORTE, Porte, PTE8_PIN, PortPin, PORTE_PERIPH, PTE8_OWNED, PTE8_REF_COUNT, 8);
   pin_source!(Pte8, super::ftm::Ftm0Ch6, super::sig::SigFtm, 2);
pin!(PTE9, Pte9, pte9, PORTE, Porte, PTE9_PIN, PortPin, PORTE_PERIPH, PTE9_OWNED, PTE9_REF_COUNT, 9);
   pin_source!(Pte9, super::ftm::Ftm0Ch7, super::sig::SigFtm, 2);
   pin_source!(Pte9, super::lpuart::Lpuart2, super::sig::SigCts, 3);
pin!(PTE10, Pte10, pte10, PORTE, Porte, PTE10_PIN, PortPin, PORTE_PERIPH, PTE10_OWNED, PTE10_REF_COUNT, 10);
   pin_source!(Pte10, super::lpspi::Lpspi2, super::sig::SigSpiPcs1, 3);
   pin_source!(Pte10, super::ftm::Ftm2Ch4, super::sig::SigFtm, 4);
pin!(PTE11, Pte11, pte11, PORTE, Porte, PTE11_PIN, PortPin, PORTE_PERIPH, PTE11_OWNED, PTE11_REF_COUNT, 11);
   pin_source!(Pte11, super::lpspi::Lpspi2, super::sig::SigSpiPcs0, 2);
   pin_source!(Pte11, super::ftm::Ftm2Ch5, super::sig::SigFtm, 4);
pin!(PTE12, Pte12, pte12, PORTE, Porte, PTE12_PIN, PortPin, PORTE_PERIPH, PTE12_OWNED, PTE12_REF_COUNT, 12);
   pin_source!(Pte12, super::lpuart::Lpuart2, super::sig::SigTx, 3);
pin!(PTE13, Pte13, pte13, PORTE, Porte, PTE13_PIN, PortPin, PORTE_PERIPH, PTE13_OWNED, PTE13_REF_COUNT, 13);
   pin_source!(Pte13, super::lpspi::Lpspi2, super::sig::SigSpiPcs2, 3);
pin!(PTE14, Pte14, pte14, PORTE, Porte, PTE14_PIN, PortPin, PORTE_PERIPH, PTE14_OWNED, PTE14_REF_COUNT, 14);
pin!(PTE15, Pte15, pte15, PORTE, Porte, PTE15_PIN, PortPin, PORTE_PERIPH, PTE15_OWNED, PTE15_REF_COUNT, 15);
   pin_source!(Pte15, super::lpuart::Lpuart1, super::sig::SigCts, 2);
   pin_source!(Pte15, super::lpspi::Lpspi2, super::sig::SigSpiSck, 3);
   pin_source!(Pte15, super::ftm::Ftm2Ch6, super::sig::SigFtm, 4);
pin!(PTE16, Pte16, pte16, PORTE, Porte, PTE16_PIN, PortPin, PORTE_PERIPH, PTE16_OWNED, PTE16_REF_COUNT, 16);
   pin_source!(Pte16, super::lpuart::Lpuart1, super::sig::SigRts, 2);
   pin_source!(Pte16, super::lpspi::Lpspi2, super::sig::SigSpiSin, 3);
   pin_source!(Pte16, super::ftm::Ftm2Ch7, super::sig::SigFtm, 4);
pub use super::gpio::*;

pin!(PA0, Pa0, pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, PA0_OWNED, PA0_REF_COUNT, 0);
pin!(PA1, Pa1, pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, PA1_OWNED, PA1_REF_COUNT, 1);
pin!(PA2, Pa2, pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, PA2_OWNED, PA2_REF_COUNT, 2);
pin!(PA3, Pa3, pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, PA3_OWNED, PA3_REF_COUNT, 3);
pin!(PA4, Pa4, pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, PA4_OWNED, PA4_REF_COUNT, 4);
pin!(PA5, Pa5, pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, PA5_OWNED, PA5_REF_COUNT, 5);
pin!(PA6, Pa6, pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, PA6_OWNED, PA6_REF_COUNT, 6);
pin!(PA7, Pa7, pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, PA7_OWNED, PA7_REF_COUNT, 7);
pin!(PA8, Pa8, pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, PA8_OWNED, PA8_REF_COUNT, 8);
pin!(PA9, Pa9, pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, PA9_OWNED, PA9_REF_COUNT, 9);
pin!(PA10, Pa10, pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, PA10_OWNED, PA10_REF_COUNT, 10);
pin!(PA11, Pa11, pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, PA11_OWNED, PA11_REF_COUNT, 11);
pin!(PA12, Pa12, pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, PA12_OWNED, PA12_REF_COUNT, 12);
pin!(PA13, Pa13, pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, PA13_OWNED, PA13_REF_COUNT, 13);
pin!(PA14, Pa14, pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, PA14_OWNED, PA14_REF_COUNT, 14);
pin!(PA15, Pa15, pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, PA15_OWNED, PA15_REF_COUNT, 15);
pin!(PA16, Pa16, pa16, GPIOA, Gpioa, PA16_PIN, GpioPin, GPIOA_PERIPH, PA16_OWNED, PA16_REF_COUNT, 16);
pin!(PA17, Pa17, pa17, GPIOA, Gpioa, PA17_PIN, GpioPin, GPIOA_PERIPH, PA17_OWNED, PA17_REF_COUNT, 17);
pin!(PB0, Pb0, pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, PB0_OWNED, PB0_REF_COUNT, 0);
pin!(PB1, Pb1, pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, PB1_OWNED, PB1_REF_COUNT, 1);
pin!(PB2, Pb2, pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, PB2_OWNED, PB2_REF_COUNT, 2);
pin!(PB3, Pb3, pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, PB3_OWNED, PB3_REF_COUNT, 3);
pin!(PB4, Pb4, pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, PB4_OWNED, PB4_REF_COUNT, 4);
pin!(PB5, Pb5, pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, PB5_OWNED, PB5_REF_COUNT, 5);
pin!(PB6, Pb6, pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, PB6_OWNED, PB6_REF_COUNT, 6);
pin!(PB7, Pb7, pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, PB7_OWNED, PB7_REF_COUNT, 7);
pin!(PB8, Pb8, pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, PB8_OWNED, PB8_REF_COUNT, 8);
pin!(PB9, Pb9, pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, PB9_OWNED, PB9_REF_COUNT, 9);
pin!(PB10, Pb10, pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, PB10_OWNED, PB10_REF_COUNT, 10);
pin!(PB11, Pb11, pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, PB11_OWNED, PB11_REF_COUNT, 11);
pin!(PB12, Pb12, pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, PB12_OWNED, PB12_REF_COUNT, 12);
pin!(PB13, Pb13, pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, PB13_OWNED, PB13_REF_COUNT, 13);
pin!(PB14, Pb14, pb14, GPIOB, Gpiob, PB14_PIN, GpioPin, GPIOB_PERIPH, PB14_OWNED, PB14_REF_COUNT, 14);
pin!(PB15, Pb15, pb15, GPIOB, Gpiob, PB15_PIN, GpioPin, GPIOB_PERIPH, PB15_OWNED, PB15_REF_COUNT, 15);
pin!(PB16, Pb16, pb16, GPIOB, Gpiob, PB16_PIN, GpioPin, GPIOB_PERIPH, PB16_OWNED, PB16_REF_COUNT, 16);
pin!(PB17, Pb17, pb17, GPIOB, Gpiob, PB17_PIN, GpioPin, GPIOB_PERIPH, PB17_OWNED, PB17_REF_COUNT, 17);
pin!(PC0, Pc0, pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, PC0_OWNED, PC0_REF_COUNT, 0);
pin!(PC1, Pc1, pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, PC1_OWNED, PC1_REF_COUNT, 1);
pin!(PC2, Pc2, pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, PC2_OWNED, PC2_REF_COUNT, 2);
pin!(PC3, Pc3, pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, PC3_OWNED, PC3_REF_COUNT, 3);
pin!(PC4, Pc4, pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, PC4_OWNED, PC4_REF_COUNT, 4);
pin!(PC5, Pc5, pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, PC5_OWNED, PC5_REF_COUNT, 5);
pin!(PC6, Pc6, pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, PC6_OWNED, PC6_REF_COUNT, 6);
pin!(PC7, Pc7, pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, PC7_OWNED, PC7_REF_COUNT, 7);
pin!(PC8, Pc8, pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, PC8_OWNED, PC8_REF_COUNT, 8);
pin!(PC9, Pc9, pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, PC9_OWNED, PC9_REF_COUNT, 9);
pin!(PC10, Pc10, pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, PC10_OWNED, PC10_REF_COUNT, 10);
pin!(PC11, Pc11, pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, PC11_OWNED, PC11_REF_COUNT, 11);
pin!(PC12, Pc12, pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, PC12_OWNED, PC12_REF_COUNT, 12);
pin!(PC13, Pc13, pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, PC13_OWNED, PC13_REF_COUNT, 13);
pin!(PC14, Pc14, pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, PC14_OWNED, PC14_REF_COUNT, 14);
pin!(PC15, Pc15, pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, PC15_OWNED, PC15_REF_COUNT, 15);
pin!(PC16, Pc16, pc16, GPIOC, Gpioc, PC16_PIN, GpioPin, GPIOC_PERIPH, PC16_OWNED, PC16_REF_COUNT, 16);
pin!(PC17, Pc17, pc17, GPIOC, Gpioc, PC17_PIN, GpioPin, GPIOC_PERIPH, PC17_OWNED, PC17_REF_COUNT, 17);
pin!(PD0, Pd0, pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, PD0_OWNED, PD0_REF_COUNT, 0);
pin!(PD1, Pd1, pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, PD1_OWNED, PD1_REF_COUNT, 1);
pin!(PD2, Pd2, pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, PD2_OWNED, PD2_REF_COUNT, 2);
pin!(PD3, Pd3, pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, PD3_OWNED, PD3_REF_COUNT, 3);
pin!(PD4, Pd4, pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, PD4_OWNED, PD4_REF_COUNT, 4);
pin!(PD5, Pd5, pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, PD5_OWNED, PD5_REF_COUNT, 5);
pin!(PD6, Pd6, pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, PD6_OWNED, PD6_REF_COUNT, 6);
pin!(PD7, Pd7, pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, PD7_OWNED, PD7_REF_COUNT, 7);
pin!(PD8, Pd8, pd8, GPIOD, Gpiod, PD8_PIN, GpioPin, GPIOD_PERIPH, PD8_OWNED, PD8_REF_COUNT, 8);
pin!(PD9, Pd9, pd9, GPIOD, Gpiod, PD9_PIN, GpioPin, GPIOD_PERIPH, PD9_OWNED, PD9_REF_COUNT, 9);
pin!(PD10, Pd10, pd10, GPIOD, Gpiod, PD10_PIN, GpioPin, GPIOD_PERIPH, PD10_OWNED, PD10_REF_COUNT, 10);
pin!(PD11, Pd11, pd11, GPIOD, Gpiod, PD11_PIN, GpioPin, GPIOD_PERIPH, PD11_OWNED, PD11_REF_COUNT, 11);
pin!(PD12, Pd12, pd12, GPIOD, Gpiod, PD12_PIN, GpioPin, GPIOD_PERIPH, PD12_OWNED, PD12_REF_COUNT, 12);
pin!(PD13, Pd13, pd13, GPIOD, Gpiod, PD13_PIN, GpioPin, GPIOD_PERIPH, PD13_OWNED, PD13_REF_COUNT, 13);
pin!(PD14, Pd14, pd14, GPIOD, Gpiod, PD14_PIN, GpioPin, GPIOD_PERIPH, PD14_OWNED, PD14_REF_COUNT, 14);
pin!(PD15, Pd15, pd15, GPIOD, Gpiod, PD15_PIN, GpioPin, GPIOD_PERIPH, PD15_OWNED, PD15_REF_COUNT, 15);
pin!(PD16, Pd16, pd16, GPIOD, Gpiod, PD16_PIN, GpioPin, GPIOD_PERIPH, PD16_OWNED, PD16_REF_COUNT, 16);
pin!(PD17, Pd17, pd17, GPIOD, Gpiod, PD17_PIN, GpioPin, GPIOD_PERIPH, PD17_OWNED, PD17_REF_COUNT, 17);
pin!(PE0, Pe0, pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, PE0_OWNED, PE0_REF_COUNT, 0);
pin!(PE1, Pe1, pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, PE1_OWNED, PE1_REF_COUNT, 1);
pin!(PE2, Pe2, pe2, GPIOE, Gpioe, PE2_PIN, GpioPin, GPIOE_PERIPH, PE2_OWNED, PE2_REF_COUNT, 2);
pin!(PE3, Pe3, pe3, GPIOE, Gpioe, PE3_PIN, GpioPin, GPIOE_PERIPH, PE3_OWNED, PE3_REF_COUNT, 3);
pin!(PE4, Pe4, pe4, GPIOE, Gpioe, PE4_PIN, GpioPin, GPIOE_PERIPH, PE4_OWNED, PE4_REF_COUNT, 4);
pin!(PE5, Pe5, pe5, GPIOE, Gpioe, PE5_PIN, GpioPin, GPIOE_PERIPH, PE5_OWNED, PE5_REF_COUNT, 5);
pin!(PE6, Pe6, pe6, GPIOE, Gpioe, PE6_PIN, GpioPin, GPIOE_PERIPH, PE6_OWNED, PE6_REF_COUNT, 6);
pin!(PE7, Pe7, pe7, GPIOE, Gpioe, PE7_PIN, GpioPin, GPIOE_PERIPH, PE7_OWNED, PE7_REF_COUNT, 7);
pin!(PE8, Pe8, pe8, GPIOE, Gpioe, PE8_PIN, GpioPin, GPIOE_PERIPH, PE8_OWNED, PE8_REF_COUNT, 8);
pin!(PE9, Pe9, pe9, GPIOE, Gpioe, PE9_PIN, GpioPin, GPIOE_PERIPH, PE9_OWNED, PE9_REF_COUNT, 9);
pin!(PE10, Pe10, pe10, GPIOE, Gpioe, PE10_PIN, GpioPin, GPIOE_PERIPH, PE10_OWNED, PE10_REF_COUNT, 10);
pin!(PE11, Pe11, pe11, GPIOE, Gpioe, PE11_PIN, GpioPin, GPIOE_PERIPH, PE11_OWNED, PE11_REF_COUNT, 11);
pin!(PE12, Pe12, pe12, GPIOE, Gpioe, PE12_PIN, GpioPin, GPIOE_PERIPH, PE12_OWNED, PE12_REF_COUNT, 12);
pin!(PE13, Pe13, pe13, GPIOE, Gpioe, PE13_PIN, GpioPin, GPIOE_PERIPH, PE13_OWNED, PE13_REF_COUNT, 13);
pin!(PE14, Pe14, pe14, GPIOE, Gpioe, PE14_PIN, GpioPin, GPIOE_PERIPH, PE14_OWNED, PE14_REF_COUNT, 14);
pin!(PE15, Pe15, pe15, GPIOE, Gpioe, PE15_PIN, GpioPin, GPIOE_PERIPH, PE15_OWNED, PE15_REF_COUNT, 15);
pin!(PE16, Pe16, pe16, GPIOE, Gpioe, PE16_PIN, GpioPin, GPIOE_PERIPH, PE16_OWNED, PE16_REF_COUNT, 16);
