//! Signals

pub trait Signal<T> {}

pub trait Tim {}
pub trait SignalTim<T> {}
pub trait Adc {}
pub trait SignalAdc<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Cts {}
pub trait SignalCts<T> {}
pub trait Rts {}
pub trait SignalRts<T> {}
pub trait Ck {}
pub trait SignalCk<T> {}

pub struct Tim2Ch1 {}
pub struct Tim2Ch2 {}
pub struct Tim2Ch3 {}
pub struct Tim2Ch4 {}
pub struct Tim3Ch1 {}
pub struct Tim3Ch2 {}
pub struct Tim3Ch3 {}
pub struct Tim3Ch4 {}
pub struct Tim4Ch1 {}
pub struct Tim4Ch2 {}
pub struct Tim4Ch3 {}
pub struct Tim4Ch4 {}
pub struct Adc1In0 {}
pub struct Adc1In1 {}
pub struct Adc1In2 {}
pub struct Adc1In3 {}
pub struct Adc1In4 {}
pub struct Adc1In5 {}
pub struct Adc1In6 {}
pub struct Adc1In7 {}
pub struct Adc1In8 {}
pub struct Adc1In9 {}
pub struct Adc1In10 {}
pub struct Adc1In11 {}
pub struct Adc1In12 {}
pub struct Adc1In13 {}
pub struct Adc1In14 {}
pub struct Adc1In15 {}
pub struct Adc2In0 {}
pub struct Adc2In1 {}
pub struct Adc2In2 {}
pub struct Adc2In3 {}
pub struct Adc2In4 {}
pub struct Adc2In5 {}
pub struct Adc2In6 {}
pub struct Adc2In7 {}
pub struct Adc2In8 {}
pub struct Adc2In9 {}
pub struct Adc2In10 {}
pub struct Adc2In11 {}
pub struct Adc2In12 {}
pub struct Adc2In13 {}
pub struct Adc2In14 {}
pub struct Adc2In15 {}
pub struct Adc3In0 {}
pub struct Adc3In1 {}
pub struct Adc3In2 {}
pub struct Adc3In3 {}
pub struct Adc3In4 {}
pub struct Adc3In5 {}
pub struct Adc3In6 {}
pub struct Adc3In7 {}
pub struct Adc3In8 {}
pub struct Adc3In9 {}
pub struct Adc3In10 {}
pub struct Adc3In11 {}
pub struct Adc3In12 {}
pub struct Adc3In13 {}
pub struct Adc3In14 {}
pub struct Adc3In15 {}
pub struct Usart1Tx {}
pub struct Usart1Rx {}
pub struct Usart1Cts {}
pub struct Usart1Rts {}
pub struct Usart1Ck {}
pub struct Usart2Tx {}
pub struct Usart2Rx {}
pub struct Usart2Cts {}
pub struct Usart2Rts {}
pub struct Usart2Ck {}
pub struct Usart3Tx {}
pub struct Usart3Rx {}
pub struct Usart3Cts {}
pub struct Usart3Rts {}
pub struct Usart3Ck {}
pub struct Usart4Tx {}
pub struct Usart4Rx {}
pub struct Usart4Cts {}
pub struct Usart4Rts {}
pub struct Usart4Ck {}
pub struct Usart5Tx {}
pub struct Usart5Rx {}
pub struct Usart5Cts {}
pub struct Usart5Rts {}
pub struct Usart5Ck {}
pub struct Usart6Tx {}
pub struct Usart6Rx {}
pub struct Usart6Cts {}
pub struct Usart6Rts {}
pub struct Usart6Ck {}
pub struct Tim2Etr {}
pub struct Tim5Ch1 {}
pub struct Tim8Etr {}
pub struct Uart4Tx {}
pub struct EthMiiCrs {}
pub struct Eventout {}
pub struct Tim5Ch2 {}
pub struct Uart4Rx {}
pub struct EthMiiRxClk {}
pub struct EthRmiiRefClk {}
pub struct Tim5Ch3 {}
pub struct Tim9Ch1 {}
pub struct EthMdio {}
pub struct Tim5Ch4 {}
pub struct Tim9Ch2 {}
pub struct OtgHsUlpiD0 {}
pub struct EthMiiCol {}
pub struct LcdB5 {}
pub struct Spi1Nss {}
pub struct Spi3Nss {}
pub struct I2s3Ws {}
pub struct OtgHsSof {}
pub struct DcmiHsync {}
pub struct LcdVsync {}
pub struct Tim8Ch1n {}
pub struct Spi1Sck {}
pub struct OtgHsUlpiCk {}
pub struct Tim1Bkin {}
pub struct Tim8Bkin {}
pub struct Spi1Miso {}
pub struct Tim13Ch1 {}
pub struct DcmiPxclk {}
pub struct LcdG2 {}
pub struct Tim1Ch1n {}
pub struct Spi1Mosi {}
pub struct Tim14Ch1 {}
pub struct EthMiiRxDv {}
pub struct EthRmiiCrsDv {}
pub struct Mco1 {}
pub struct Tim1Ch1 {}
pub struct I2c3Scl {}
pub struct OtgFsSof {}
pub struct LcdR6 {}
pub struct Tim1Ch2 {}
pub struct I2c3Smba {}
pub struct DcmiD0 {}
pub struct Tim1Ch3 {}
pub struct OtgFsId {}
pub struct DcmiD1 {}
pub struct Tim1Ch4 {}
pub struct Can1Rx {}
pub struct OtgFsDm {}
pub struct LcdR4 {}
pub struct Tim1Etr {}
pub struct Can1Tx {}
pub struct OtgFsDp {}
pub struct LcdR5 {}
pub struct Jtms {}
pub struct Swdio {}
pub struct Jtck {}
pub struct Swclk {}
pub struct Jtdi {}
pub struct Tim1Ch2n {}
pub struct Tim8Ch2n {}
pub struct LcdR3 {}
pub struct OtgHsUlpiD1 {}
pub struct EthMiiRxd2 {}
pub struct Tim1Ch3n {}
pub struct Tim8Ch3n {}
pub struct OtgHsUlpiD2 {}
pub struct EthMiiRxd3 {}
pub struct Jtdo {}
pub struct Traceswo {}
pub struct Spi3Sck {}
pub struct Is2cCk {}
pub struct Njtrst {}
pub struct Spi3Miso {}
pub struct I2s3extSd {}
pub struct I2c1Smba {}
pub struct Spi3Mosi {}
pub struct I2s3Sd {}
pub struct Can2Rx {}
pub struct OtgHsUlpiD7 {}
pub struct EthPpsOut {}
pub struct FmcSdcke1 {}
pub struct DcmiD10 {}
pub struct I2c1Scl {}
pub struct Can2Tx {}
pub struct FmcSdne1 {}
pub struct DcmiD5 {}
pub struct I2c1Sda {}
pub struct FmcNl {}
pub struct DcmiVsync {}
pub struct Tim10Ch1 {}
pub struct EthMiiTxd3 {}
pub struct SdioD4 {}
pub struct DcmiD6 {}
pub struct LcdB6 {}
pub struct Tim11Ch1 {}
pub struct Spi2Nss {}
pub struct I2s2Ws {}
pub struct SdioD5 {}
pub struct DcmiD7 {}
pub struct LcdB7 {}
pub struct I2c2Scl {}
pub struct Spi2Sck {}
pub struct I2s2Ck {}
pub struct OtgHsUlpiD3 {}
pub struct EthMiiRxEr {}
pub struct LcdG4 {}
pub struct Sim2Ch4 {}
pub struct I2c2Sda {}
pub struct OtgHsUlpiD4 {}
pub struct EthMiiTxEn {}
pub struct EthRmiiTxEn {}
pub struct LcdG5 {}
pub struct I2c2Smba {}
pub struct OtgHsUlpiD5 {}
pub struct EthMiiTxd0 {}
pub struct EthRmiiTxd0 {}
pub struct OtgHsId {}
pub struct OtgHsUlpiD6 {}
pub struct EthMiiTxd1 {}
pub struct EthRmiiTxd1 {}
pub struct Tim2Ch2n {}
pub struct Spi2Miso {}
pub struct I2s2extSd {}
pub struct Tim12Ch1 {}
pub struct OtgHsDm {}
pub struct RtcRefin {}
pub struct Spi2Mosi {}
pub struct I2s2Sd {}
pub struct Tim12Ch2 {}
pub struct OtgHsDp {}
pub struct OtgHsUlpiStp {}
pub struct FmcSdnwe {}
pub struct EthMdc {}
pub struct OtgHsUlpiDir {}
pub struct EthMiiTxd2 {}
pub struct FmcSdne0 {}
pub struct OtgHsUlpiNxt {}
pub struct EthMiiTxClk {}
pub struct FmcSdcke0 {}
pub struct EthMiiRxd0 {}
pub struct EthRmiiRxd0 {}
pub struct EthMiiRxd1 {}
pub struct EthRmiiRxd1 {}
pub struct Tim8Ch1 {}
pub struct I2s2Mck {}
pub struct SdioD6 {}
pub struct LcdHsync {}
pub struct Tim8Ch2 {}
pub struct I2s3Mck {}
pub struct SdioD7 {}
pub struct LcdG6 {}
pub struct Tim8Ch3 {}
pub struct SdioD0 {}
pub struct DcmiD2 {}
pub struct Mco2 {}
pub struct Tim8Ch4 {}
pub struct I2c3Sda {}
pub struct I2sCkin {}
pub struct SdioD1 {}
pub struct DcmiD3 {}
pub struct I2s3Ck {}
pub struct SdioD2 {}
pub struct DcmiD8 {}
pub struct LcdR2 {}
pub struct SdioD3 {}
pub struct DcmiD4 {}
pub struct SdioCk {}
pub struct DcmiD9 {}
pub struct FmcD2 {}
pub struct FmcD3 {}
pub struct Tim3Etr {}
pub struct Uart5Rx {}
pub struct SdioCmd {}
pub struct DcmiD11 {}
pub struct FmcClk {}
pub struct LcdG7 {}
pub struct FmcNoe {}
pub struct FmcNwe {}
pub struct Sai1SdA {}
pub struct FmcNwait {}
pub struct LcdB2 {}
pub struct FmcNe1 {}
pub struct FmcNce2 {}
pub struct FmcD13 {}
pub struct FmcD14 {}
pub struct FmcD15 {}
pub struct FmcA16 {}
pub struct FmcA17 {}
pub struct FmcA18 {}
pub struct FmcD0 {}
pub struct FmcD1 {}
pub struct Tim4Etr {}
pub struct Uart8Rx {}
pub struct FmcNbl0 {}
pub struct Uart8Tx {}
pub struct FmcNbl1 {}
pub struct Traceclk {}
pub struct Spi4Sck {}
pub struct Sai1MclkA {}
pub struct FmcA23 {}
pub struct Traced0 {}
pub struct Sai1SdB {}
pub struct FmcA19 {}
pub struct Traced1 {}
pub struct Spi4Nss {}
pub struct Sai1FsA {}
pub struct FmcA20 {}
pub struct Traced2 {}
pub struct Spi4Miso {}
pub struct Sai1SckA {}
pub struct FmcA21 {}
pub struct Traced3 {}
pub struct Spi4Mosi {}
pub struct FmcA22 {}
pub struct FmcD4 {}
pub struct FmcD5 {}
pub struct FmcD6 {}
pub struct FmcD7 {}
pub struct FmcD8 {}
pub struct LcdG3 {}
pub struct FmcD9 {}
pub struct LcdB4 {}
pub struct FmcD10 {}
pub struct LcdDe {}
pub struct FmcD11 {}
pub struct LcdClk {}
pub struct FmcD12 {}
pub struct LcdR7 {}
pub struct FmcA0 {}
pub struct FmcA1 {}
pub struct FmcA2 {}
pub struct FmcA3 {}
pub struct FmcA4 {}
pub struct FmcA5 {}
pub struct Spi5Nss {}
pub struct Uart7Rx {}
pub struct FmcNiord {}
pub struct Spi5Sck {}
pub struct Sai1MclkB {}
pub struct Uart7Tx {}
pub struct FmcNreg {}
pub struct Spi5Miso {}
pub struct SaiSckB {}
pub struct FmcNiowr {}
pub struct Spi5Mosi {}
pub struct SaiFsB {}
pub struct FmcCd {}
pub struct FmcIntr {}
pub struct FmcSdnras {}
pub struct DcmiD12 {}
pub struct FmcA6 {}
pub struct FmcA7 {}
pub struct FmcA8 {}
pub struct FmcA9 {}
pub struct FmcA10 {}
pub struct FmcA11 {}
pub struct FmcA12 {}
pub struct FmcA13 {}
pub struct FmcA14 {}
pub struct FmcBa0 {}
pub struct FmcA15 {}
pub struct FmcBa1 {}
pub struct FmcInt2 {}
pub struct FmcInt3 {}
pub struct DcmiD13 {}
pub struct Spi6Nss {}
pub struct EthPsOut {}
pub struct FmcSdclk {}
pub struct FmcNe2 {}
pub struct FmcNce3 {}
pub struct FmcNce41 {}
pub struct FmcNe3 {}
pub struct Spi6Miso {}
pub struct FmcNce42 {}
pub struct LcdB3 {}
pub struct Spi6Sck {}
pub struct FmcNe4 {}
pub struct LcdB1 {}
pub struct Spi6Mosi {}
pub struct FmcA24 {}
pub struct FmcA25 {}
pub struct FmcSndcas {}
pub struct LcdR0 {}
pub struct LcdR1 {}
pub struct FmcD16 {}
pub struct FmcD17 {}
pub struct FmcD18 {}
pub struct FmcD19 {}
pub struct FmcD20 {}
pub struct FmcD21 {}
pub struct FmcD22 {}
pub struct FmcD23 {}
pub struct FmcD24 {}
pub struct FmcD25 {}
pub struct FmcD26 {}
pub struct FmcD27 {}
pub struct FmcNbl2 {}
pub struct FmcNbl3 {}
pub struct DcmVsync {}
pub struct FmcD28 {}
pub struct FmcD29 {}
pub struct FmcD30 {}
pub struct FmcD31 {}
pub struct LcdG0 {}
pub struct LcdG1 {}
pub struct LcdB0 {}
