//! Signals

pub trait Signal<T> {}

pub trait Ain {}
pub trait SignalAin<T> {}
pub trait Pwm {}
pub trait SignalPwm<T> {}
pub trait Ccp {}
pub trait SignalCcp<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}

pub struct Ain0 {}
pub struct Ain1 {}
pub struct Ain2 {}
pub struct Ain3 {}
pub struct Ain4 {}
pub struct Ain5 {}
pub struct Ain6 {}
pub struct Ain7 {}
pub struct Ain8 {}
pub struct Ain9 {}
pub struct Ain10 {}
pub struct Ain11 {}
pub struct Ain12 {}
pub struct Ain13 {}
pub struct Ain14 {}
pub struct Ain15 {}
pub struct Ain16 {}
pub struct Ain17 {}
pub struct Ain18 {}
pub struct Ain19 {}
pub struct M0pwm0 {}
pub struct M0pwm1 {}
pub struct M0pwm2 {}
pub struct M0pwm3 {}
pub struct T0ccp0 {}
pub struct T0ccp1 {}
pub struct T1ccp0 {}
pub struct T1ccp1 {}
pub struct T2ccp0 {}
pub struct T2ccp1 {}
pub struct T3ccp0 {}
pub struct T3ccp1 {}
pub struct T4ccp0 {}
pub struct T4ccp1 {}
pub struct T5ccp0 {}
pub struct T5ccp1 {}
pub struct T6ccp0 {}
pub struct T6ccp1 {}
pub struct T7ccp0 {}
pub struct T7ccp1 {}
pub struct U0rx {}
pub struct U0tx {}
pub struct U1rx {}
pub struct U1tx {}
pub struct U2rx {}
pub struct U2tx {}
pub struct U3rx {}
pub struct U3tx {}
pub struct U4rx {}
pub struct U4tx {}
pub struct U5rx {}
pub struct U5tx {}
pub struct U6rx {}
pub struct U6tx {}
pub struct U7rx {}
pub struct U7tx {}
pub struct I2c9scl {}
pub struct Can0rx {}
pub struct I2c9sda {}
pub struct Can0tx {}
pub struct I2c8scl {}
pub struct Ssi0clk {}
pub struct I2c8sda {}
pub struct Ssi0fss {}
pub struct I2c7scl {}
pub struct Ssi0xdat0 {}
pub struct I2c7sda {}
pub struct Ssi0xdat1 {}
pub struct I2c6scl {}
pub struct Usb0epen {}
pub struct Ssi0xdat2 {}
pub struct Epi0s8 {}
pub struct I2c6sda {}
pub struct Usb0pflt {}
pub struct Ssi0xdat3 {}
pub struct Epi0s9 {}
pub struct Usb0id {}
pub struct I2c5scl {}
pub struct Can1rx {}
pub struct Usb0vbus {}
pub struct I2c5sda {}
pub struct Can1tx {}
pub struct I2c0scl {}
pub struct Usb0stp {}
pub struct Epi0s27 {}
pub struct I2c0sda {}
pub struct Usb0clk {}
pub struct Epi0s28 {}
pub struct U0cts {}
pub struct Ssi1fss {}
pub struct U0rts {}
pub struct Ssi1clk {}
pub struct Tck {}
pub struct Swclk {}
pub struct Tms {}
pub struct Swdio {}
pub struct Tdi {}
pub struct Tdo {}
pub struct Swo {}
pub struct C1Neg {}
pub struct Epi0s7 {}
pub struct C1Pos {}
pub struct Rtcclk {}
pub struct Epi0s6 {}
pub struct C0Neg {}
pub struct Epi0s5 {}
pub struct C0Pos {}
pub struct Epi0s4 {}
pub struct C0o {}
pub struct Ssi2xdat1 {}
pub struct C1o {}
pub struct Ssi2xdat0 {}
pub struct C2o {}
pub struct Ssi2fss {}
pub struct Ssi2clk {}
pub struct Ssi1xdat2 {}
pub struct Ssi1xdat3 {}
pub struct U2rts {}
pub struct Ssi2xdat3 {}
pub struct U2cts {}
pub struct Nmi {}
pub struct Ssi2xdat2 {}
pub struct U1rts {}
pub struct U1dsr {}
pub struct U1dcd {}
pub struct U1dtr {}
pub struct U1ri {}
pub struct Ssi1xdat0 {}
pub struct Ssi1xdat1 {}
pub struct En0led0 {}
pub struct Ssi3xdat1 {}
pub struct Trd2 {}
pub struct En0led2 {}
pub struct Ssi3xdat0 {}
pub struct Trd1 {}
pub struct Ssi3fss {}
pub struct Trd0 {}
pub struct Ssi3clk {}
pub struct Trclk {}
pub struct En0led1 {}
pub struct M0fault0 {}
pub struct Ssi3xdat2 {}
pub struct Trd3 {}
pub struct I2c1scl {}
pub struct En0pps {}
pub struct M0pwm4 {}
pub struct Epi0s11 {}
pub struct I2c1sda {}
pub struct M0pwm5 {}
pub struct Epi0s10 {}
pub struct Epi0s0 {}
pub struct Epi0s1 {}
pub struct U0dcd {}
pub struct Epi0s2 {}
pub struct U0dsr {}
pub struct Epi0s3 {}
pub struct U4rts {}
pub struct U4cts {}
pub struct I2c3scl {}
pub struct M0pwm6 {}
pub struct Epi0s32 {}
pub struct I2c3sda {}
pub struct M0pwm7 {}
pub struct Epi0s31 {}
pub struct I2c4scl {}
pub struct M0fault1 {}
pub struct Epi0s25 {}
pub struct U0ri {}
pub struct I2c4sda {}
pub struct M0fault2 {}
pub struct Epi0s24 {}
pub struct I2c2sda {}
pub struct M0fault3 {}
pub struct Usb0d0 {}
pub struct Epi0s16 {}
pub struct I2c2scl {}
pub struct Pha0 {}
pub struct Usb0d1 {}
pub struct Epi0s17 {}
pub struct Phb0 {}
pub struct Usb0d2 {}
pub struct Epi0s18 {}
pub struct Idx0 {}
pub struct Usb0d3 {}
pub struct Epi0s19 {}
pub struct Usb0d4 {}
pub struct Epi0s26 {}
pub struct Usb0d5 {}
pub struct Epi0s33 {}
pub struct Usb0dp {}
pub struct Usb0dm {}
pub struct Epi0s15 {}
pub struct Epi0s14 {}
pub struct Epi0s13 {}
pub struct Epi0s12 {}
pub struct Tmpr3 {}
pub struct Tmpr2 {}
pub struct Tmpr1 {}
pub struct Tmpr0 {}
pub struct U1cts {}
pub struct Epi0s29 {}
pub struct Epi0s30 {}
pub struct U3rts {}
pub struct Epi0s34 {}
pub struct U3cts {}
pub struct Epi0s35 {}
pub struct C2Pos {}
pub struct Ssi3xdat {}
pub struct C2Neg {}
pub struct U0dtr {}
pub struct Usb0nxt {}
pub struct Usb0dir {}
pub struct Usb0d7 {}
pub struct Usb0d6 {}
pub struct Epi0s20 {}
pub struct Epi0s21 {}
pub struct Epi0s22 {}
pub struct Epi0s23 {}
pub struct Divsclk {}
