[package]
name = "bobbin-samd51-example"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]
edition = "2018"

[[bin]]
name = "blinky"
path = "src/blinky.rs"
doc = false

[[bin]]
name = "serial"
path = "src/serial.rs"
doc = false

[[bin]]
name = "console"
path = "src/console.rs"
doc = false

[dependencies]
cortex-m-rt = "0.6"
cortex-m = "0.6"
panic-abort = "0.3"

[dependencies.samd51]
path = "../../mcu/bobbin-sam/samd51"
features = ["SAMD51x19"]

[profile.dev]
panic = "abort"
opt-level = "s"
incremental = false
lto = true

[profile.release]
panic = "abort"
opt-level = "s"
debug = true
incremental = false
lto = true