#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;

pub use super::port::*;

pin!(PTA0, Pta0, pta0, PORTA, Porta, PTA0_PIN, PortPin, PORTA_PERIPH, PTA0_OWNED, PTA0_REF_COUNT, 0);
   pin_source!(Pta0, super::tpm::Tpm0Ch5, super::sig::SigTpm, 3);
pin!(PTA1, Pta1, pta1, PORTA, Porta, PTA1_PIN, PortPin, PORTA_PERIPH, PTA1_OWNED, PTA1_REF_COUNT, 1);
   pin_source!(Pta1, super::uart0::Uart0, super::sig::SigRx, 2);
   pin_source!(Pta1, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTA2, Pta2, pta2, PORTA, Porta, PTA2_PIN, PortPin, PORTA_PERIPH, PTA2_OWNED, PTA2_REF_COUNT, 2);
   pin_source!(Pta2, super::uart0::Uart0, super::sig::SigTx, 2);
   pin_source!(Pta2, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTA3, Pta3, pta3, PORTA, Porta, PTA3_PIN, PortPin, PORTA_PERIPH, PTA3_OWNED, PTA3_REF_COUNT, 3);
   pin_source!(Pta3, super::i2c::I2c1, super::sig::SigI2cScl, 2);
   pin_source!(Pta3, super::tpm::Tpm0Ch0, super::sig::SigTpm, 3);
pin!(PTA4, Pta4, pta4, PORTA, Porta, PTA4_PIN, PortPin, PORTA_PERIPH, PTA4_OWNED, PTA4_REF_COUNT, 4);
   pin_source!(Pta4, super::i2c::I2c1, super::sig::SigI2cSda, 2);
   pin_source!(Pta4, super::tpm::Tpm0Ch1, super::sig::SigTpm, 3);
pin!(PTA5, Pta5, pta5, PORTA, Porta, PTA5_PIN, PortPin, PORTA_PERIPH, PTA5_OWNED, PTA5_REF_COUNT, 5);
   pin_source!(Pta5, super::tpm::Tpm0Ch2, super::sig::SigTpm, 3);
pin!(PTA12, Pta12, pta12, PORTA, Porta, PTA12_PIN, PortPin, PORTA_PERIPH, PTA12_OWNED, PTA12_REF_COUNT, 12);
   pin_source!(Pta12, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
pin!(PTA13, Pta13, pta13, PORTA, Porta, PTA13_PIN, PortPin, PORTA_PERIPH, PTA13_OWNED, PTA13_REF_COUNT, 13);
   pin_source!(Pta13, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
pin!(PTA18, Pta18, pta18, PORTA, Porta, PTA18_PIN, PortPin, PORTA_PERIPH, PTA18_OWNED, PTA18_REF_COUNT, 18);
   pin_source!(Pta18, super::uart::Uart1, super::sig::SigRx, 3);
pin!(PTA19, Pta19, pta19, PORTA, Porta, PTA19_PIN, PortPin, PORTA_PERIPH, PTA19_OWNED, PTA19_REF_COUNT, 19);
   pin_source!(Pta19, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Pta19, super::lptmr::Lptmr0, super::sig::SigLptmrAlt1, 6);
pin!(PTA20, Pta20, pta20, PORTA, Porta, PTA20_PIN, PortPin, PORTA_PERIPH, PTA20_OWNED, PTA20_REF_COUNT, 20);
pin!(PTB0, Ptb0, ptb0, PORTB, Portb, PTB0_PIN, PortPin, PORTB_PERIPH, PTB0_OWNED, PTB0_REF_COUNT, 0);
   pin_source!(Ptb0, super::adc::Adc0Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptb0, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
pin!(PTB1, Ptb1, ptb1, PORTB, Portb, PTB1_PIN, PortPin, PORTB_PERIPH, PTB1_OWNED, PTB1_REF_COUNT, 1);
   pin_source!(Ptb1, super::adc::Adc0Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptb1, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
pin!(PTB2, Ptb2, ptb2, PORTB, Portb, PTB2_PIN, PortPin, PORTB_PERIPH, PTB2_OWNED, PTB2_REF_COUNT, 2);
   pin_source!(Ptb2, super::adc::Adc0Ch12, super::sig::SigAdc, 0);
   pin_source!(Ptb2, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptb2, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTB3, Ptb3, ptb3, PORTB, Portb, PTB3_PIN, PortPin, PORTB_PERIPH, PTB3_OWNED, PTB3_REF_COUNT, 3);
   pin_source!(Ptb3, super::adc::Adc0Ch13, super::sig::SigAdc, 0);
   pin_source!(Ptb3, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptb3, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTB16, Ptb16, ptb16, PORTB, Portb, PTB16_PIN, PortPin, PORTB_PERIPH, PTB16_OWNED, PTB16_REF_COUNT, 16);
   pin_source!(Ptb16, super::uart0::Uart0, super::sig::SigRx, 3);
pin!(PTB17, Ptb17, ptb17, PORTB, Portb, PTB17_PIN, PortPin, PORTB_PERIPH, PTB17_OWNED, PTB17_REF_COUNT, 17);
   pin_source!(Ptb17, super::uart0::Uart0, super::sig::SigTx, 3);
pin!(PTB18, Ptb18, ptb18, PORTB, Portb, PTB18_PIN, PortPin, PORTB_PERIPH, PTB18_OWNED, PTB18_REF_COUNT, 18);
   pin_source!(Ptb18, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTB19, Ptb19, ptb19, PORTB, Portb, PTB19_PIN, PortPin, PORTB_PERIPH, PTB19_OWNED, PTB19_REF_COUNT, 19);
   pin_source!(Ptb19, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTC0, Ptc0, ptc0, PORTC, Portc, PTC0_PIN, PortPin, PORTC_PERIPH, PTC0_OWNED, PTC0_REF_COUNT, 0);
   pin_source!(Ptc0, super::adc::Adc0Ch14, super::sig::SigAdc, 0);
pin!(PTC1, Ptc1, ptc1, PORTC, Portc, PTC1_PIN, PortPin, PORTC_PERIPH, PTC1_OWNED, PTC1_REF_COUNT, 1);
   pin_source!(Ptc1, super::adc::Adc0Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptc1, super::i2c::I2c1, super::sig::SigI2cScl, 2);
   pin_source!(Ptc1, super::tpm::Tpm0Ch0, super::sig::SigTpm, 4);
pin!(PTC2, Ptc2, ptc2, PORTC, Portc, PTC2_PIN, PortPin, PORTC_PERIPH, PTC2_OWNED, PTC2_REF_COUNT, 2);
   pin_source!(Ptc2, super::adc::Adc0Ch11, super::sig::SigAdc, 0);
   pin_source!(Ptc2, super::i2c::I2c1, super::sig::SigI2cSda, 2);
   pin_source!(Ptc2, super::tpm::Tpm0Ch1, super::sig::SigTpm, 4);
pin!(PTC3, Ptc3, ptc3, PORTC, Portc, PTC3_PIN, PortPin, PORTC_PERIPH, PTC3_OWNED, PTC3_REF_COUNT, 3);
   pin_source!(Ptc3, super::uart::Uart1, super::sig::SigRx, 3);
   pin_source!(Ptc3, super::tpm::Tpm0Ch2, super::sig::SigTpm, 4);
pin!(PTC4, Ptc4, ptc4, PORTC, Portc, PTC4_PIN, PortPin, PORTC_PERIPH, PTC4_OWNED, PTC4_REF_COUNT, 4);
   pin_source!(Ptc4, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptc4, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Ptc4, super::tpm::Tpm0Ch3, super::sig::SigTpm, 4);
pin!(PTC5, Ptc5, ptc5, PORTC, Portc, PTC5_PIN, PortPin, PORTC_PERIPH, PTC5_OWNED, PTC5_REF_COUNT, 5);
   pin_source!(Ptc5, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Ptc5, super::lptmr::Lptmr0, super::sig::SigLptmrAlt2, 3);
pin!(PTC6, Ptc6, ptc6, PORTC, Portc, PTC6_PIN, PortPin, PORTC_PERIPH, PTC6_OWNED, PTC6_REF_COUNT, 6);
   pin_source!(Ptc6, super::spi::Spi0, super::sig::SigSpiMosi, 2);
   pin_source!(Ptc6, super::spi::Spi0, super::sig::SigSpiMiso, 5);
pin!(PTC7, Ptc7, ptc7, PORTC, Portc, PTC7_PIN, PortPin, PORTC_PERIPH, PTC7_OWNED, PTC7_REF_COUNT, 7);
   pin_source!(Ptc7, super::spi::Spi0, super::sig::SigSpiMiso, 2);
   pin_source!(Ptc7, super::spi::Spi0, super::sig::SigSpiMosi, 5);
pin!(PTC8, Ptc8, ptc8, PORTC, Portc, PTC8_PIN, PortPin, PORTC_PERIPH, PTC8_OWNED, PTC8_REF_COUNT, 8);
   pin_source!(Ptc8, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptc8, super::tpm::Tpm0Ch4, super::sig::SigTpm, 3);
pin!(PTC9, Ptc9, ptc9, PORTC, Portc, PTC9_PIN, PortPin, PORTC_PERIPH, PTC9_OWNED, PTC9_REF_COUNT, 9);
   pin_source!(Ptc9, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptc9, super::tpm::Tpm0Ch5, super::sig::SigTpm, 3);
pin!(PTC10, Ptc10, ptc10, PORTC, Portc, PTC10_PIN, PortPin, PORTC_PERIPH, PTC10_OWNED, PTC10_REF_COUNT, 10);
   pin_source!(Ptc10, super::i2c::I2c1, super::sig::SigI2cScl, 2);
pin!(PTC11, Ptc11, ptc11, PORTC, Portc, PTC11_PIN, PortPin, PORTC_PERIPH, PTC11_OWNED, PTC11_REF_COUNT, 11);
   pin_source!(Ptc11, super::i2c::I2c1, super::sig::SigI2cSda, 2);
pin!(PTD0, Ptd0, ptd0, PORTD, Portd, PTD0_PIN, PortPin, PORTD_PERIPH, PTD0_OWNED, PTD0_REF_COUNT, 0);
   pin_source!(Ptd0, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptd0, super::tpm::Tpm0Ch0, super::sig::SigTpm, 4);
pin!(PTD1, Ptd1, ptd1, PORTD, Portd, PTD1_PIN, PortPin, PORTD_PERIPH, PTD1_OWNED, PTD1_REF_COUNT, 1);
   pin_source!(Ptd1, super::adc::Adc0Ch5, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd1, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Ptd1, super::tpm::Tpm0Ch1, super::sig::SigTpm, 4);
pin!(PTD2, Ptd2, ptd2, PORTD, Portd, PTD2_PIN, PortPin, PORTD_PERIPH, PTD2_OWNED, PTD2_REF_COUNT, 2);
   pin_source!(Ptd2, super::spi::Spi0, super::sig::SigSpiMosi, 2);
   pin_source!(Ptd2, super::uart::Uart2, super::sig::SigRx, 3);
   pin_source!(Ptd2, super::tpm::Tpm0Ch2, super::sig::SigTpm, 4);
   pin_source!(Ptd2, super::spi::Spi0, super::sig::SigSpiMiso, 5);
pin!(PTD3, Ptd3, ptd3, PORTD, Portd, PTD3_PIN, PortPin, PORTD_PERIPH, PTD3_OWNED, PTD3_REF_COUNT, 3);
   pin_source!(Ptd3, super::spi::Spi0, super::sig::SigSpiMiso, 2);
   pin_source!(Ptd3, super::uart::Uart2, super::sig::SigTx, 3);
   pin_source!(Ptd3, super::tpm::Tpm0Ch3, super::sig::SigTpm, 4);
   pin_source!(Ptd3, super::spi::Spi0, super::sig::SigSpiMosi, 5);
pin!(PTD4, Ptd4, ptd4, PORTD, Portd, PTD4_PIN, PortPin, PORTD_PERIPH, PTD4_OWNED, PTD4_REF_COUNT, 4);
   pin_source!(Ptd4, super::spi::Spi1, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptd4, super::uart::Uart2, super::sig::SigRx, 3);
   pin_source!(Ptd4, super::tpm::Tpm0Ch4, super::sig::SigTpm, 4);
pin!(PTD5, Ptd5, ptd5, PORTD, Portd, PTD5_PIN, PortPin, PORTD_PERIPH, PTD5_OWNED, PTD5_REF_COUNT, 5);
   pin_source!(Ptd5, super::adc::Adc0Ch6, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd5, super::spi::Spi1, super::sig::SigSpiSck, 2);
   pin_source!(Ptd5, super::uart::Uart2, super::sig::SigTx, 3);
   pin_source!(Ptd5, super::tpm::Tpm0Ch5, super::sig::SigTpm, 4);
pin!(PTD6, Ptd6, ptd6, PORTD, Portd, PTD6_PIN, PortPin, PORTD_PERIPH, PTD6_OWNED, PTD6_REF_COUNT, 6);
   pin_source!(Ptd6, super::adc::Adc0Ch7, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd6, super::uart0::Uart0, super::sig::SigRx, 3);
pin!(PTD7, Ptd7, ptd7, PORTD, Portd, PTD7_PIN, PortPin, PORTD_PERIPH, PTD7_OWNED, PTD7_REF_COUNT, 7);
   pin_source!(Ptd7, super::uart0::Uart0, super::sig::SigTx, 3);
pin!(PTE0, Pte0, pte0, PORTE, Porte, PTE0_PIN, PortPin, PORTE_PERIPH, PTE0_OWNED, PTE0_REF_COUNT, 0);
   pin_source!(Pte0, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Pte0, super::i2c::I2c1, super::sig::SigI2cSda, 6);
pin!(PTE1, Pte1, pte1, PORTE, Porte, PTE1_PIN, PortPin, PORTE_PERIPH, PTE1_OWNED, PTE1_REF_COUNT, 1);
   pin_source!(Pte1, super::uart::Uart1, super::sig::SigRx, 3);
   pin_source!(Pte1, super::i2c::I2c1, super::sig::SigI2cScl, 6);
pin!(PTE20, Pte20, pte20, PORTE, Porte, PTE20_PIN, PortPin, PORTE_PERIPH, PTE20_OWNED, PTE20_REF_COUNT, 20);
   pin_source!(Pte20, super::adc::Adc0Ch0, super::sig::SigAdcDp, 0);
   pin_source!(Pte20, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte20, super::uart0::Uart0, super::sig::SigTx, 4);
pin!(PTE21, Pte21, pte21, PORTE, Porte, PTE21_PIN, PortPin, PORTE_PERIPH, PTE21_OWNED, PTE21_REF_COUNT, 21);
   pin_source!(Pte21, super::adc::Adc0Ch0, super::sig::SigAdcDm, 0);
   pin_source!(Pte21, super::adc::Adc0Ch4, super::sig::SigAdcSea, 0);
   pin_source!(Pte21, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte21, super::uart0::Uart0, super::sig::SigRx, 4);
pin!(PTE22, Pte22, pte22, PORTE, Porte, PTE22_PIN, PortPin, PORTE_PERIPH, PTE22_OWNED, PTE22_REF_COUNT, 22);
   pin_source!(Pte22, super::adc::Adc0Ch3, super::sig::SigAdcDp, 0);
   pin_source!(Pte22, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte22, super::uart::Uart2, super::sig::SigTx, 4);
pin!(PTE23, Pte23, pte23, PORTE, Porte, PTE23_PIN, PortPin, PORTE_PERIPH, PTE23_OWNED, PTE23_REF_COUNT, 23);
   pin_source!(Pte23, super::adc::Adc0Ch3, super::sig::SigAdcDm, 0);
   pin_source!(Pte23, super::adc::Adc0Ch7, super::sig::SigAdcSea, 0);
   pin_source!(Pte23, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte23, super::uart::Uart2, super::sig::SigRx, 4);
pin!(PTE24, Pte24, pte24, PORTE, Porte, PTE24_PIN, PortPin, PORTE_PERIPH, PTE24_OWNED, PTE24_REF_COUNT, 24);
   pin_source!(Pte24, super::tpm::Tpm0Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte24, super::i2c::I2c0, super::sig::SigI2cScl, 5);
pin!(PTE25, Pte25, pte25, PORTE, Porte, PTE25_PIN, PortPin, PORTE_PERIPH, PTE25_OWNED, PTE25_REF_COUNT, 25);
   pin_source!(Pte25, super::tpm::Tpm0Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte25, super::i2c::I2c0, super::sig::SigI2cSda, 5);
pin!(PTE29, Pte29, pte29, PORTE, Porte, PTE29_PIN, PortPin, PORTE_PERIPH, PTE29_OWNED, PTE29_REF_COUNT, 29);
   pin_source!(Pte29, super::adc::Adc0Ch4, super::sig::SigAdcSeb, 0);
   pin_source!(Pte29, super::tpm::Tpm0Ch2, super::sig::SigTpm, 3);
pin!(PTE30, Pte30, pte30, PORTE, Porte, PTE30_PIN, PortPin, PORTE_PERIPH, PTE30_OWNED, PTE30_REF_COUNT, 30);
   pin_source!(Pte30, super::adc::Adc0Ch23, super::sig::SigAdc, 0);
   pin_source!(Pte30, super::tpm::Tpm0Ch3, super::sig::SigTpm, 3);
pin!(PTE31, Pte31, pte31, PORTE, Porte, PTE31_PIN, PortPin, PORTE_PERIPH, PTE31_OWNED, PTE31_REF_COUNT, 31);
   pin_source!(Pte31, super::tpm::Tpm0Ch4, super::sig::SigTpm, 3);
pub use super::gpio::*;

pin!(PA0, Pa0, pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, PA0_OWNED, PA0_REF_COUNT, 0);
pin!(PA1, Pa1, pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, PA1_OWNED, PA1_REF_COUNT, 1);
pin!(PA2, Pa2, pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, PA2_OWNED, PA2_REF_COUNT, 2);
pin!(PA3, Pa3, pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, PA3_OWNED, PA3_REF_COUNT, 3);
pin!(PA4, Pa4, pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, PA4_OWNED, PA4_REF_COUNT, 4);
pin!(PA5, Pa5, pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, PA5_OWNED, PA5_REF_COUNT, 5);
pin!(PA12, Pa12, pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, PA12_OWNED, PA12_REF_COUNT, 12);
pin!(PA13, Pa13, pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, PA13_OWNED, PA13_REF_COUNT, 13);
pin!(PA18, Pa18, pa18, GPIOA, Gpioa, PA18_PIN, GpioPin, GPIOA_PERIPH, PA18_OWNED, PA18_REF_COUNT, 18);
pin!(PA19, Pa19, pa19, GPIOA, Gpioa, PA19_PIN, GpioPin, GPIOA_PERIPH, PA19_OWNED, PA19_REF_COUNT, 19);
pin!(PA20, Pa20, pa20, GPIOA, Gpioa, PA20_PIN, GpioPin, GPIOA_PERIPH, PA20_OWNED, PA20_REF_COUNT, 20);
pin!(PB0, Pb0, pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, PB0_OWNED, PB0_REF_COUNT, 0);
pin!(PB1, Pb1, pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, PB1_OWNED, PB1_REF_COUNT, 1);
pin!(PB2, Pb2, pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, PB2_OWNED, PB2_REF_COUNT, 2);
pin!(PB3, Pb3, pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, PB3_OWNED, PB3_REF_COUNT, 3);
pin!(PB16, Pb16, pb16, GPIOB, Gpiob, PB16_PIN, GpioPin, GPIOB_PERIPH, PB16_OWNED, PB16_REF_COUNT, 16);
pin!(PB17, Pb17, pb17, GPIOB, Gpiob, PB17_PIN, GpioPin, GPIOB_PERIPH, PB17_OWNED, PB17_REF_COUNT, 17);
pin!(PB18, Pb18, pb18, GPIOB, Gpiob, PB18_PIN, GpioPin, GPIOB_PERIPH, PB18_OWNED, PB18_REF_COUNT, 18);
pin!(PB19, Pb19, pb19, GPIOB, Gpiob, PB19_PIN, GpioPin, GPIOB_PERIPH, PB19_OWNED, PB19_REF_COUNT, 19);
pin!(PC0, Pc0, pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, PC0_OWNED, PC0_REF_COUNT, 0);
pin!(PC1, Pc1, pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, PC1_OWNED, PC1_REF_COUNT, 1);
pin!(PC2, Pc2, pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, PC2_OWNED, PC2_REF_COUNT, 2);
pin!(PC3, Pc3, pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, PC3_OWNED, PC3_REF_COUNT, 3);
pin!(PC4, Pc4, pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, PC4_OWNED, PC4_REF_COUNT, 4);
pin!(PC5, Pc5, pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, PC5_OWNED, PC5_REF_COUNT, 5);
pin!(PC6, Pc6, pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, PC6_OWNED, PC6_REF_COUNT, 6);
pin!(PC7, Pc7, pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, PC7_OWNED, PC7_REF_COUNT, 7);
pin!(PC8, Pc8, pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, PC8_OWNED, PC8_REF_COUNT, 8);
pin!(PC9, Pc9, pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, PC9_OWNED, PC9_REF_COUNT, 9);
pin!(PC10, Pc10, pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, PC10_OWNED, PC10_REF_COUNT, 10);
pin!(PC11, Pc11, pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, PC11_OWNED, PC11_REF_COUNT, 11);
pin!(PD0, Pd0, pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, PD0_OWNED, PD0_REF_COUNT, 0);
pin!(PD1, Pd1, pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, PD1_OWNED, PD1_REF_COUNT, 1);
pin!(PD2, Pd2, pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, PD2_OWNED, PD2_REF_COUNT, 2);
pin!(PD3, Pd3, pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, PD3_OWNED, PD3_REF_COUNT, 3);
pin!(PD4, Pd4, pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, PD4_OWNED, PD4_REF_COUNT, 4);
pin!(PD5, Pd5, pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, PD5_OWNED, PD5_REF_COUNT, 5);
pin!(PD6, Pd6, pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, PD6_OWNED, PD6_REF_COUNT, 6);
pin!(PD7, Pd7, pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, PD7_OWNED, PD7_REF_COUNT, 7);
pin!(PE0, Pe0, pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, PE0_OWNED, PE0_REF_COUNT, 0);
pin!(PE1, Pe1, pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, PE1_OWNED, PE1_REF_COUNT, 1);
pin!(PE20, Pe20, pe20, GPIOE, Gpioe, PE20_PIN, GpioPin, GPIOE_PERIPH, PE20_OWNED, PE20_REF_COUNT, 20);
pin!(PE21, Pe21, pe21, GPIOE, Gpioe, PE21_PIN, GpioPin, GPIOE_PERIPH, PE21_OWNED, PE21_REF_COUNT, 21);
pin!(PE22, Pe22, pe22, GPIOE, Gpioe, PE22_PIN, GpioPin, GPIOE_PERIPH, PE22_OWNED, PE22_REF_COUNT, 22);
pin!(PE23, Pe23, pe23, GPIOE, Gpioe, PE23_PIN, GpioPin, GPIOE_PERIPH, PE23_OWNED, PE23_REF_COUNT, 23);
pin!(PE24, Pe24, pe24, GPIOE, Gpioe, PE24_PIN, GpioPin, GPIOE_PERIPH, PE24_OWNED, PE24_REF_COUNT, 24);
pin!(PE25, Pe25, pe25, GPIOE, Gpioe, PE25_PIN, GpioPin, GPIOE_PERIPH, PE25_OWNED, PE25_REF_COUNT, 25);
pin!(PE29, Pe29, pe29, GPIOE, Gpioe, PE29_PIN, GpioPin, GPIOE_PERIPH, PE29_OWNED, PE29_REF_COUNT, 29);
pin!(PE30, Pe30, pe30, GPIOE, Gpioe, PE30_PIN, GpioPin, GPIOE_PERIPH, PE30_OWNED, PE30_REF_COUNT, 30);
pin!(PE31, Pe31, pe31, GPIOE, Gpioe, PE31_PIN, GpioPin, GPIOE_PERIPH, PE31_OWNED, PE31_REF_COUNT, 31);
