#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;
pub use super::port::*;

pin!(PTA0, Pta0, PORTA, Porta, PTA0_PIN, PortPin, PORTA_PERIPH, 0);
   pin_source!(Pta0, super::tpm::Tpm0Ch5, super::sig::SigTpm, 3);
pin!(PTA1, Pta1, PORTA, Porta, PTA1_PIN, PortPin, PORTA_PERIPH, 1);
   pin_source!(Pta1, super::uart0::Uart0, super::sig::SigRx, 2);
   pin_source!(Pta1, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTA2, Pta2, PORTA, Porta, PTA2_PIN, PortPin, PORTA_PERIPH, 2);
   pin_source!(Pta2, super::uart0::Uart0, super::sig::SigTx, 2);
   pin_source!(Pta2, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTA3, Pta3, PORTA, Porta, PTA3_PIN, PortPin, PORTA_PERIPH, 3);
   pin_source!(Pta3, super::i2c::I2c1, super::sig::SigI2cScl, 2);
   pin_source!(Pta3, super::tpm::Tpm0Ch0, super::sig::SigTpm, 3);
pin!(PTA4, Pta4, PORTA, Porta, PTA4_PIN, PortPin, PORTA_PERIPH, 4);
   pin_source!(Pta4, super::i2c::I2c1, super::sig::SigI2cSda, 2);
   pin_source!(Pta4, super::tpm::Tpm0Ch1, super::sig::SigTpm, 3);
pin!(PTA5, Pta5, PORTA, Porta, PTA5_PIN, PortPin, PORTA_PERIPH, 5);
   pin_source!(Pta5, super::tpm::Tpm0Ch2, super::sig::SigTpm, 3);
pin!(PTA12, Pta12, PORTA, Porta, PTA12_PIN, PortPin, PORTA_PERIPH, 12);
   pin_source!(Pta12, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
pin!(PTA13, Pta13, PORTA, Porta, PTA13_PIN, PortPin, PORTA_PERIPH, 13);
   pin_source!(Pta13, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
pin!(PTA18, Pta18, PORTA, Porta, PTA18_PIN, PortPin, PORTA_PERIPH, 18);
   pin_source!(Pta18, super::uart::Uart1, super::sig::SigRx, 3);
pin!(PTA19, Pta19, PORTA, Porta, PTA19_PIN, PortPin, PORTA_PERIPH, 19);
   pin_source!(Pta19, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Pta19, super::lptmr::Lptmr0, super::sig::SigLptmrAlt1, 6);
pin!(PTA20, Pta20, PORTA, Porta, PTA20_PIN, PortPin, PORTA_PERIPH, 20);
pin!(PTB0, Ptb0, PORTB, Portb, PTB0_PIN, PortPin, PORTB_PERIPH, 0);
   pin_source!(Ptb0, super::adc::Adc0Ch8, super::sig::SigAdc, 0);
   pin_source!(Ptb0, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptb0, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
pin!(PTB1, Ptb1, PORTB, Portb, PTB1_PIN, PortPin, PORTB_PERIPH, 1);
   pin_source!(Ptb1, super::adc::Adc0Ch9, super::sig::SigAdc, 0);
   pin_source!(Ptb1, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptb1, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
pin!(PTB2, Ptb2, PORTB, Portb, PTB2_PIN, PortPin, PORTB_PERIPH, 2);
   pin_source!(Ptb2, super::adc::Adc0Ch12, super::sig::SigAdc, 0);
   pin_source!(Ptb2, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptb2, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTB3, Ptb3, PORTB, Portb, PTB3_PIN, PortPin, PORTB_PERIPH, 3);
   pin_source!(Ptb3, super::adc::Adc0Ch13, super::sig::SigAdc, 0);
   pin_source!(Ptb3, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptb3, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTB16, Ptb16, PORTB, Portb, PTB16_PIN, PortPin, PORTB_PERIPH, 16);
   pin_source!(Ptb16, super::uart0::Uart0, super::sig::SigRx, 3);
pin!(PTB17, Ptb17, PORTB, Portb, PTB17_PIN, PortPin, PORTB_PERIPH, 17);
   pin_source!(Ptb17, super::uart0::Uart0, super::sig::SigTx, 3);
pin!(PTB18, Ptb18, PORTB, Portb, PTB18_PIN, PortPin, PORTB_PERIPH, 18);
   pin_source!(Ptb18, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
pin!(PTB19, Ptb19, PORTB, Portb, PTB19_PIN, PortPin, PORTB_PERIPH, 19);
   pin_source!(Ptb19, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
pin!(PTC0, Ptc0, PORTC, Portc, PTC0_PIN, PortPin, PORTC_PERIPH, 0);
   pin_source!(Ptc0, super::adc::Adc0Ch14, super::sig::SigAdc, 0);
pin!(PTC1, Ptc1, PORTC, Portc, PTC1_PIN, PortPin, PORTC_PERIPH, 1);
   pin_source!(Ptc1, super::adc::Adc0Ch15, super::sig::SigAdc, 0);
   pin_source!(Ptc1, super::i2c::I2c1, super::sig::SigI2cScl, 2);
   pin_source!(Ptc1, super::tpm::Tpm0Ch0, super::sig::SigTpm, 4);
pin!(PTC2, Ptc2, PORTC, Portc, PTC2_PIN, PortPin, PORTC_PERIPH, 2);
   pin_source!(Ptc2, super::adc::Adc0Ch11, super::sig::SigAdc, 0);
   pin_source!(Ptc2, super::i2c::I2c1, super::sig::SigI2cSda, 2);
   pin_source!(Ptc2, super::tpm::Tpm0Ch1, super::sig::SigTpm, 4);
pin!(PTC3, Ptc3, PORTC, Portc, PTC3_PIN, PortPin, PORTC_PERIPH, 3);
   pin_source!(Ptc3, super::uart::Uart1, super::sig::SigRx, 3);
   pin_source!(Ptc3, super::tpm::Tpm0Ch2, super::sig::SigTpm, 4);
pin!(PTC4, Ptc4, PORTC, Portc, PTC4_PIN, PortPin, PORTC_PERIPH, 4);
   pin_source!(Ptc4, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptc4, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Ptc4, super::tpm::Tpm0Ch3, super::sig::SigTpm, 4);
pin!(PTC5, Ptc5, PORTC, Portc, PTC5_PIN, PortPin, PORTC_PERIPH, 5);
   pin_source!(Ptc5, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Ptc5, super::lptmr::Lptmr0, super::sig::SigLptmrAlt2, 3);
pin!(PTC6, Ptc6, PORTC, Portc, PTC6_PIN, PortPin, PORTC_PERIPH, 6);
   pin_source!(Ptc6, super::spi::Spi0, super::sig::SigSpiMosi, 2);
   pin_source!(Ptc6, super::spi::Spi0, super::sig::SigSpiMiso, 5);
pin!(PTC7, Ptc7, PORTC, Portc, PTC7_PIN, PortPin, PORTC_PERIPH, 7);
   pin_source!(Ptc7, super::spi::Spi0, super::sig::SigSpiMiso, 2);
   pin_source!(Ptc7, super::spi::Spi0, super::sig::SigSpiMosi, 5);
pin!(PTC8, Ptc8, PORTC, Portc, PTC8_PIN, PortPin, PORTC_PERIPH, 8);
   pin_source!(Ptc8, super::i2c::I2c0, super::sig::SigI2cScl, 2);
   pin_source!(Ptc8, super::tpm::Tpm0Ch4, super::sig::SigTpm, 3);
pin!(PTC9, Ptc9, PORTC, Portc, PTC9_PIN, PortPin, PORTC_PERIPH, 9);
   pin_source!(Ptc9, super::i2c::I2c0, super::sig::SigI2cSda, 2);
   pin_source!(Ptc9, super::tpm::Tpm0Ch5, super::sig::SigTpm, 3);
pin!(PTC10, Ptc10, PORTC, Portc, PTC10_PIN, PortPin, PORTC_PERIPH, 10);
   pin_source!(Ptc10, super::i2c::I2c1, super::sig::SigI2cScl, 2);
pin!(PTC11, Ptc11, PORTC, Portc, PTC11_PIN, PortPin, PORTC_PERIPH, 11);
   pin_source!(Ptc11, super::i2c::I2c1, super::sig::SigI2cSda, 2);
pin!(PTD0, Ptd0, PORTD, Portd, PTD0_PIN, PortPin, PORTD_PERIPH, 0);
   pin_source!(Ptd0, super::spi::Spi0, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptd0, super::tpm::Tpm0Ch0, super::sig::SigTpm, 4);
pin!(PTD1, Ptd1, PORTD, Portd, PTD1_PIN, PortPin, PORTD_PERIPH, 1);
   pin_source!(Ptd1, super::adc::Adc0Ch5, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd1, super::spi::Spi0, super::sig::SigSpiSck, 2);
   pin_source!(Ptd1, super::tpm::Tpm0Ch1, super::sig::SigTpm, 4);
pin!(PTD2, Ptd2, PORTD, Portd, PTD2_PIN, PortPin, PORTD_PERIPH, 2);
   pin_source!(Ptd2, super::spi::Spi0, super::sig::SigSpiMosi, 2);
   pin_source!(Ptd2, super::uart::Uart2, super::sig::SigRx, 3);
   pin_source!(Ptd2, super::tpm::Tpm0Ch2, super::sig::SigTpm, 4);
   pin_source!(Ptd2, super::spi::Spi0, super::sig::SigSpiMiso, 5);
pin!(PTD3, Ptd3, PORTD, Portd, PTD3_PIN, PortPin, PORTD_PERIPH, 3);
   pin_source!(Ptd3, super::spi::Spi0, super::sig::SigSpiMiso, 2);
   pin_source!(Ptd3, super::uart::Uart2, super::sig::SigTx, 3);
   pin_source!(Ptd3, super::tpm::Tpm0Ch3, super::sig::SigTpm, 4);
   pin_source!(Ptd3, super::spi::Spi0, super::sig::SigSpiMosi, 5);
pin!(PTD4, Ptd4, PORTD, Portd, PTD4_PIN, PortPin, PORTD_PERIPH, 4);
   pin_source!(Ptd4, super::spi::Spi1, super::sig::SigSpiPcs0, 2);
   pin_source!(Ptd4, super::uart::Uart2, super::sig::SigRx, 3);
   pin_source!(Ptd4, super::tpm::Tpm0Ch4, super::sig::SigTpm, 4);
pin!(PTD5, Ptd5, PORTD, Portd, PTD5_PIN, PortPin, PORTD_PERIPH, 5);
   pin_source!(Ptd5, super::adc::Adc0Ch6, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd5, super::spi::Spi1, super::sig::SigSpiSck, 2);
   pin_source!(Ptd5, super::uart::Uart2, super::sig::SigTx, 3);
   pin_source!(Ptd5, super::tpm::Tpm0Ch5, super::sig::SigTpm, 4);
pin!(PTD6, Ptd6, PORTD, Portd, PTD6_PIN, PortPin, PORTD_PERIPH, 6);
   pin_source!(Ptd6, super::adc::Adc0Ch7, super::sig::SigAdcSeb, 0);
   pin_source!(Ptd6, super::uart0::Uart0, super::sig::SigRx, 3);
pin!(PTD7, Ptd7, PORTD, Portd, PTD7_PIN, PortPin, PORTD_PERIPH, 7);
   pin_source!(Ptd7, super::uart0::Uart0, super::sig::SigTx, 3);
pin!(PTE0, Pte0, PORTE, Porte, PTE0_PIN, PortPin, PORTE_PERIPH, 0);
   pin_source!(Pte0, super::uart::Uart1, super::sig::SigTx, 3);
   pin_source!(Pte0, super::i2c::I2c1, super::sig::SigI2cSda, 6);
pin!(PTE1, Pte1, PORTE, Porte, PTE1_PIN, PortPin, PORTE_PERIPH, 1);
   pin_source!(Pte1, super::uart::Uart1, super::sig::SigRx, 3);
   pin_source!(Pte1, super::i2c::I2c1, super::sig::SigI2cScl, 6);
pin!(PTE20, Pte20, PORTE, Porte, PTE20_PIN, PortPin, PORTE_PERIPH, 20);
   pin_source!(Pte20, super::adc::Adc0Ch0, super::sig::SigAdcDp, 0);
   pin_source!(Pte20, super::tpm::Tpm1Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte20, super::uart0::Uart0, super::sig::SigTx, 4);
pin!(PTE21, Pte21, PORTE, Porte, PTE21_PIN, PortPin, PORTE_PERIPH, 21);
   pin_source!(Pte21, super::adc::Adc0Ch0, super::sig::SigAdcDm, 0);
   pin_source!(Pte21, super::adc::Adc0Ch4, super::sig::SigAdcSea, 0);
   pin_source!(Pte21, super::tpm::Tpm1Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte21, super::uart0::Uart0, super::sig::SigRx, 4);
pin!(PTE22, Pte22, PORTE, Porte, PTE22_PIN, PortPin, PORTE_PERIPH, 22);
   pin_source!(Pte22, super::adc::Adc0Ch3, super::sig::SigAdcDp, 0);
   pin_source!(Pte22, super::tpm::Tpm2Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte22, super::uart::Uart2, super::sig::SigTx, 4);
pin!(PTE23, Pte23, PORTE, Porte, PTE23_PIN, PortPin, PORTE_PERIPH, 23);
   pin_source!(Pte23, super::adc::Adc0Ch3, super::sig::SigAdcDm, 0);
   pin_source!(Pte23, super::adc::Adc0Ch7, super::sig::SigAdcSea, 0);
   pin_source!(Pte23, super::tpm::Tpm2Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte23, super::uart::Uart2, super::sig::SigRx, 4);
pin!(PTE24, Pte24, PORTE, Porte, PTE24_PIN, PortPin, PORTE_PERIPH, 24);
   pin_source!(Pte24, super::tpm::Tpm0Ch0, super::sig::SigTpm, 3);
   pin_source!(Pte24, super::i2c::I2c0, super::sig::SigI2cScl, 5);
pin!(PTE25, Pte25, PORTE, Porte, PTE25_PIN, PortPin, PORTE_PERIPH, 25);
   pin_source!(Pte25, super::tpm::Tpm0Ch1, super::sig::SigTpm, 3);
   pin_source!(Pte25, super::i2c::I2c0, super::sig::SigI2cSda, 5);
pin!(PTE29, Pte29, PORTE, Porte, PTE29_PIN, PortPin, PORTE_PERIPH, 29);
   pin_source!(Pte29, super::adc::Adc0Ch4, super::sig::SigAdcSeb, 0);
   pin_source!(Pte29, super::tpm::Tpm0Ch2, super::sig::SigTpm, 3);
pin!(PTE30, Pte30, PORTE, Porte, PTE30_PIN, PortPin, PORTE_PERIPH, 30);
   pin_source!(Pte30, super::adc::Adc0Ch23, super::sig::SigAdc, 0);
   pin_source!(Pte30, super::tpm::Tpm0Ch3, super::sig::SigTpm, 3);
pin!(PTE31, Pte31, PORTE, Porte, PTE31_PIN, PortPin, PORTE_PERIPH, 31);
   pin_source!(Pte31, super::tpm::Tpm0Ch4, super::sig::SigTpm, 3);
pub use super::gpio::*;

pin!(PA0, Pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, 0);
pin!(PA1, Pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, 1);
pin!(PA2, Pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, 2);
pin!(PA3, Pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, 3);
pin!(PA4, Pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, 4);
pin!(PA5, Pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, 5);
pin!(PA12, Pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, 12);
pin!(PA13, Pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, 13);
pin!(PA18, Pa18, GPIOA, Gpioa, PA18_PIN, GpioPin, GPIOA_PERIPH, 18);
pin!(PA19, Pa19, GPIOA, Gpioa, PA19_PIN, GpioPin, GPIOA_PERIPH, 19);
pin!(PA20, Pa20, GPIOA, Gpioa, PA20_PIN, GpioPin, GPIOA_PERIPH, 20);
pin!(PB0, Pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, 0);
pin!(PB1, Pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, 1);
pin!(PB2, Pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, 2);
pin!(PB3, Pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, 3);
pin!(PB16, Pb16, GPIOB, Gpiob, PB16_PIN, GpioPin, GPIOB_PERIPH, 16);
pin!(PB17, Pb17, GPIOB, Gpiob, PB17_PIN, GpioPin, GPIOB_PERIPH, 17);
pin!(PB18, Pb18, GPIOB, Gpiob, PB18_PIN, GpioPin, GPIOB_PERIPH, 18);
pin!(PB19, Pb19, GPIOB, Gpiob, PB19_PIN, GpioPin, GPIOB_PERIPH, 19);
pin!(PC0, Pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, 0);
pin!(PC1, Pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, 1);
pin!(PC2, Pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, 2);
pin!(PC3, Pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, 3);
pin!(PC4, Pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, 4);
pin!(PC5, Pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, 5);
pin!(PC6, Pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, 6);
pin!(PC7, Pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, 7);
pin!(PC8, Pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, 8);
pin!(PC9, Pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, 9);
pin!(PC10, Pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, 10);
pin!(PC11, Pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, 11);
pin!(PD0, Pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, 0);
pin!(PD1, Pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, 1);
pin!(PD2, Pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, 2);
pin!(PD3, Pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, 3);
pin!(PD4, Pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, 4);
pin!(PD5, Pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, 5);
pin!(PD6, Pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, 6);
pin!(PD7, Pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, 7);
pin!(PE0, Pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, 0);
pin!(PE1, Pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, 1);
pin!(PE20, Pe20, GPIOE, Gpioe, PE20_PIN, GpioPin, GPIOE_PERIPH, 20);
pin!(PE21, Pe21, GPIOE, Gpioe, PE21_PIN, GpioPin, GPIOE_PERIPH, 21);
pin!(PE22, Pe22, GPIOE, Gpioe, PE22_PIN, GpioPin, GPIOE_PERIPH, 22);
pin!(PE23, Pe23, GPIOE, Gpioe, PE23_PIN, GpioPin, GPIOE_PERIPH, 23);
pin!(PE24, Pe24, GPIOE, Gpioe, PE24_PIN, GpioPin, GPIOE_PERIPH, 24);
pin!(PE25, Pe25, GPIOE, Gpioe, PE25_PIN, GpioPin, GPIOE_PERIPH, 25);
pin!(PE29, Pe29, GPIOE, Gpioe, PE29_PIN, GpioPin, GPIOE_PERIPH, 29);
pin!(PE30, Pe30, GPIOE, Gpioe, PE30_PIN, GpioPin, GPIOE_PERIPH, 30);
pin!(PE31, Pe31, GPIOE, Gpioe, PE31_PIN, GpioPin, GPIOE_PERIPH, 31);
