//! Signals

pub trait Signal<T> {}

pub trait Ftm {}
pub trait SignalFtm<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}

pub struct Ftm0Ch0 {}
pub struct Ftm0Ch1 {}
pub struct Ftm0Ch2 {}
pub struct Ftm0Ch3 {}
pub struct Ftm0Ch4 {}
pub struct Ftm0Ch5 {}
pub struct Ftm0Ch6 {}
pub struct Ftm0Ch7 {}
pub struct Ftm1Ch0 {}
pub struct Ftm1Ch1 {}
pub struct Ftm1Ch2 {}
pub struct Ftm1Ch3 {}
pub struct Ftm1Ch4 {}
pub struct Ftm1Ch5 {}
pub struct Ftm1Ch6 {}
pub struct Ftm1Ch7 {}
pub struct Ftm2Ch0 {}
pub struct Ftm2Ch1 {}
pub struct Ftm2Ch2 {}
pub struct Ftm2Ch3 {}
pub struct Ftm2Ch4 {}
pub struct Ftm2Ch5 {}
pub struct Ftm2Ch6 {}
pub struct Ftm2Ch7 {}
pub struct Uart0Tx {}
pub struct Uart0Rx {}
pub struct Uart1Tx {}
pub struct Uart1Rx {}
pub struct Uart2Tx {}
pub struct Uart2Rx {}
pub struct Uart3Tx {}
pub struct Uart3Rx {}
pub struct Uart4Tx {}
pub struct Uart4Rx {}
pub struct Uart5Tx {}
pub struct Uart5Rx {}
pub struct Pta0 {}
pub struct Uart0CtsB {}
pub struct Uart0ColB {}
pub struct JtagTclk {}
pub struct SwdClk {}
pub struct Pta1 {}
pub struct JtagTdi {}
pub struct Pta2 {}
pub struct JtagTdo {}
pub struct TraceSwo {}
pub struct Pta3 {}
pub struct Uart0RtsB {}
pub struct JtagTms {}
pub struct SwdDio {}
pub struct Pta4 {}
pub struct NmiB {}
pub struct Pta5 {}
pub struct UsbClkin {}
pub struct Rmii0Rxer {}
pub struct Mii0Rxer {}
pub struct Cmp2Out {}
pub struct I2s0TxBclk {}
pub struct JtagTrstB {}
pub struct Pta6 {}
pub struct Clkout {}
pub struct TraceClkout {}
pub struct Adc0Se10 {}
pub struct Pta7 {}
pub struct TraceD3 {}
pub struct Adc0Se11 {}
pub struct Pta8 {}
pub struct Ftm1QdPha {}
pub struct TraceD2 {}
pub struct Pta9 {}
pub struct Mii0Rxd3 {}
pub struct Ftm1QdPhb {}
pub struct TraceD1 {}
pub struct Pta10 {}
pub struct Mii0Rxd2 {}
pub struct Ftm2QdPha {}
pub struct TraceD0 {}
pub struct Pta11 {}
pub struct Mii0Rxclk {}
pub struct I2c2Sda {}
pub struct Ftm2QdPhb {}
pub struct Cmp2In0 {}
pub struct Pta12 {}
pub struct Can0Tx {}
pub struct Rmii0Rxd1 {}
pub struct Mii0Rxd1 {}
pub struct I2c2Scl {}
pub struct I2s0Txd0 {}
pub struct Cmp2In1 {}
pub struct Pta13 {}
pub struct Can0Rx {}
pub struct Rmii0Rxd0 {}
pub struct Mii0Rxd0 {}
pub struct I2s0TxFs {}
pub struct Pta14 {}
pub struct Spi0Pcs0 {}
pub struct Rmii0CrsDv {}
pub struct Mii0Rxdv {}
pub struct I2s0RxBclk {}
pub struct I2s0Txd1 {}
pub struct Pta15 {}
pub struct Spi0Sck {}
pub struct Rmii0Txen {}
pub struct Mii0Txen {}
pub struct I2s0Rxd0 {}
pub struct Pta16 {}
pub struct Spi0Sout {}
pub struct Rmii0Txd0 {}
pub struct Mii0Txd0 {}
pub struct I2s0RxFs {}
pub struct I2s0Rxd1 {}
pub struct Adc1Se17 {}
pub struct Pta17 {}
pub struct Spi0Sin {}
pub struct Rmii0Txd1 {}
pub struct Mii0Txd1 {}
pub struct I2s0Mclk {}
pub struct Extal0 {}
pub struct Pta18 {}
pub struct Ftm0Flt2 {}
pub struct FtmClkin0 {}
pub struct Xtal0 {}
pub struct Pta19 {}
pub struct Ftm1Flt0 {}
pub struct FtmClkin1 {}
pub struct Lptmr0Alt1 {}
pub struct Pta24 {}
pub struct Mii0Txd2 {}
pub struct FbA29 {}
pub struct Pta25 {}
pub struct Mii0Txclk {}
pub struct FbA28 {}
pub struct Pta26 {}
pub struct Mii0Txd3 {}
pub struct FbA27 {}
pub struct Pta27 {}
pub struct Mii0Crs {}
pub struct FbA26 {}
pub struct Pta28 {}
pub struct Mii0Txer {}
pub struct FbA25 {}
pub struct Pta29 {}
pub struct Mii0Col {}
pub struct FbA24 {}
pub struct Adc0Se8 {}
pub struct Adc1Se8 {}
pub struct Ptb0 {}
pub struct I2c0Scl {}
pub struct Rmii0Mdio {}
pub struct Mii0Mdio {}
pub struct Adc0Se9 {}
pub struct Adc1Se9 {}
pub struct Ptb1 {}
pub struct I2c0Sda {}
pub struct Rmii0Mdc {}
pub struct Mii0Mdc {}
pub struct Adc0Se12 {}
pub struct Ptb2 {}
pub struct Enet01588Tmr0 {}
pub struct Ftm0Flt3 {}
pub struct Adc0Se13 {}
pub struct Ptb3 {}
pub struct Enet01588Tmr1 {}
pub struct Ftm0Flt0 {}
pub struct Adc1Se10 {}
pub struct Ptb4 {}
pub struct Enet01588Tmr2 {}
pub struct Adc1Se11 {}
pub struct Ptb5 {}
pub struct Enet01588Tmr3 {}
pub struct Ftm2Flt0 {}
pub struct Adc1Se12 {}
pub struct Ptb6 {}
pub struct FbAd23 {}
pub struct Adc1Se13 {}
pub struct Ptb7 {}
pub struct FbAd22 {}
pub struct Ptb8 {}
pub struct Uart3RtsB {}
pub struct FbAd21 {}
pub struct Ptb9 {}
pub struct Spi1Pcs1 {}
pub struct Uart3CtsB {}
pub struct FbAd20 {}
pub struct Adc1Se14 {}
pub struct Ptb10 {}
pub struct Spi1Pcs0 {}
pub struct FbAd19 {}
pub struct Ftm0Flt1 {}
pub struct Adc1Se15 {}
pub struct Ptb11 {}
pub struct Spi1Sck {}
pub struct FbAd18 {}
pub struct Ptb12 {}
pub struct Ptb13 {}
pub struct Ptb16 {}
pub struct Spi1Sout {}
pub struct FbAd17 {}
pub struct EwmIn {}
pub struct Ptb17 {}
pub struct Spi1Sin {}
pub struct FbAd16 {}
pub struct EwmOutB {}
pub struct Ptb18 {}
pub struct FbAd15 {}
pub struct Ptb19 {}
pub struct FbOeB {}
pub struct Ptb20 {}
pub struct Spi2Pcs0 {}
pub struct FbAd31 {}
pub struct Cmp0Out {}
pub struct Ptb21 {}
pub struct Spi2Sck {}
pub struct FbAd30 {}
pub struct Cmp1Out {}
pub struct Ptb22 {}
pub struct Spi2Sout {}
pub struct FbAd29 {}
pub struct Ptb23 {}
pub struct Spi2Sin {}
pub struct Spi0Pcs5 {}
pub struct FbAd28 {}
pub struct Adc0Se14 {}
pub struct Ptc0 {}
pub struct Spi0Pcs4 {}
pub struct Pdb0Extrg {}
pub struct UsbSofOut {}
pub struct FbAd14 {}
pub struct Adc0Se15 {}
pub struct Ptc1 {}
pub struct Spi0Pcs3 {}
pub struct Uart1RtsB {}
pub struct FbAd13 {}
pub struct Adc0Se4b {}
pub struct Cmp1In0 {}
pub struct Ptc2 {}
pub struct Spi0Pcs2 {}
pub struct Uart1CtsB {}
pub struct FbAd12 {}
pub struct Cmp1In1 {}
pub struct Ptc3 {}
pub struct Spi0Pcs1 {}
pub struct Ptc4 {}
pub struct FbAd11 {}
pub struct Ptc5 {}
pub struct Lptmr0Alt2 {}
pub struct FbAd10 {}
pub struct Cmp0In0 {}
pub struct Ptc6 {}
pub struct FbAd9 {}
pub struct Cmp0In1 {}
pub struct Ptc7 {}
pub struct FbAd8 {}
pub struct Adc1Se4b {}
pub struct Cmp0In2 {}
pub struct Ptc8 {}
pub struct Ftm3Ch4 {}
pub struct FbAd7 {}
pub struct Adc1Se5b {}
pub struct Cmp0In3 {}
pub struct Ptc9 {}
pub struct Ftm3Ch5 {}
pub struct FbAd6 {}
pub struct Adc1Se6b {}
pub struct Ptc10 {}
pub struct I2c1Scl {}
pub struct Ftm3Ch6 {}
pub struct FbAd5 {}
pub struct Adc1Se7b {}
pub struct Ptc11 {}
pub struct I2c1Sda {}
pub struct Ftm3Ch7 {}
pub struct FbRwB {}
pub struct Ptc12 {}
pub struct Uart4RtsB {}
pub struct FbAd27 {}
pub struct Ftm3Flt0 {}
pub struct Ptc13 {}
pub struct Uart4CtsB {}
pub struct FbAd26 {}
pub struct Ptc14 {}
pub struct FbAd25 {}
pub struct Ptc15 {}
pub struct FbAd24 {}
pub struct Ptc16 {}
pub struct FbCs5B {}
pub struct FbTsiz1 {}
pub struct FbBe2316Bls158B {}
pub struct Ptc17 {}
pub struct FbCs4B {}
pub struct FbTsiz0 {}
pub struct FbBe3124Bls70B {}
pub struct Ptc18 {}
pub struct FbTbstB {}
pub struct FbCs2B {}
pub struct FbBe158Bls2316B {}
pub struct Ptc19 {}
pub struct FbCs3B {}
pub struct FbBe70Bls3124B {}
pub struct FbTaB {}
pub struct Ptd0 {}
pub struct Uart2RtsB {}
pub struct Ftm3Ch0 {}
pub struct FbAle {}
pub struct FbCs1B {}
pub struct FbTsB {}
pub struct Adc0Se5b {}
pub struct Ptd1 {}
pub struct Uart2CtsB {}
pub struct Ftm3Ch1 {}
pub struct FbCs0B {}
pub struct Ptd2 {}
pub struct Ftm3Ch2 {}
pub struct FbAd4 {}
pub struct Ptd3 {}
pub struct Ftm3Ch3 {}
pub struct FbAd3 {}
pub struct Ptd4 {}
pub struct FbAd2 {}
pub struct Adc0Se6b {}
pub struct Ptd5 {}
pub struct FbAd1 {}
pub struct Adc0Se7b {}
pub struct Ptd6 {}
pub struct FbAd0 {}
pub struct Ptd7 {}
pub struct CmtIro {}
pub struct Ptd8 {}
pub struct FbA16 {}
pub struct Ptd9 {}
pub struct FbA17 {}
pub struct Ptd10 {}
pub struct Uart5RtsB {}
pub struct FbA18 {}
pub struct Ptd11 {}
pub struct Uart5CtsB {}
pub struct Sdhc0Clkin {}
pub struct FbA19 {}
pub struct Ptd12 {}
pub struct Sdhc0D4 {}
pub struct FbA20 {}
pub struct Ptd13 {}
pub struct Sdhc0D5 {}
pub struct FbA21 {}
pub struct Ptd14 {}
pub struct Sdhc0D6 {}
pub struct FbA22 {}
pub struct Ptd15 {}
pub struct Spi2Pcs1 {}
pub struct Sdhc0D7 {}
pub struct FbA23 {}
pub struct Adc1Se4a {}
pub struct Pte0 {}
pub struct Sdhc0D1 {}
pub struct RtcClkout {}
pub struct Adc1Se5a {}
pub struct Pte1 {}
pub struct Sdhc0D0 {}
pub struct Adc0Dp2 {}
pub struct Adc1Se6a {}
pub struct Pte2 {}
pub struct Sdhc0Dclk {}
pub struct Adc0Dm2 {}
pub struct Adc1Se7a {}
pub struct Pte3 {}
pub struct Sdhc0Cmd {}
pub struct Pte4 {}
pub struct Sdhc0D3 {}
pub struct Pte5 {}
pub struct Spi1Pcs2 {}
pub struct Sdhc0D2 {}
pub struct Pte6 {}
pub struct Spi1Pcs3 {}
pub struct Pte7 {}
pub struct Pte8 {}
pub struct Pte9 {}
pub struct Pte10 {}
pub struct Pte11 {}
pub struct Pte12 {}
pub struct Adc0Se17 {}
pub struct Pte24 {}
pub struct Adc0Se18 {}
pub struct Pte25 {}
pub struct Pte26 {}
pub struct Enet1588Clkin {}
pub struct Pte27 {}
pub struct Pte28 {}
