pub use ::bobbin_common::*;
pub use ::bobbin_common::tree::*;
pub use ::hz::Hz;


// Define Global Clocks

pub const HSI_HZ: Hz = Hz::from_num(16000000);
pub const LSI_HZ: Hz = Hz::from_num(32000);

tree_defn! {
    id: TREE_DEFN: TreeDefn,
    clock: {
        OSC: Osc,
        OSC32: Osc32,
        HSI: Hsi,
        HSE: Hse,
        LSI: Lsi,
        LSE: Lse,
        PLLCLK: Pllclk,
        PLL48CLK: Pll48clk,
        SYSCLK: Sysclk,
        I2S: I2s,
        OTG_HS_SCL: OtgHsScl,
        HCLK: Hclk,
        SYSTICK: Systick,
        FCLK: Fclk,
        PCLK1: Pclk1,
        PCLK2: Pclk2,
        TIM_PCLK1: TimPclk1,
        TIM_PCLK2: TimPclk2,
        RTC: Rtc,
        SDMMC: Sdmmc,
        HDMI_CEC: HdmiCec,
        SPDIF: Spdif,
        SAI1: Sai1,
        SAI2: Sai2,
        ETH_MACTX: EthMactx,
        ETH_MACRX: EthMacrx,
        ETH_MACRMII: EthMacrmii,
        USART1: Usart1,
        USART2: Usart2,
        USART3: Usart3,
        UART4: Uart4,
        UART5: Uart5,
        USART6: Usart6,
        UART7: Uart7,
        UART8: Uart8,
        I2C1: I2c1,
        I2C2: I2c2,
        I2C3: I2c3,
        I2C4: I2c4,
    },
    type: {
        ::syscfg::Syscfg: Pclk2,
        ::ethernet_mac::EthernetMac: Hclk,
        ::ethernet_ptp::EthernetPtp: Hclk,
        ::hash::Hash: Hclk,
        ::cryp::Cryp: Hclk,
        ::dcmi::Dcmi: Hclk,
        ::usb_fs_host::UsbFsHost: Pll48clk,
        ::usb_fs_device::UsbFsDevice: Pll48clk,
        ::iwdg::Iwdg: Lsi,
        ::wwdg::Wwdg: Pclk1,
        ::crc::Crc: Hclk,
        ::tim_bas::Tim6: TimPclk1,
        ::tim_bas::Tim7: TimPclk1,
        ::tim_gen::Tim2: TimPclk1,
        ::tim_gen::Tim3: TimPclk1,
        ::tim_gen::Tim4: TimPclk1,
        ::tim_gen::Tim5: TimPclk1,
        ::tim_gen::Tim9: TimPclk2,
        ::tim_gen::Tim10: TimPclk2,
        ::tim_gen::Tim11: TimPclk2,
        ::tim_gen::Tim12: TimPclk1,
        ::tim_gen::Tim13: TimPclk1,
        ::tim_gen::Tim14: TimPclk1,
        ::tim_adv::Tim1: TimPclk2,
        ::tim_adv::Tim8: TimPclk2,
        ::lptim::Lptim1: TimPclk1,
        ::adc::Adc1: Pclk2,
        ::adc::Adc2: Pclk2,
        ::adc::Adc3: Pclk2,
        ::spi::Spi1: Pclk2,
        ::spi::Spi2: Pclk1,
        ::spi::Spi3: Pclk1,
        ::spi::Spi4: Pclk2,
        ::spi::Spi5: Pclk2,
        ::spi::Spi6: Pclk2,
        ::i2c::I2c1: Pclk1,
        ::i2c::I2c2: Pclk1,
        ::i2c::I2c3: Pclk1,
        ::i2c::I2c4: Pclk1,
        ::can::Can1: Pclk1,
        ::gpio::Gpioa: Hclk,
        ::gpio::Gpiob: Hclk,
        ::gpio::Gpioc: Hclk,
        ::gpio::Gpiod: Hclk,
        ::gpio::Gpioe: Hclk,
        ::gpio::Gpiof: Hclk,
        ::gpio::Gpiog: Hclk,
        ::gpio::Gpioh: Hclk,
        ::gpio::Gpioi: Hclk,
        ::gpio::Gpioj: Hclk,
        ::gpio::Gpiok: Hclk,
        ::usart::Usart1: Usart1,
        ::usart::Usart2: Usart2,
        ::usart::Usart3: Usart3,
        ::usart::Uart4: Uart4,
        ::usart::Uart5: Uart5,
        ::usart::Usart6: Usart6,
        ::usart::Uart7: Uart7,
        ::usart::Uart8: Uart8,
        ::dma::Dma1: Hclk,
        ::dma::Dma2: Hclk,
    },
}
