#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;

pub use super::gpio::*;

pin!(PA0, Pa0, pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, PA0_OWNED, PA0_REF_COUNT, 0);
   pin_source!(Pa0, super::adc::Adc1Ch1, super::sig::SigAdc, 0);
   pin_source!(Pa0, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa0, super::usart::Usart2, super::sig::SigCts, 7);
pin!(PA1, Pa1, pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, PA1_OWNED, PA1_REF_COUNT, 1);
   pin_source!(Pa1, super::adc::Adc1Ch2, super::sig::SigAdc, 0);
   pin_source!(Pa1, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pa1, super::usart::Usart2, super::sig::SigRts, 7);
pin!(PA2, Pa2, pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, PA2_OWNED, PA2_REF_COUNT, 2);
   pin_source!(Pa2, super::adc::Adc1Ch3, super::sig::SigAdc, 0);
   pin_source!(Pa2, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pa2, super::usart::Usart2, super::sig::SigTx, 7);
   pin_source!(Pa2, super::tim_gen::Tim15Ch1, super::sig::SigTim, 9);
pin!(PA3, Pa3, pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, PA3_OWNED, PA3_REF_COUNT, 3);
   pin_source!(Pa3, super::adc::Adc1Ch4, super::sig::SigAdc, 0);
   pin_source!(Pa3, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pa3, super::usart::Usart2, super::sig::SigRx, 7);
   pin_source!(Pa3, super::tim_gen::Tim15Ch2, super::sig::SigTim, 9);
pin!(PA4, Pa4, pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, PA4_OWNED, PA4_REF_COUNT, 4);
   pin_source!(Pa4, super::adc::Adc2Ch1, super::sig::SigAdc, 0);
   pin_source!(Pa4, super::dac::DacCh1, super::sig::SigDac, 0);
   pin_source!(Pa4, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pa4, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pa4, super::spi::Spi3, super::sig::SigSpiNss, 6);
   pin_source!(Pa4, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PA5, Pa5, pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, PA5_OWNED, PA5_REF_COUNT, 5);
   pin_source!(Pa5, super::adc::Adc2Ch2, super::sig::SigAdc, 0);
   pin_source!(Pa5, super::dac::DacCh2, super::sig::SigDac, 0);
   pin_source!(Pa5, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa5, super::spi::Spi1, super::sig::SigSpiSck, 5);
pin!(PA6, Pa6, pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, PA6_OWNED, PA6_REF_COUNT, 6);
   pin_source!(Pa6, super::adc::Adc2Ch3, super::sig::SigAdc, 0);
   pin_source!(Pa6, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pa6, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pa6, super::spi::Spi1, super::sig::SigSpiMiso, 5);
pin!(PA7, Pa7, pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, PA7_OWNED, PA7_REF_COUNT, 7);
   pin_source!(Pa7, super::adc::Adc2Ch4, super::sig::SigAdc, 0);
   pin_source!(Pa7, super::tim_gen::Tim17Ch1, super::sig::SigTim, 1);
   pin_source!(Pa7, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pa7, super::spi::Spi1, super::sig::SigSpiMosi, 5);
pin!(PA8, Pa8, pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, PA8_OWNED, PA8_REF_COUNT, 8);
   pin_source!(Pa8, super::i2c::I2c3, super::sig::SigI2cScl, 3);
   pin_source!(Pa8, super::i2c::I2c2, super::sig::SigI2cSmbal, 4);
   pin_source!(Pa8, super::tim_adv::Tim1Ch1, super::sig::SigTim, 6);
   pin_source!(Pa8, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PA9, Pa9, pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, PA9_OWNED, PA9_REF_COUNT, 9);
   pin_source!(Pa9, super::i2c::I2c3, super::sig::SigI2cSmbal, 2);
   pin_source!(Pa9, super::i2c::I2c2, super::sig::SigI2cScl, 4);
   pin_source!(Pa9, super::tim_adv::Tim1Ch2, super::sig::SigTim, 6);
   pin_source!(Pa9, super::usart::Usart1, super::sig::SigTx, 7);
   pin_source!(Pa9, super::tim_gen::Tim2Ch3, super::sig::SigTim, 10);
pin!(PA10, Pa10, pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, PA10_OWNED, PA10_REF_COUNT, 10);
   pin_source!(Pa10, super::i2c::I2c2, super::sig::SigI2cSda, 4);
   pin_source!(Pa10, super::spi::Spi2, super::sig::SigSpiMiso, 5);
   pin_source!(Pa10, super::tim_adv::Tim1Ch3, super::sig::SigTim, 6);
   pin_source!(Pa10, super::usart::Usart1, super::sig::SigRx, 7);
   pin_source!(Pa10, super::tim_gen::Tim2Ch4, super::sig::SigTim, 10);
pin!(PA11, Pa11, pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, PA11_OWNED, PA11_REF_COUNT, 11);
   pin_source!(Pa11, super::spi::Spi2, super::sig::SigSpiMosi, 5);
   pin_source!(Pa11, super::usart::Usart1, super::sig::SigCts, 7);
   pin_source!(Pa11, super::tim_gen::Tim4Ch1, super::sig::SigTim, 10);
   pin_source!(Pa11, super::tim_adv::Tim1Ch4, super::sig::SigTim, 11);
pin!(PA12, Pa12, pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, PA12_OWNED, PA12_REF_COUNT, 12);
   pin_source!(Pa12, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pa12, super::usart::Usart1, super::sig::SigRts, 7);
   pin_source!(Pa12, super::tim_gen::Tim4Ch2, super::sig::SigTim, 10);
pin!(PA13, Pa13, pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, PA13_OWNED, PA13_REF_COUNT, 13);
   pin_source!(Pa13, super::tim_gen::Tim16Ch1, super::sig::SigTimn, 1);
   pin_source!(Pa13, super::usart::Usart3, super::sig::SigCts, 7);
   pin_source!(Pa13, super::tim_gen::Tim4Ch3, super::sig::SigTim, 10);
pin!(PA14, Pa14, pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, PA14_OWNED, PA14_REF_COUNT, 14);
   pin_source!(Pa14, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pa14, super::tim_adv::Tim8Ch2, super::sig::SigTim, 5);
   pin_source!(Pa14, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PA15, Pa15, pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, PA15_OWNED, PA15_REF_COUNT, 15);
   pin_source!(Pa15, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa15, super::tim_adv::Tim8Ch1, super::sig::SigTim, 2);
   pin_source!(Pa15, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pa15, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pa15, super::spi::Spi3, super::sig::SigSpiNss, 6);
   pin_source!(Pa15, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PB0, Pb0, pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, PB0_OWNED, PB0_REF_COUNT, 0);
   pin_source!(Pb0, super::adc::Adc2Ch12, super::sig::SigAdc, 0);
   pin_source!(Pb0, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
pin!(PB1, Pb1, pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, PB1_OWNED, PB1_REF_COUNT, 1);
   pin_source!(Pb1, super::adc::Adc3Ch1, super::sig::SigAdc, 0);
   pin_source!(Pb1, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
pin!(PB2, Pb2, pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, PB2_OWNED, PB2_REF_COUNT, 2);
   pin_source!(Pb2, super::adc::Adc2Ch12, super::sig::SigAdc, 0);
pin!(PB3, Pb3, pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, PB3_OWNED, PB3_REF_COUNT, 3);
   pin_source!(Pb3, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pb3, super::spi::Spi1, super::sig::SigSpiSck, 5);
   pin_source!(Pb3, super::spi::Spi3, super::sig::SigSpiSck, 6);
   pin_source!(Pb3, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PB4, Pb4, pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, PB4_OWNED, PB4_REF_COUNT, 4);
   pin_source!(Pb4, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pb4, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pb4, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pb4, super::spi::Spi3, super::sig::SigSpiMiso, 6);
   pin_source!(Pb4, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PB5, Pb5, pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, PB5_OWNED, PB5_REF_COUNT, 5);
   pin_source!(Pb5, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pb5, super::i2c::I2c1, super::sig::SigI2cSmbal, 4);
   pin_source!(Pb5, super::spi::Spi1, super::sig::SigSpiMosi, 5);
   pin_source!(Pb5, super::spi::Spi3, super::sig::SigSpiMosi, 6);
   pin_source!(Pb5, super::usart::Usart2, super::sig::SigCk, 7);
   pin_source!(Pb5, super::i2c::I2c3, super::sig::SigI2cSda, 8);
   pin_source!(Pb5, super::tim_gen::Tim17Ch1, super::sig::SigTim, 10);
pin!(PB6, Pb6, pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, PB6_OWNED, PB6_REF_COUNT, 6);
   pin_source!(Pb6, super::tim_gen::Tim16Ch1, super::sig::SigTimn, 1);
   pin_source!(Pb6, super::tim_gen::Tim4Ch1, super::sig::SigTim, 2);
   pin_source!(Pb6, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pb6, super::tim_adv::Tim8Ch1, super::sig::SigTim, 5);
   pin_source!(Pb6, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PB7, Pb7, pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, PB7_OWNED, PB7_REF_COUNT, 7);
   pin_source!(Pb7, super::tim_gen::Tim17Ch1, super::sig::SigTimn, 1);
   pin_source!(Pb7, super::tim_gen::Tim4Ch2, super::sig::SigTim, 2);
   pin_source!(Pb7, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pb7, super::usart::Usart1, super::sig::SigRx, 7);
   pin_source!(Pb7, super::tim_gen::Tim3Ch4, super::sig::SigTim, 10);
pin!(PB8, Pb8, pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, PB8_OWNED, PB8_REF_COUNT, 8);
   pin_source!(Pb8, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pb8, super::tim_gen::Tim4Ch3, super::sig::SigTim, 2);
   pin_source!(Pb8, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pb8, super::usart::Usart3, super::sig::SigRx, 7);
   pin_source!(Pb8, super::tim_adv::Tim8Ch2, super::sig::SigTim, 10);
pin!(PB9, Pb9, pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, PB9_OWNED, PB9_REF_COUNT, 9);
   pin_source!(Pb9, super::tim_gen::Tim17Ch1, super::sig::SigTim, 1);
   pin_source!(Pb9, super::tim_gen::Tim4Ch4, super::sig::SigTim, 2);
   pin_source!(Pb9, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pb9, super::usart::Usart3, super::sig::SigTx, 7);
   pin_source!(Pb9, super::tim_adv::Tim8Ch3, super::sig::SigTim, 10);
pin!(PB10, Pb10, pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, PB10_OWNED, PB10_REF_COUNT, 10);
   pin_source!(Pb10, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pb10, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PB11, Pb11, pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, PB11_OWNED, PB11_REF_COUNT, 11);
   pin_source!(Pb11, super::adc::Adc4Ch14, super::sig::SigAdc, 0);
   pin_source!(Pb11, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pb11, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PB12, Pb12, pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, PB12_OWNED, PB12_REF_COUNT, 12);
   pin_source!(Pb12, super::adc::Adc4Ch3, super::sig::SigAdc, 0);
   pin_source!(Pb12, super::i2c::I2c1, super::sig::SigI2cSmbal, 4);
   pin_source!(Pb12, super::spi::Spi2, super::sig::SigSpiNss, 5);
   pin_source!(Pb12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PB13, Pb13, pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, PB13_OWNED, PB13_REF_COUNT, 13);
   pin_source!(Pb13, super::adc::Adc4Ch5, super::sig::SigAdc, 0);
   pin_source!(Pb13, super::spi::Spi2, super::sig::SigSpiSck, 5);
   pin_source!(Pb13, super::usart::Usart3, super::sig::SigCts, 7);
pin!(PB14, Pb14, pb14, GPIOB, Gpiob, PB14_PIN, GpioPin, GPIOB_PERIPH, PB14_OWNED, PB14_REF_COUNT, 14);
   pin_source!(Pb14, super::adc::Adc4Ch4, super::sig::SigAdc, 0);
   pin_source!(Pb14, super::tim_gen::Tim15Ch1, super::sig::SigTim, 1);
   pin_source!(Pb14, super::spi::Spi2, super::sig::SigSpiMiso, 5);
   pin_source!(Pb14, super::usart::Usart3, super::sig::SigRts, 7);
pin!(PB15, Pb15, pb15, GPIOB, Gpiob, PB15_PIN, GpioPin, GPIOB_PERIPH, PB15_OWNED, PB15_REF_COUNT, 15);
   pin_source!(Pb15, super::adc::Adc4Ch5, super::sig::SigAdc, 0);
   pin_source!(Pb15, super::tim_gen::Tim15Ch2, super::sig::SigTim, 1);
   pin_source!(Pb15, super::spi::Spi2, super::sig::SigSpiMosi, 5);
pin!(PC0, Pc0, pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, PC0_OWNED, PC0_REF_COUNT, 0);
   pin_source!(Pc0, super::adc::Adc1Ch6, super::sig::SigAdc, 0);
   pin_source!(Pc0, super::adc::Adc2Ch6, super::sig::SigAdc, 0);
   pin_source!(Pc0, super::tim_adv::Tim1Ch1, super::sig::SigTim, 2);
pin!(PC1, Pc1, pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, PC1_OWNED, PC1_REF_COUNT, 1);
   pin_source!(Pc1, super::adc::Adc1Ch7, super::sig::SigAdc, 0);
   pin_source!(Pc1, super::adc::Adc2Ch7, super::sig::SigAdc, 0);
   pin_source!(Pc1, super::tim_adv::Tim1Ch2, super::sig::SigTim, 2);
pin!(PC2, Pc2, pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, PC2_OWNED, PC2_REF_COUNT, 2);
   pin_source!(Pc2, super::adc::Adc1Ch8, super::sig::SigAdc, 0);
   pin_source!(Pc2, super::adc::Adc2Ch8, super::sig::SigAdc, 0);
   pin_source!(Pc2, super::tim_adv::Tim1Ch3, super::sig::SigTim, 2);
pin!(PC3, Pc3, pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, PC3_OWNED, PC3_REF_COUNT, 3);
   pin_source!(Pc3, super::adc::Adc1Ch9, super::sig::SigAdc, 0);
   pin_source!(Pc3, super::adc::Adc2Ch9, super::sig::SigAdc, 0);
   pin_source!(Pc3, super::tim_adv::Tim1Ch4, super::sig::SigTim, 2);
pin!(PC4, Pc4, pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, PC4_OWNED, PC4_REF_COUNT, 4);
   pin_source!(Pc4, super::adc::Adc2Ch5, super::sig::SigAdc, 0);
   pin_source!(Pc4, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PC5, Pc5, pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, PC5_OWNED, PC5_REF_COUNT, 5);
   pin_source!(Pc5, super::adc::Adc2Ch11, super::sig::SigAdc, 0);
   pin_source!(Pc5, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PC6, Pc6, pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, PC6_OWNED, PC6_REF_COUNT, 6);
   pin_source!(Pc6, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pc6, super::tim_adv::Tim8Ch1, super::sig::SigTim, 3);
pin!(PC7, Pc7, pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, PC7_OWNED, PC7_REF_COUNT, 7);
   pin_source!(Pc7, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pc7, super::tim_adv::Tim8Ch2, super::sig::SigTim, 3);
pin!(PC8, Pc8, pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, PC8_OWNED, PC8_REF_COUNT, 8);
   pin_source!(Pc8, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
   pin_source!(Pc8, super::tim_adv::Tim8Ch3, super::sig::SigTim, 3);
pin!(PC9, Pc9, pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, PC9_OWNED, PC9_REF_COUNT, 9);
   pin_source!(Pc9, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
   pin_source!(Pc9, super::i2c::I2c3, super::sig::SigI2cSda, 3);
   pin_source!(Pc9, super::tim_adv::Tim8Ch4, super::sig::SigTim, 3);
pin!(PC10, Pc10, pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, PC10_OWNED, PC10_REF_COUNT, 10);
   pin_source!(Pc10, super::usart::Uart4, super::sig::SigTx, 5);
   pin_source!(Pc10, super::spi::Spi3, super::sig::SigSpiSck, 6);
   pin_source!(Pc10, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PC11, Pc11, pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, PC11_OWNED, PC11_REF_COUNT, 11);
   pin_source!(Pc11, super::usart::Uart4, super::sig::SigRx, 5);
   pin_source!(Pc11, super::spi::Spi3, super::sig::SigSpiMiso, 6);
   pin_source!(Pc11, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PC12, Pc12, pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, PC12_OWNED, PC12_REF_COUNT, 12);
   pin_source!(Pc12, super::usart::Uart5, super::sig::SigTx, 5);
   pin_source!(Pc12, super::spi::Spi3, super::sig::SigSpiMosi, 6);
   pin_source!(Pc12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PC13, Pc13, pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, PC13_OWNED, PC13_REF_COUNT, 13);
pin!(PC14, Pc14, pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, PC14_OWNED, PC14_REF_COUNT, 14);
pin!(PC15, Pc15, pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, PC15_OWNED, PC15_REF_COUNT, 15);
pin!(PD0, Pd0, pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, PD0_OWNED, PD0_REF_COUNT, 0);
pin!(PD1, Pd1, pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, PD1_OWNED, PD1_REF_COUNT, 1);
   pin_source!(Pd1, super::tim_adv::Tim8Ch4, super::sig::SigTim, 3);
pin!(PD2, Pd2, pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, PD2_OWNED, PD2_REF_COUNT, 2);
   pin_source!(Pd2, super::usart::Uart5, super::sig::SigRx, 5);
pin!(PD3, Pd3, pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, PD3_OWNED, PD3_REF_COUNT, 3);
   pin_source!(Pd3, super::tim_gen::Tim2Ch1, super::sig::SigTim, 2);
   pin_source!(Pd3, super::usart::Usart2, super::sig::SigCts, 7);
pin!(PD4, Pd4, pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, PD4_OWNED, PD4_REF_COUNT, 4);
   pin_source!(Pd4, super::tim_gen::Tim2Ch2, super::sig::SigTim, 2);
   pin_source!(Pd4, super::usart::Usart2, super::sig::SigRts, 7);
pin!(PD5, Pd5, pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, PD5_OWNED, PD5_REF_COUNT, 5);
   pin_source!(Pd5, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PD6, Pd6, pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, PD6_OWNED, PD6_REF_COUNT, 6);
   pin_source!(Pd6, super::tim_gen::Tim2Ch4, super::sig::SigTim, 2);
   pin_source!(Pd6, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PD7, Pd7, pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, PD7_OWNED, PD7_REF_COUNT, 7);
   pin_source!(Pd7, super::tim_gen::Tim2Ch3, super::sig::SigTim, 2);
   pin_source!(Pd7, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PD8, Pd8, pd8, GPIOD, Gpiod, PD8_PIN, GpioPin, GPIOD_PERIPH, PD8_OWNED, PD8_REF_COUNT, 8);
   pin_source!(Pd8, super::adc::Adc4Ch12, super::sig::SigAdc, 0);
   pin_source!(Pd8, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PD9, Pd9, pd9, GPIOD, Gpiod, PD9_PIN, GpioPin, GPIOD_PERIPH, PD9_OWNED, PD9_REF_COUNT, 9);
   pin_source!(Pd9, super::adc::Adc4Ch13, super::sig::SigAdc, 0);
   pin_source!(Pd9, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PD10, Pd10, pd10, GPIOD, Gpiod, PD10_PIN, GpioPin, GPIOD_PERIPH, PD10_OWNED, PD10_REF_COUNT, 10);
   pin_source!(Pd10, super::adc::Adc3Ch7, super::sig::SigAdc, 0);
   pin_source!(Pd10, super::adc::Adc4Ch7, super::sig::SigAdc, 0);
   pin_source!(Pd10, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PD11, Pd11, pd11, GPIOD, Gpiod, PD11_PIN, GpioPin, GPIOD_PERIPH, PD11_OWNED, PD11_REF_COUNT, 11);
   pin_source!(Pd11, super::adc::Adc3Ch8, super::sig::SigAdc, 0);
   pin_source!(Pd11, super::adc::Adc4Ch8, super::sig::SigAdc, 0);
   pin_source!(Pd11, super::usart::Usart3, super::sig::SigCts, 7);
pin!(PD12, Pd12, pd12, GPIOD, Gpiod, PD12_PIN, GpioPin, GPIOD_PERIPH, PD12_OWNED, PD12_REF_COUNT, 12);
   pin_source!(Pd12, super::adc::Adc3Ch9, super::sig::SigAdc, 0);
   pin_source!(Pd12, super::adc::Adc4Ch9, super::sig::SigAdc, 0);
   pin_source!(Pd12, super::tim_gen::Tim4Ch1, super::sig::SigTim, 2);
   pin_source!(Pd12, super::usart::Usart3, super::sig::SigRts, 7);
pin!(PD13, Pd13, pd13, GPIOD, Gpiod, PD13_PIN, GpioPin, GPIOD_PERIPH, PD13_OWNED, PD13_REF_COUNT, 13);
   pin_source!(Pd13, super::adc::Adc3Ch10, super::sig::SigAdc, 0);
   pin_source!(Pd13, super::adc::Adc4Ch10, super::sig::SigAdc, 0);
   pin_source!(Pd13, super::tim_gen::Tim4Ch2, super::sig::SigTim, 2);
pin!(PD14, Pd14, pd14, GPIOD, Gpiod, PD14_PIN, GpioPin, GPIOD_PERIPH, PD14_OWNED, PD14_REF_COUNT, 14);
   pin_source!(Pd14, super::adc::Adc3Ch11, super::sig::SigAdc, 0);
   pin_source!(Pd14, super::adc::Adc4Ch11, super::sig::SigAdc, 0);
   pin_source!(Pd14, super::tim_gen::Tim4Ch3, super::sig::SigTim, 2);
pin!(PD15, Pd15, pd15, GPIOD, Gpiod, PD15_PIN, GpioPin, GPIOD_PERIPH, PD15_OWNED, PD15_REF_COUNT, 15);
   pin_source!(Pd15, super::tim_gen::Tim4Ch4, super::sig::SigTim, 2);
   pin_source!(Pd15, super::spi::Spi2, super::sig::SigSpiNss, 6);
pin!(PE0, Pe0, pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, PE0_OWNED, PE0_REF_COUNT, 0);
   pin_source!(Pe0, super::tim_gen::Tim16Ch1, super::sig::SigTim, 4);
   pin_source!(Pe0, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PE1, Pe1, pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, PE1_OWNED, PE1_REF_COUNT, 1);
   pin_source!(Pe1, super::tim_gen::Tim17Ch1, super::sig::SigTim, 4);
   pin_source!(Pe1, super::tim_adv::Tim20Ch4, super::sig::SigTim, 6);
   pin_source!(Pe1, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PE2, Pe2, pe2, GPIOE, Gpioe, PE2_PIN, GpioPin, GPIOE_PERIPH, PE2_OWNED, PE2_REF_COUNT, 2);
   pin_source!(Pe2, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pe2, super::tim_adv::Tim20Ch1, super::sig::SigTim, 6);
pin!(PE3, Pe3, pe3, GPIOE, Gpioe, PE3_PIN, GpioPin, GPIOE_PERIPH, PE3_OWNED, PE3_REF_COUNT, 3);
   pin_source!(Pe3, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pe3, super::tim_adv::Tim20Ch2, super::sig::SigTim, 6);
pin!(PE4, Pe4, pe4, GPIOE, Gpioe, PE4_PIN, GpioPin, GPIOE_PERIPH, PE4_OWNED, PE4_REF_COUNT, 4);
   pin_source!(Pe4, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
pin!(PE5, Pe5, pe5, GPIOE, Gpioe, PE5_PIN, GpioPin, GPIOE_PERIPH, PE5_OWNED, PE5_REF_COUNT, 5);
   pin_source!(Pe5, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
pin!(PE6, Pe6, pe6, GPIOE, Gpioe, PE6_PIN, GpioPin, GPIOE_PERIPH, PE6_OWNED, PE6_REF_COUNT, 6);
pin!(PE7, Pe7, pe7, GPIOE, Gpioe, PE7_PIN, GpioPin, GPIOE_PERIPH, PE7_OWNED, PE7_REF_COUNT, 7);
   pin_source!(Pe7, super::adc::Adc3Ch13, super::sig::SigAdc, 0);
pin!(PE8, Pe8, pe8, GPIOE, Gpioe, PE8_PIN, GpioPin, GPIOE_PERIPH, PE8_OWNED, PE8_REF_COUNT, 8);
   pin_source!(Pe8, super::adc::Adc3Ch6, super::sig::SigAdc, 0);
   pin_source!(Pe8, super::adc::Adc4Ch6, super::sig::SigAdc, 0);
pin!(PE9, Pe9, pe9, GPIOE, Gpioe, PE9_PIN, GpioPin, GPIOE_PERIPH, PE9_OWNED, PE9_REF_COUNT, 9);
   pin_source!(Pe9, super::adc::Adc3Ch2, super::sig::SigAdc, 0);
   pin_source!(Pe9, super::tim_adv::Tim1Ch1, super::sig::SigTim, 2);
pin!(PE10, Pe10, pe10, GPIOE, Gpioe, PE10_PIN, GpioPin, GPIOE_PERIPH, PE10_OWNED, PE10_REF_COUNT, 10);
   pin_source!(Pe10, super::adc::Adc3Ch14, super::sig::SigAdc, 0);
pin!(PE11, Pe11, pe11, GPIOE, Gpioe, PE11_PIN, GpioPin, GPIOE_PERIPH, PE11_OWNED, PE11_REF_COUNT, 11);
   pin_source!(Pe11, super::adc::Adc3Ch15, super::sig::SigAdc, 0);
   pin_source!(Pe11, super::tim_adv::Tim1Ch2, super::sig::SigTim, 2);
pin!(PE12, Pe12, pe12, GPIOE, Gpioe, PE12_PIN, GpioPin, GPIOE_PERIPH, PE12_OWNED, PE12_REF_COUNT, 12);
pin!(PE13, Pe13, pe13, GPIOE, Gpioe, PE13_PIN, GpioPin, GPIOE_PERIPH, PE13_OWNED, PE13_REF_COUNT, 13);
   pin_source!(Pe13, super::adc::Adc3Ch3, super::sig::SigAdc, 0);
   pin_source!(Pe13, super::tim_adv::Tim1Ch3, super::sig::SigTim, 2);
pin!(PE14, Pe14, pe14, GPIOE, Gpioe, PE14_PIN, GpioPin, GPIOE_PERIPH, PE14_OWNED, PE14_REF_COUNT, 14);
   pin_source!(Pe14, super::adc::Adc4Ch1, super::sig::SigAdc, 0);
   pin_source!(Pe14, super::tim_adv::Tim1Ch4, super::sig::SigTim, 2);
pin!(PE15, Pe15, pe15, GPIOE, Gpioe, PE15_PIN, GpioPin, GPIOE_PERIPH, PE15_OWNED, PE15_REF_COUNT, 15);
   pin_source!(Pe15, super::adc::Adc4Ch2, super::sig::SigAdc, 0);
   pin_source!(Pe15, super::usart::Usart3, super::sig::SigRx, 6);
pin!(PF0, Pf0, pf0, GPIOF, Gpiof, PF0_PIN, GpioPin, GPIOF_PERIPH, PF0_OWNED, PF0_REF_COUNT, 0);
   pin_source!(Pf0, super::i2c::I2c2, super::sig::SigI2cSda, 4);
   pin_source!(Pf0, super::spi::Spi2, super::sig::SigSpiNss, 5);
pin!(PF1, Pf1, pf1, GPIOF, Gpiof, PF1_PIN, GpioPin, GPIOF_PERIPH, PF1_OWNED, PF1_REF_COUNT, 1);
   pin_source!(Pf1, super::i2c::I2c2, super::sig::SigI2cScl, 4);
   pin_source!(Pf1, super::spi::Spi2, super::sig::SigSpiSck, 5);
pin!(PF2, Pf2, pf2, GPIOF, Gpiof, PF2_PIN, GpioPin, GPIOF_PERIPH, PF2_OWNED, PF2_REF_COUNT, 2);
   pin_source!(Pf2, super::adc::Adc1Ch10, super::sig::SigAdc, 0);
   pin_source!(Pf2, super::adc::Adc2Ch10, super::sig::SigAdc, 0);
   pin_source!(Pf2, super::tim_adv::Tim20Ch3, super::sig::SigTim, 2);
pin!(PF3, Pf3, pf3, GPIOF, Gpiof, PF3_PIN, GpioPin, GPIOF_PERIPH, PF3_OWNED, PF3_REF_COUNT, 3);
   pin_source!(Pf3, super::tim_adv::Tim20Ch4, super::sig::SigTim, 2);
pin!(PF4, Pf4, pf4, GPIOF, Gpiof, PF4_PIN, GpioPin, GPIOF_PERIPH, PF4_OWNED, PF4_REF_COUNT, 4);
   pin_source!(Pf4, super::adc::Adc1Ch5, super::sig::SigAdc, 0);
pin!(PF5, Pf5, pf5, GPIOF, Gpiof, PF5_PIN, GpioPin, GPIOF_PERIPH, PF5_OWNED, PF5_REF_COUNT, 5);
pin!(PF6, Pf6, pf6, GPIOF, Gpiof, PF6_PIN, GpioPin, GPIOF_PERIPH, PF6_OWNED, PF6_REF_COUNT, 6);
   pin_source!(Pf6, super::tim_gen::Tim4Ch4, super::sig::SigTim, 2);
   pin_source!(Pf6, super::i2c::I2c2, super::sig::SigI2cScl, 4);
   pin_source!(Pf6, super::usart::Usart3, super::sig::SigRts, 6);
pin!(PF7, Pf7, pf7, GPIOF, Gpiof, PF7_PIN, GpioPin, GPIOF_PERIPH, PF7_OWNED, PF7_REF_COUNT, 7);
pin!(PF8, Pf8, pf8, GPIOF, Gpiof, PF8_PIN, GpioPin, GPIOF_PERIPH, PF8_OWNED, PF8_REF_COUNT, 8);
pin!(PF9, Pf9, pf9, GPIOF, Gpiof, PF9_PIN, GpioPin, GPIOF_PERIPH, PF9_OWNED, PF9_REF_COUNT, 9);
   pin_source!(Pf9, super::tim_gen::Tim15Ch1, super::sig::SigTim, 3);
   pin_source!(Pf9, super::spi::Spi2, super::sig::SigSpiSck, 5);
pin!(PF10, Pf10, pf10, GPIOF, Gpiof, PF10_PIN, GpioPin, GPIOF_PERIPH, PF10_OWNED, PF10_REF_COUNT, 10);
   pin_source!(Pf10, super::tim_gen::Tim15Ch2, super::sig::SigTim, 3);
   pin_source!(Pf10, super::spi::Spi2, super::sig::SigSpiSck, 5);
pin!(PF11, Pf11, pf11, GPIOF, Gpiof, PF11_PIN, GpioPin, GPIOF_PERIPH, PF11_OWNED, PF11_REF_COUNT, 11);
pin!(PF12, Pf12, pf12, GPIOF, Gpiof, PF12_PIN, GpioPin, GPIOF_PERIPH, PF12_OWNED, PF12_REF_COUNT, 12);
   pin_source!(Pf12, super::tim_adv::Tim20Ch1, super::sig::SigTim, 2);
pin!(PF13, Pf13, pf13, GPIOF, Gpiof, PF13_PIN, GpioPin, GPIOF_PERIPH, PF13_OWNED, PF13_REF_COUNT, 13);
   pin_source!(Pf13, super::tim_adv::Tim20Ch2, super::sig::SigTim, 2);
pin!(PF14, Pf14, pf14, GPIOF, Gpiof, PF14_PIN, GpioPin, GPIOF_PERIPH, PF14_OWNED, PF14_REF_COUNT, 14);
   pin_source!(Pf14, super::tim_adv::Tim20Ch3, super::sig::SigTim, 2);
pin!(PF15, Pf15, pf15, GPIOF, Gpiof, PF15_PIN, GpioPin, GPIOF_PERIPH, PF15_OWNED, PF15_REF_COUNT, 15);
   pin_source!(Pf15, super::tim_adv::Tim20Ch4, super::sig::SigTim, 2);
pin!(PG0, Pg0, pg0, GPIOG, Gpiog, PG0_PIN, GpioPin, GPIOG_PERIPH, PG0_OWNED, PG0_REF_COUNT, 0);
pin!(PG1, Pg1, pg1, GPIOG, Gpiog, PG1_PIN, GpioPin, GPIOG_PERIPH, PG1_OWNED, PG1_REF_COUNT, 1);
pin!(PG2, Pg2, pg2, GPIOG, Gpiog, PG2_PIN, GpioPin, GPIOG_PERIPH, PG2_OWNED, PG2_REF_COUNT, 2);
pin!(PG3, Pg3, pg3, GPIOG, Gpiog, PG3_PIN, GpioPin, GPIOG_PERIPH, PG3_OWNED, PG3_REF_COUNT, 3);
pin!(PG4, Pg4, pg4, GPIOG, Gpiog, PG4_PIN, GpioPin, GPIOG_PERIPH, PG4_OWNED, PG4_REF_COUNT, 4);
pin!(PG5, Pg5, pg5, GPIOG, Gpiog, PG5_PIN, GpioPin, GPIOG_PERIPH, PG5_OWNED, PG5_REF_COUNT, 5);
pin!(PG6, Pg6, pg6, GPIOG, Gpiog, PG6_PIN, GpioPin, GPIOG_PERIPH, PG6_OWNED, PG6_REF_COUNT, 6);
pin!(PG7, Pg7, pg7, GPIOG, Gpiog, PG7_PIN, GpioPin, GPIOG_PERIPH, PG7_OWNED, PG7_REF_COUNT, 7);
pin!(PG8, Pg8, pg8, GPIOG, Gpiog, PG8_PIN, GpioPin, GPIOG_PERIPH, PG8_OWNED, PG8_REF_COUNT, 8);
pin!(PG9, Pg9, pg9, GPIOG, Gpiog, PG9_PIN, GpioPin, GPIOG_PERIPH, PG9_OWNED, PG9_REF_COUNT, 9);
pin!(PG10, Pg10, pg10, GPIOG, Gpiog, PG10_PIN, GpioPin, GPIOG_PERIPH, PG10_OWNED, PG10_REF_COUNT, 10);
pin!(PG11, Pg11, pg11, GPIOG, Gpiog, PG11_PIN, GpioPin, GPIOG_PERIPH, PG11_OWNED, PG11_REF_COUNT, 11);
pin!(PG12, Pg12, pg12, GPIOG, Gpiog, PG12_PIN, GpioPin, GPIOG_PERIPH, PG12_OWNED, PG12_REF_COUNT, 12);
pin!(PG13, Pg13, pg13, GPIOG, Gpiog, PG13_PIN, GpioPin, GPIOG_PERIPH, PG13_OWNED, PG13_REF_COUNT, 13);
pin!(PG14, Pg14, pg14, GPIOG, Gpiog, PG14_PIN, GpioPin, GPIOG_PERIPH, PG14_OWNED, PG14_REF_COUNT, 14);
pin!(PG15, Pg15, pg15, GPIOG, Gpiog, PG15_PIN, GpioPin, GPIOG_PERIPH, PG15_OWNED, PG15_REF_COUNT, 15);
pin!(PH0, Ph0, ph0, GPIOH, Gpioh, PH0_PIN, GpioPin, GPIOH_PERIPH, PH0_OWNED, PH0_REF_COUNT, 0);
   pin_source!(Ph0, super::tim_adv::Tim20Ch1, super::sig::SigTim, 2);
pin!(PH1, Ph1, ph1, GPIOH, Gpioh, PH1_PIN, GpioPin, GPIOH_PERIPH, PH1_OWNED, PH1_REF_COUNT, 1);
   pin_source!(Ph1, super::tim_adv::Tim20Ch2, super::sig::SigTim, 2);
pin!(PH2, Ph2, ph2, GPIOH, Gpioh, PH2_PIN, GpioPin, GPIOH_PERIPH, PH2_OWNED, PH2_REF_COUNT, 2);
