[package]
name = "stm32f74x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
no-heap = [ "stm32-common/no-heap" ]
default = []

STM32F72xxC = []
STM32F72xxE = []
STM32F74xxE = []
STM32F74xxG = []
STM32F76xxG = []
STM32F76xxI = []
