//! Signals

pub trait Signal<T> {}

pub trait Tim {}
pub trait SignalTim<T> {}
pub trait Adc {}
pub trait SignalAdc<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Cts {}
pub trait SignalCts<T> {}
pub trait Rts {}
pub trait SignalRts<T> {}
pub trait Ck {}
pub trait SignalCk<T> {}

pub struct Tim2Ch1 {}
pub struct Tim2Ch2 {}
pub struct Tim2Ch3 {}
pub struct Tim2Ch4 {}
pub struct Tim3Ch1 {}
pub struct Tim3Ch2 {}
pub struct Tim3Ch3 {}
pub struct Tim3Ch4 {}
pub struct Tim4Ch1 {}
pub struct Tim4Ch2 {}
pub struct Tim4Ch3 {}
pub struct Tim4Ch4 {}
pub struct Tim5Ch1 {}
pub struct Tim5Ch2 {}
pub struct Tim5Ch3 {}
pub struct Tim5Ch4 {}
pub struct Tim9Ch1 {}
pub struct Tim9Ch2 {}
pub struct Tim10Ch1 {}
pub struct Tim11Ch1 {}
pub struct Tim12Ch1 {}
pub struct Tim12Ch2 {}
pub struct Tim13Ch1 {}
pub struct Tim14Ch1 {}
pub struct Tim1Ch1 {}
pub struct Tim1Ch2 {}
pub struct Tim1Ch3 {}
pub struct Tim1Ch4 {}
pub struct Tim8Ch1 {}
pub struct Tim8Ch2 {}
pub struct Tim8Ch3 {}
pub struct Tim8Ch4 {}
pub struct Adc1In0 {}
pub struct Adc1In1 {}
pub struct Adc1In2 {}
pub struct Adc1In3 {}
pub struct Adc1In4 {}
pub struct Adc1In5 {}
pub struct Adc1In6 {}
pub struct Adc1In7 {}
pub struct Adc1In8 {}
pub struct Adc1In9 {}
pub struct Adc1In10 {}
pub struct Adc1In11 {}
pub struct Adc1In12 {}
pub struct Adc1In13 {}
pub struct Adc1In14 {}
pub struct Adc1In15 {}
pub struct Adc2In0 {}
pub struct Adc2In1 {}
pub struct Adc2In2 {}
pub struct Adc2In3 {}
pub struct Adc2In4 {}
pub struct Adc2In5 {}
pub struct Adc2In6 {}
pub struct Adc2In7 {}
pub struct Adc2In8 {}
pub struct Adc2In9 {}
pub struct Adc2In10 {}
pub struct Adc2In11 {}
pub struct Adc2In12 {}
pub struct Adc2In13 {}
pub struct Adc2In14 {}
pub struct Adc2In15 {}
pub struct Adc3In0 {}
pub struct Adc3In1 {}
pub struct Adc3In2 {}
pub struct Adc3In3 {}
pub struct Adc3In4 {}
pub struct Adc3In5 {}
pub struct Adc3In6 {}
pub struct Adc3In7 {}
pub struct Adc3In8 {}
pub struct Adc3In9 {}
pub struct Adc3In10 {}
pub struct Adc3In11 {}
pub struct Adc3In12 {}
pub struct Adc3In13 {}
pub struct Adc3In14 {}
pub struct Adc3In15 {}
pub struct Usart1Tx {}
pub struct Usart1Rx {}
pub struct Usart1Cts {}
pub struct Usart1Rts {}
pub struct Usart1Ck {}
pub struct Usart2Tx {}
pub struct Usart2Rx {}
pub struct Usart2Cts {}
pub struct Usart2Rts {}
pub struct Usart2Ck {}
pub struct Usart3Tx {}
pub struct Usart3Rx {}
pub struct Usart3Cts {}
pub struct Usart3Rts {}
pub struct Usart3Ck {}
pub struct Uart4Tx {}
pub struct Uart4Rx {}
pub struct Uart4Cts {}
pub struct Uart4Rts {}
pub struct Uart4Ck {}
pub struct Uart5Tx {}
pub struct Uart5Rx {}
pub struct Uart5Cts {}
pub struct Uart5Rts {}
pub struct Uart5Ck {}
pub struct Usart6Tx {}
pub struct Usart6Rx {}
pub struct Usart6Cts {}
pub struct Usart6Rts {}
pub struct Usart6Ck {}
pub struct Tim2Etr {}
pub struct Tim8Etr {}
pub struct EthMiiCrs {}
pub struct Eventout {}
pub struct EthMiiRxClk {}
pub struct EthRmiiRefClk {}
pub struct EthMdio {}
pub struct OtgHsUlpiD0 {}
pub struct EthMiiCol {}
pub struct Spi1Nss {}
pub struct Spi3Nss {}
pub struct I2s3Ws {}
pub struct OtgHsSof {}
pub struct DcmiHsync {}
pub struct Tim8Ch1n {}
pub struct Spi1Sck {}
pub struct OtgHsUlpiCk {}
pub struct Tim1Bkin {}
pub struct Tim8Bkin {}
pub struct Spi1Miso {}
pub struct DcmiPxclk {}
pub struct Tim1Ch1n {}
pub struct Spi1Mosi {}
pub struct EthMiiRxDv {}
pub struct EthRmiiCrsDv {}
pub struct Mco1 {}
pub struct I2c3Scl {}
pub struct OtgFsSof {}
pub struct I2c3Smba {}
pub struct DcmiD0 {}
pub struct OtgFsId {}
pub struct DcmiD1 {}
pub struct Can1Rx {}
pub struct OtgFsDm {}
pub struct Tim1Etr {}
pub struct Can1Tx {}
pub struct OtgFsDp {}
pub struct Jtms {}
pub struct Swdio {}
pub struct Jtck {}
pub struct Swclk {}
pub struct Jtdi {}
pub struct Tim1Ch2n {}
pub struct Tim8Ch2n {}
pub struct OtgHsUlpiD1 {}
pub struct EthMiiRxd2 {}
pub struct Tim1Ch3n {}
pub struct Tim8Ch3n {}
pub struct OtgHsUlpiD2 {}
pub struct EthMiiRxd3 {}
pub struct Jtdo {}
pub struct Traceswo {}
pub struct Spi3Sck {}
pub struct I2s3Ck {}
pub struct Njtrst {}
pub struct Spi3Miso {}
pub struct I2s3extSd {}
pub struct I2c1Smba {}
pub struct Spi3Mosi {}
pub struct I2s3Sd {}
pub struct Can2Rx {}
pub struct OtgHsUlpiD7 {}
pub struct EthPpsOut {}
pub struct DcmiD10 {}
pub struct I2c1Scl {}
pub struct Can2Tx {}
pub struct DcmiD5 {}
pub struct I2c1Sda {}
pub struct FsmcNl {}
pub struct DcmiVsync {}
pub struct EthMiiTxd3 {}
pub struct SdioD4 {}
pub struct DcmiD6 {}
pub struct Spi2Nss {}
pub struct I2s2Ws {}
pub struct SdioD5 {}
pub struct DcmiD7 {}
pub struct I2c2Scl {}
pub struct Spi2Sck {}
pub struct I2s2Ck {}
pub struct OtgHsUlpiD3 {}
pub struct EthMiiRxEr {}
pub struct I2c2Sda {}
pub struct OtgHsUlpiD4 {}
pub struct EthMiiTxEn {}
pub struct EthRmiiTxEn {}
pub struct I2c2Smba {}
pub struct OtgHsUlpiD5 {}
pub struct EthMiiTxd0 {}
pub struct EthRmiiTxd0 {}
pub struct OtgHsId {}
pub struct OtgHsUlpiD6 {}
pub struct EthMiiTxd1 {}
pub struct EthRmiiTxd1 {}
pub struct Spi2Miso {}
pub struct I2s2extSd {}
pub struct OtgHsDm {}
pub struct RtcRefin {}
pub struct Spi2Mosi {}
pub struct I2s2Sd {}
pub struct OtgHsDp {}
pub struct OtgHsUlpiStp {}
pub struct EthMdc {}
pub struct OtgHsUlpiDir {}
pub struct EthMiiTxd2 {}
pub struct OtgHsUlpiNxt {}
pub struct EthMiiTxClk {}
pub struct EthMiiRxd0 {}
pub struct EthRmiiRxd0 {}
pub struct EthMiiRxd1 {}
pub struct EthRmiiRxd1 {}
pub struct I2s2Mck {}
pub struct SdioD6 {}
pub struct I2s3Mck {}
pub struct SdioD7 {}
pub struct SdioD0 {}
pub struct DcmiD2 {}
pub struct Mco2 {}
pub struct I2c3Sda {}
pub struct I2sCkin {}
pub struct SdioD1 {}
pub struct DcmiD3 {}
pub struct SdioD2 {}
pub struct DcmiD8 {}
pub struct SdioD3 {}
pub struct DcmiD4 {}
pub struct SdioCk {}
pub struct DcmiD9 {}
pub struct FsmcD2 {}
pub struct FsmcD3 {}
pub struct Tim3Etr {}
pub struct SdioCmd {}
pub struct DcmiD11 {}
pub struct FsmcClk {}
pub struct FsmcNoe {}
pub struct FsmcNwe {}
pub struct FsmcNwait {}
pub struct FsmcNe1 {}
pub struct FsmcNce2 {}
pub struct FsmcD13 {}
pub struct FsmcD14 {}
pub struct FsmcD15 {}
pub struct FsmcA16 {}
pub struct FsmcA17 {}
pub struct FsmcA18 {}
pub struct FsmcD0 {}
pub struct FsmcD1 {}
pub struct Tim4Etr {}
pub struct FsmcNbl0 {}
pub struct FsmcNbl1 {}
pub struct Traceclk {}
pub struct FsmcA23 {}
pub struct Traced0 {}
pub struct FsmcA19 {}
pub struct Traced1 {}
pub struct FsmcA20 {}
pub struct Traced2 {}
pub struct FsmcA21 {}
pub struct Traced3 {}
pub struct FsmcA22 {}
pub struct FsmcD4 {}
pub struct FsmcD5 {}
pub struct FsmcD6 {}
pub struct FsmcD7 {}
pub struct FsmcD8 {}
pub struct FsmcD9 {}
pub struct FsmcD10 {}
pub struct FsmcD11 {}
pub struct FsmcD12 {}
pub struct FsmcA0 {}
pub struct FsmcA1 {}
pub struct FsmcA2 {}
pub struct FsmcA3 {}
pub struct FsmcA4 {}
pub struct FsmcA5 {}
pub struct FsmcNiord {}
pub struct FsmcNreg {}
pub struct FsmcNiowr {}
pub struct FsmcCd {}
pub struct FsmcIntr {}
pub struct DcmiD12 {}
pub struct FsmcA6 {}
pub struct FsmcA7 {}
pub struct FsmcA8 {}
pub struct FsmcA9 {}
pub struct FsmcA10 {}
pub struct FsmcA11 {}
pub struct FsmcA12 {}
pub struct FsmcA13 {}
pub struct FsmcA14 {}
pub struct FsmcA15 {}
pub struct FsmcInt2 {}
pub struct FsmcInt3 {}
pub struct FsmcNe2 {}
pub struct FsmcNce3 {}
pub struct FsmcNce41 {}
pub struct FsmcNe3 {}
pub struct FsmcNce42 {}
pub struct FsmcNe4 {}
pub struct FsmcA24 {}
pub struct FsmcA25 {}
pub struct DcmiD13 {}
