#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;

pub use super::port::*;

pin!(PA00, Pa00, PORTA, Porta, PA00_PIN, PortPin, PORTA_PERIPH, 0);
   pin_source!(Pa00, super::sercom::Sercom1, super::sig::SigPad0, 3);
   pin_source!(Pa00, super::tcc::Tcc2, super::sig::SigWo0, 4);
pin!(PA01, Pa01, PORTA, Porta, PA01_PIN, PortPin, PORTA_PERIPH, 1);
   pin_source!(Pa01, super::sercom::Sercom1, super::sig::SigPad1, 3);
   pin_source!(Pa01, super::tcc::Tcc2, super::sig::SigWo1, 4);
pin!(PA02, Pa02, PORTA, Porta, PA02_PIN, PortPin, PORTA_PERIPH, 2);
   pin_source!(Pa02, super::adc::AdcCh0, super::sig::SigAin, 1);
pin!(PA03, Pa03, PORTA, Porta, PA03_PIN, PortPin, PORTA_PERIPH, 3);
   pin_source!(Pa03, super::adc::AdcCh1, super::sig::SigAin, 1);
pin!(PA04, Pa04, PORTA, Porta, PA04_PIN, PortPin, PORTA_PERIPH, 4);
   pin_source!(Pa04, super::adc::AdcCh4, super::sig::SigAin, 1);
   pin_source!(Pa04, super::adc::AdcCh0, super::sig::SigAin, 1);
   pin_source!(Pa04, super::sercom::Sercom0, super::sig::SigPad0, 3);
   pin_source!(Pa04, super::tcc::Tcc0, super::sig::SigWo0, 4);
pin!(PA05, Pa05, PORTA, Porta, PA05_PIN, PortPin, PORTA_PERIPH, 5);
   pin_source!(Pa05, super::adc::AdcCh5, super::sig::SigAin, 1);
   pin_source!(Pa05, super::adc::AdcCh1, super::sig::SigAin, 1);
   pin_source!(Pa05, super::sercom::Sercom0, super::sig::SigPad1, 3);
   pin_source!(Pa05, super::tcc::Tcc0, super::sig::SigWo1, 4);
pin!(PA06, Pa06, PORTA, Porta, PA06_PIN, PortPin, PORTA_PERIPH, 6);
   pin_source!(Pa06, super::adc::AdcCh6, super::sig::SigAin, 1);
   pin_source!(Pa06, super::adc::AdcCh2, super::sig::SigAin, 1);
   pin_source!(Pa06, super::sercom::Sercom0, super::sig::SigPad2, 3);
   pin_source!(Pa06, super::tcc::Tcc1, super::sig::SigWo0, 4);
pin!(PA07, Pa07, PORTA, Porta, PA07_PIN, PortPin, PORTA_PERIPH, 7);
   pin_source!(Pa07, super::adc::AdcCh7, super::sig::SigAin, 1);
   pin_source!(Pa07, super::adc::AdcCh3, super::sig::SigAin, 1);
   pin_source!(Pa07, super::sercom::Sercom0, super::sig::SigPad3, 3);
   pin_source!(Pa07, super::tcc::Tcc1, super::sig::SigWo1, 4);
pin!(PA08, Pa08, PORTA, Porta, PA08_PIN, PortPin, PORTA_PERIPH, 8);
   pin_source!(Pa08, super::adc::AdcCh16, super::sig::SigAin, 1);
   pin_source!(Pa08, super::sercom::Sercom0, super::sig::SigPad0, 2);
   pin_source!(Pa08, super::sercom::Sercom2, super::sig::SigPad0, 3);
   pin_source!(Pa08, super::tcc::Tcc0, super::sig::SigWo0, 4);
   pin_source!(Pa08, super::tcc::Tcc1, super::sig::SigWo2, 5);
pin!(PA09, Pa09, PORTA, Porta, PA09_PIN, PortPin, PORTA_PERIPH, 9);
   pin_source!(Pa09, super::adc::AdcCh17, super::sig::SigAin, 1);
   pin_source!(Pa09, super::sercom::Sercom0, super::sig::SigPad1, 2);
   pin_source!(Pa09, super::sercom::Sercom2, super::sig::SigPad1, 3);
   pin_source!(Pa09, super::tcc::Tcc0, super::sig::SigWo1, 4);
   pin_source!(Pa09, super::tcc::Tcc1, super::sig::SigWo3, 5);
pin!(PA10, Pa10, PORTA, Porta, PA10_PIN, PortPin, PORTA_PERIPH, 10);
   pin_source!(Pa10, super::adc::AdcCh18, super::sig::SigAin, 1);
   pin_source!(Pa10, super::sercom::Sercom0, super::sig::SigPad2, 2);
   pin_source!(Pa10, super::sercom::Sercom2, super::sig::SigPad2, 3);
   pin_source!(Pa10, super::tcc::Tcc1, super::sig::SigWo0, 4);
   pin_source!(Pa10, super::tcc::Tcc0, super::sig::SigWo2, 5);
pin!(PA11, Pa11, PORTA, Porta, PA11_PIN, PortPin, PORTA_PERIPH, 11);
   pin_source!(Pa11, super::adc::AdcCh19, super::sig::SigAin, 1);
   pin_source!(Pa11, super::sercom::Sercom0, super::sig::SigPad3, 2);
   pin_source!(Pa11, super::sercom::Sercom2, super::sig::SigPad3, 3);
   pin_source!(Pa11, super::tcc::Tcc1, super::sig::SigWo1, 4);
   pin_source!(Pa11, super::tcc::Tcc0, super::sig::SigWo3, 5);
pin!(PA12, Pa12, PORTA, Porta, PA12_PIN, PortPin, PORTA_PERIPH, 12);
   pin_source!(Pa12, super::sercom::Sercom2, super::sig::SigPad0, 2);
   pin_source!(Pa12, super::sercom::Sercom4, super::sig::SigPad0, 3);
   pin_source!(Pa12, super::tcc::Tcc2, super::sig::SigWo0, 4);
   pin_source!(Pa12, super::tcc::Tcc0, super::sig::SigWo6, 5);
pin!(PA13, Pa13, PORTA, Porta, PA13_PIN, PortPin, PORTA_PERIPH, 13);
   pin_source!(Pa13, super::sercom::Sercom2, super::sig::SigPad1, 2);
   pin_source!(Pa13, super::sercom::Sercom4, super::sig::SigPad1, 3);
   pin_source!(Pa13, super::tcc::Tcc2, super::sig::SigWo1, 4);
   pin_source!(Pa13, super::tcc::Tcc0, super::sig::SigWo7, 5);
pin!(PA14, Pa14, PORTA, Porta, PA14_PIN, PortPin, PORTA_PERIPH, 14);
   pin_source!(Pa14, super::sercom::Sercom2, super::sig::SigPad2, 2);
   pin_source!(Pa14, super::sercom::Sercom4, super::sig::SigPad2, 3);
   pin_source!(Pa14, super::tc::Tc3Ch0, super::sig::SigWo, 4);
   pin_source!(Pa14, super::tcc::Tcc0, super::sig::SigWo4, 5);
pin!(PA15, Pa15, PORTA, Porta, PA15_PIN, PortPin, PORTA_PERIPH, 15);
   pin_source!(Pa15, super::sercom::Sercom2, super::sig::SigPad3, 2);
   pin_source!(Pa15, super::sercom::Sercom4, super::sig::SigPad3, 3);
   pin_source!(Pa15, super::tc::Tc3Ch1, super::sig::SigWo, 4);
   pin_source!(Pa15, super::tcc::Tcc0, super::sig::SigWo5, 5);
pin!(PA16, Pa16, PORTA, Porta, PA16_PIN, PortPin, PORTA_PERIPH, 16);
   pin_source!(Pa16, super::sercom::Sercom1, super::sig::SigPad0, 2);
   pin_source!(Pa16, super::sercom::Sercom3, super::sig::SigPad0, 3);
   pin_source!(Pa16, super::tcc::Tcc2, super::sig::SigWo0, 4);
   pin_source!(Pa16, super::tcc::Tcc0, super::sig::SigWo6, 5);
pin!(PA17, Pa17, PORTA, Porta, PA17_PIN, PortPin, PORTA_PERIPH, 17);
   pin_source!(Pa17, super::sercom::Sercom1, super::sig::SigPad1, 2);
   pin_source!(Pa17, super::sercom::Sercom3, super::sig::SigPad1, 3);
   pin_source!(Pa17, super::tcc::Tcc2, super::sig::SigWo1, 4);
   pin_source!(Pa17, super::tcc::Tcc0, super::sig::SigWo7, 5);
pin!(PA18, Pa18, PORTA, Porta, PA18_PIN, PortPin, PORTA_PERIPH, 18);
   pin_source!(Pa18, super::sercom::Sercom1, super::sig::SigPad2, 2);
   pin_source!(Pa18, super::sercom::Sercom3, super::sig::SigPad2, 3);
   pin_source!(Pa18, super::tc::Tc3Ch0, super::sig::SigWo, 4);
   pin_source!(Pa18, super::tcc::Tcc0, super::sig::SigWo2, 5);
pin!(PA19, Pa19, PORTA, Porta, PA19_PIN, PortPin, PORTA_PERIPH, 19);
   pin_source!(Pa19, super::sercom::Sercom1, super::sig::SigPad3, 2);
   pin_source!(Pa19, super::sercom::Sercom3, super::sig::SigPad3, 3);
   pin_source!(Pa19, super::tc::Tc3Ch1, super::sig::SigWo, 4);
   pin_source!(Pa19, super::tcc::Tcc0, super::sig::SigWo3, 5);
pin!(PA20, Pa20, PORTA, Porta, PA20_PIN, PortPin, PORTA_PERIPH, 20);
   pin_source!(Pa20, super::sercom::Sercom5, super::sig::SigPad2, 2);
   pin_source!(Pa20, super::sercom::Sercom3, super::sig::SigPad2, 3);
   pin_source!(Pa20, super::tcc::Tcc0, super::sig::SigWo6, 5);
pin!(PA21, Pa21, PORTA, Porta, PA21_PIN, PortPin, PORTA_PERIPH, 21);
   pin_source!(Pa21, super::sercom::Sercom5, super::sig::SigPad3, 2);
   pin_source!(Pa21, super::sercom::Sercom3, super::sig::SigPad3, 3);
   pin_source!(Pa21, super::tcc::Tcc0, super::sig::SigWo7, 5);
pin!(PA22, Pa22, PORTA, Porta, PA22_PIN, PortPin, PORTA_PERIPH, 22);
   pin_source!(Pa22, super::sercom::Sercom3, super::sig::SigPad0, 2);
   pin_source!(Pa22, super::sercom::Sercom5, super::sig::SigPad0, 3);
   pin_source!(Pa22, super::tc::Tc4Ch0, super::sig::SigWo, 4);
   pin_source!(Pa22, super::tcc::Tcc0, super::sig::SigWo4, 5);
pin!(PA23, Pa23, PORTA, Porta, PA23_PIN, PortPin, PORTA_PERIPH, 23);
   pin_source!(Pa23, super::sercom::Sercom3, super::sig::SigPad1, 2);
   pin_source!(Pa23, super::sercom::Sercom5, super::sig::SigPad1, 3);
   pin_source!(Pa23, super::tc::Tc4Ch1, super::sig::SigWo, 4);
   pin_source!(Pa23, super::tcc::Tcc0, super::sig::SigWo5, 5);
pin!(PA24, Pa24, PORTA, Porta, PA24_PIN, PortPin, PORTA_PERIPH, 24);
   pin_source!(Pa24, super::sercom::Sercom3, super::sig::SigPad2, 2);
   pin_source!(Pa24, super::sercom::Sercom5, super::sig::SigPad2, 3);
   pin_source!(Pa24, super::tc::Tc5Ch0, super::sig::SigWo, 4);
   pin_source!(Pa24, super::tcc::Tcc1, super::sig::SigWo2, 5);
pin!(PA25, Pa25, PORTA, Porta, PA25_PIN, PortPin, PORTA_PERIPH, 25);
   pin_source!(Pa25, super::sercom::Sercom3, super::sig::SigPad3, 2);
   pin_source!(Pa25, super::sercom::Sercom5, super::sig::SigPad3, 3);
   pin_source!(Pa25, super::tc::Tc5Ch1, super::sig::SigWo, 4);
   pin_source!(Pa25, super::tcc::Tcc1, super::sig::SigWo3, 5);
pin!(PA27, Pa27, PORTA, Porta, PA27_PIN, PortPin, PORTA_PERIPH, 27);
pin!(PA28, Pa28, PORTA, Porta, PA28_PIN, PortPin, PORTA_PERIPH, 28);
pin!(PA30, Pa30, PORTA, Porta, PA30_PIN, PortPin, PORTA_PERIPH, 30);
   pin_source!(Pa30, super::sercom::Sercom1, super::sig::SigPad2, 3);
   pin_source!(Pa30, super::tcc::Tcc1, super::sig::SigWo0, 4);
pin!(PA31, Pa31, PORTA, Porta, PA31_PIN, PortPin, PORTA_PERIPH, 31);
   pin_source!(Pa31, super::sercom::Sercom1, super::sig::SigPad3, 3);
   pin_source!(Pa31, super::tcc::Tcc1, super::sig::SigWo1, 4);
pin!(PB00, Pb00, PORTB, Portb, PB00_PIN, PortPin, PORTB_PERIPH, 0);
   pin_source!(Pb00, super::adc::AdcCh8, super::sig::SigAin, 1);
   pin_source!(Pb00, super::sercom::Sercom5, super::sig::SigPad2, 3);
pin!(PB01, Pb01, PORTB, Portb, PB01_PIN, PortPin, PORTB_PERIPH, 1);
   pin_source!(Pb01, super::adc::AdcCh9, super::sig::SigAin, 1);
   pin_source!(Pb01, super::sercom::Sercom5, super::sig::SigPad3, 3);
pin!(PB02, Pb02, PORTB, Portb, PB02_PIN, PortPin, PORTB_PERIPH, 2);
   pin_source!(Pb02, super::adc::AdcCh10, super::sig::SigAin, 1);
   pin_source!(Pb02, super::sercom::Sercom5, super::sig::SigPad0, 3);
pin!(PB03, Pb03, PORTB, Portb, PB03_PIN, PortPin, PORTB_PERIPH, 3);
   pin_source!(Pb03, super::adc::AdcCh11, super::sig::SigAin, 1);
   pin_source!(Pb03, super::sercom::Sercom5, super::sig::SigPad1, 3);
pin!(PB04, Pb04, PORTB, Portb, PB04_PIN, PortPin, PORTB_PERIPH, 4);
   pin_source!(Pb04, super::adc::AdcCh12, super::sig::SigAin, 1);
pin!(PB05, Pb05, PORTB, Portb, PB05_PIN, PortPin, PORTB_PERIPH, 5);
   pin_source!(Pb05, super::adc::AdcCh13, super::sig::SigAin, 1);
pin!(PB06, Pb06, PORTB, Portb, PB06_PIN, PortPin, PORTB_PERIPH, 6);
   pin_source!(Pb06, super::adc::AdcCh14, super::sig::SigAin, 1);
pin!(PB07, Pb07, PORTB, Portb, PB07_PIN, PortPin, PORTB_PERIPH, 7);
   pin_source!(Pb07, super::adc::AdcCh15, super::sig::SigAin, 1);
pin!(PB08, Pb08, PORTB, Portb, PB08_PIN, PortPin, PORTB_PERIPH, 8);
   pin_source!(Pb08, super::adc::AdcCh2, super::sig::SigAin, 1);
   pin_source!(Pb08, super::sercom::Sercom4, super::sig::SigPad0, 3);
   pin_source!(Pb08, super::tc::Tc4Ch0, super::sig::SigWo, 4);
pin!(PB09, Pb09, PORTB, Portb, PB09_PIN, PortPin, PORTB_PERIPH, 9);
   pin_source!(Pb09, super::adc::AdcCh3, super::sig::SigAin, 1);
   pin_source!(Pb09, super::sercom::Sercom4, super::sig::SigPad1, 3);
   pin_source!(Pb09, super::tc::Tc4Ch1, super::sig::SigWo, 4);
pin!(PB10, Pb10, PORTB, Portb, PB10_PIN, PortPin, PORTB_PERIPH, 10);
   pin_source!(Pb10, super::sercom::Sercom4, super::sig::SigPad2, 3);
   pin_source!(Pb10, super::tc::Tc5Ch0, super::sig::SigWo, 4);
   pin_source!(Pb10, super::tcc::Tcc0, super::sig::SigWo4, 5);
pin!(PB11, Pb11, PORTB, Portb, PB11_PIN, PortPin, PORTB_PERIPH, 11);
   pin_source!(Pb11, super::sercom::Sercom4, super::sig::SigPad3, 3);
   pin_source!(Pb11, super::tc::Tc5Ch1, super::sig::SigWo, 4);
   pin_source!(Pb11, super::tcc::Tcc0, super::sig::SigWo5, 5);
pin!(PB12, Pb12, PORTB, Portb, PB12_PIN, PortPin, PORTB_PERIPH, 12);
   pin_source!(Pb12, super::sercom::Sercom4, super::sig::SigPad0, 2);
   pin_source!(Pb12, super::tc::Tc4Ch0, super::sig::SigWo, 4);
   pin_source!(Pb12, super::tcc::Tcc0, super::sig::SigWo6, 5);
pin!(PB13, Pb13, PORTB, Portb, PB13_PIN, PortPin, PORTB_PERIPH, 13);
   pin_source!(Pb13, super::sercom::Sercom4, super::sig::SigPad1, 2);
   pin_source!(Pb13, super::tc::Tc4Ch1, super::sig::SigWo, 4);
   pin_source!(Pb13, super::tcc::Tcc0, super::sig::SigWo7, 5);
pin!(PB14, Pb14, PORTB, Portb, PB14_PIN, PortPin, PORTB_PERIPH, 14);
   pin_source!(Pb14, super::sercom::Sercom4, super::sig::SigPad2, 2);
   pin_source!(Pb14, super::tc::Tc5Ch0, super::sig::SigWo, 4);
pin!(PB15, Pb15, PORTB, Portb, PB15_PIN, PortPin, PORTB_PERIPH, 15);
   pin_source!(Pb15, super::sercom::Sercom4, super::sig::SigPad3, 2);
   pin_source!(Pb15, super::tc::Tc5Ch1, super::sig::SigWo, 4);
pin!(PB16, Pb16, PORTB, Portb, PB16_PIN, PortPin, PORTB_PERIPH, 16);
   pin_source!(Pb16, super::sercom::Sercom5, super::sig::SigPad0, 2);
   pin_source!(Pb16, super::tcc::Tcc0, super::sig::SigWo4, 5);
pin!(PB17, Pb17, PORTB, Portb, PB17_PIN, PortPin, PORTB_PERIPH, 17);
   pin_source!(Pb17, super::sercom::Sercom5, super::sig::SigPad1, 2);
   pin_source!(Pb17, super::tcc::Tcc0, super::sig::SigWo5, 5);
pin!(PB22, Pb22, PORTB, Portb, PB22_PIN, PortPin, PORTB_PERIPH, 22);
   pin_source!(Pb22, super::sercom::Sercom5, super::sig::SigPad2, 3);
pin!(PB23, Pb23, PORTB, Portb, PB23_PIN, PortPin, PORTB_PERIPH, 23);
   pin_source!(Pb23, super::sercom::Sercom5, super::sig::SigPad3, 3);
pin!(PB30, Pb30, PORTB, Portb, PB30_PIN, PortPin, PORTB_PERIPH, 30);
   pin_source!(Pb30, super::sercom::Sercom5, super::sig::SigPad0, 3);
   pin_source!(Pb30, super::tcc::Tcc0, super::sig::SigWo0, 4);
   pin_source!(Pb30, super::tcc::Tcc1, super::sig::SigWo2, 5);
pin!(PB31, Pb31, PORTB, Portb, PB31_PIN, PortPin, PORTB_PERIPH, 31);
   pin_source!(Pb31, super::sercom::Sercom5, super::sig::SigPad1, 3);
   pin_source!(Pb31, super::tcc::Tcc0, super::sig::SigWo1, 4);
   pin_source!(Pb31, super::tcc::Tcc1, super::sig::SigWo3, 5);
