#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;
pub use super::gpio::*;

pin!(PA0, Pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, 0);
   pin_source!(Pa0, super::adc::Adc1Ch1, super::sig::SigAdc, 0);
   pin_source!(Pa0, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa0, super::usart::Usart2, super::sig::SigCts, 7);
pin!(PA1, Pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, 1);
   pin_source!(Pa1, super::adc::Adc1Ch2, super::sig::SigAdc, 0);
   pin_source!(Pa1, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
pin!(PA2, Pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, 2);
   pin_source!(Pa2, super::adc::Adc1Ch3, super::sig::SigAdc, 0);
   pin_source!(Pa2, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pa2, super::usart::Usart2, super::sig::SigTx, 7);
   pin_source!(Pa2, super::tim_gen::Tim15Ch1, super::sig::SigTim, 9);
pin!(PA3, Pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, 3);
   pin_source!(Pa3, super::adc::Adc1Ch4, super::sig::SigAdc, 0);
   pin_source!(Pa3, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pa3, super::usart::Usart2, super::sig::SigRx, 7);
   pin_source!(Pa3, super::tim_gen::Tim15Ch2, super::sig::SigTim, 9);
pin!(PA4, Pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, 4);
   pin_source!(Pa4, super::adc::Adc1Ch5, super::sig::SigAdc, 0);
   pin_source!(Pa4, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PA5, Pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, 5);
   pin_source!(Pa5, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
pin!(PA6, Pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, 6);
   pin_source!(Pa6, super::adc::Adc1Ch10, super::sig::SigAdc, 0);
   pin_source!(Pa6, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
pin!(PA7, Pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, 7);
   pin_source!(Pa7, super::adc::Adc1Ch15, super::sig::SigAdc, 0);
   pin_source!(Pa7, super::tim_gen::Tim17Ch1, super::sig::SigTim, 1);
pin!(PA8, Pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, 8);
   pin_source!(Pa8, super::tim_adv::Tim1Ch1, super::sig::SigTim, 6);
   pin_source!(Pa8, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PA9, Pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, 9);
   pin_source!(Pa9, super::tim_adv::Tim1Ch2, super::sig::SigTim, 6);
   pin_source!(Pa9, super::usart::Usart1, super::sig::SigTx, 7);
   pin_source!(Pa9, super::tim_gen::Tim2Ch3, super::sig::SigTim, 10);
pin!(PA10, Pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, 10);
   pin_source!(Pa10, super::tim_adv::Tim1Ch3, super::sig::SigTim, 6);
   pin_source!(Pa10, super::usart::Usart1, super::sig::SigRx, 7);
   pin_source!(Pa10, super::tim_gen::Tim2Ch4, super::sig::SigTim, 10);
pin!(PA11, Pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, 11);
   pin_source!(Pa11, super::usart::Usart1, super::sig::SigCts, 7);
   pin_source!(Pa11, super::tim_adv::Tim1Ch4, super::sig::SigTim, 11);
pin!(PA12, Pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, 12);
   pin_source!(Pa12, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
pin!(PA13, Pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, 13);
   pin_source!(Pa13, super::tim_gen::Tim16Ch1, super::sig::SigTimn, 1);
   pin_source!(Pa13, super::usart::Usart3, super::sig::SigCts, 7);
pin!(PA14, Pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, 14);
   pin_source!(Pa14, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PA15, Pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, 15);
   pin_source!(Pa15, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa15, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PB0, Pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, 0);
   pin_source!(Pb0, super::adc::Adc1Ch11, super::sig::SigAdc, 0);
pin!(PB1, Pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, 1);
   pin_source!(Pb1, super::adc::Adc1Ch12, super::sig::SigAdc, 0);
pin!(PB2, Pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, 2);
pin!(PB3, Pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, 3);
   pin_source!(Pb3, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pb3, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PB4, Pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, 4);
   pin_source!(Pb4, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pb4, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PB5, Pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, 5);
   pin_source!(Pb5, super::usart::Usart2, super::sig::SigCk, 7);
   pin_source!(Pb5, super::tim_gen::Tim17Ch1, super::sig::SigTim, 10);
pin!(PB6, Pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, 6);
   pin_source!(Pb6, super::tim_gen::Tim16Ch1, super::sig::SigTimn, 1);
   pin_source!(Pb6, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PB7, Pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, 7);
   pin_source!(Pb7, super::tim_gen::Tim17Ch1, super::sig::SigTimn, 1);
   pin_source!(Pb7, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PB8, Pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, 8);
   pin_source!(Pb8, super::tim_gen::Tim16Ch1, super::sig::SigTim, 1);
   pin_source!(Pb8, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PB9, Pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, 9);
   pin_source!(Pb9, super::tim_gen::Tim17Ch1, super::sig::SigTim, 1);
   pin_source!(Pb9, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PB10, Pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, 10);
   pin_source!(Pb10, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pb10, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PB11, Pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, 11);
   pin_source!(Pb11, super::adc::Adc1Ch11, super::sig::SigAdc, 0);
   pin_source!(Pb11, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pb11, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PB12, Pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, 12);
   pin_source!(Pb12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PB13, Pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, 13);
   pin_source!(Pb13, super::adc::Adc1Ch13, super::sig::SigAdc, 0);
   pin_source!(Pb13, super::usart::Usart3, super::sig::SigCts, 7);
pin!(PB14, Pb14, GPIOB, Gpiob, PB14_PIN, GpioPin, GPIOB_PERIPH, 14);
   pin_source!(Pb14, super::tim_gen::Tim15Ch1, super::sig::SigTim, 1);
pin!(PB15, Pb15, GPIOB, Gpiob, PB15_PIN, GpioPin, GPIOB_PERIPH, 15);
   pin_source!(Pb15, super::tim_gen::Tim15Ch2, super::sig::SigTim, 1);
pin!(PC0, Pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, 0);
   pin_source!(Pc0, super::tim_adv::Tim1Ch1, super::sig::SigTim, 2);
pin!(PC1, Pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, 1);
   pin_source!(Pc1, super::tim_adv::Tim1Ch2, super::sig::SigTim, 2);
pin!(PC2, Pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, 2);
   pin_source!(Pc2, super::tim_adv::Tim1Ch3, super::sig::SigTim, 2);
pin!(PC3, Pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, 3);
   pin_source!(Pc3, super::tim_adv::Tim1Ch4, super::sig::SigTim, 2);
pin!(PC4, Pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, 4);
   pin_source!(Pc4, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PC5, Pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, 5);
   pin_source!(Pc5, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PC6, Pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, 6);
pin!(PC7, Pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, 7);
pin!(PC8, Pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, 8);
pin!(PC9, Pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, 9);
pin!(PC10, Pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, 10);
   pin_source!(Pc10, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PC11, Pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, 11);
   pin_source!(Pc11, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PC12, Pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, 12);
   pin_source!(Pc12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PC13, Pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, 13);
pin!(PC14, Pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, 14);
pin!(PC15, Pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, 15);
pin!(PD2, Pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, 2);
pin!(PF0, Pf0, GPIOF, Gpiof, PF0_PIN, GpioPin, GPIOF_PERIPH, 0);
pin!(PF1, Pf1, GPIOF, Gpiof, PF1_PIN, GpioPin, GPIOF_PERIPH, 1);
