[package]
name = "k64"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
kinetis-common = { path = "../kinetis-common" }

[features]
no-heap = [ "kinetis-common/no-heap" ]
default = []

K64FN1M0 = []
K64FX512 = []
