#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;
pub use super::gpio::*;

pin!(PA0, Pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, 0);
   pin_source!(Pa0, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa0, super::usart::Usart2, super::sig::SigCts, 7);
   pin_source!(Pa0, super::usart::Uart4, super::sig::SigTx, 8);
pin!(PA1, Pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, 1);
   pin_source!(Pa1, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pa1, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
   pin_source!(Pa1, super::spi::Spi1, super::sig::SigSpiSck, 5);
   pin_source!(Pa1, super::usart::Uart4, super::sig::SigRx, 8);
pin!(PA2, Pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, 2);
   pin_source!(Pa2, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pa2, super::usart::Usart2, super::sig::SigTx, 7);
   pin_source!(Pa2, super::lpuart::Lpuart1, super::sig::SigTx, 8);
   pin_source!(Pa2, super::tim_gen::Tim15Ch1, super::sig::SigTim, 14);
pin!(PA3, Pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, 3);
   pin_source!(Pa3, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pa3, super::usart::Usart2, super::sig::SigRx, 7);
   pin_source!(Pa3, super::lpuart::Lpuart1, super::sig::SigRx, 8);
   pin_source!(Pa3, super::tim_gen::Tim15Ch2, super::sig::SigTim, 14);
pin!(PA4, Pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, 4);
   pin_source!(Pa4, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pa4, super::spi::Spi3, super::sig::SigSpiNss, 6);
   pin_source!(Pa4, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PA5, Pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, 5);
   pin_source!(Pa5, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa5, super::spi::Spi1, super::sig::SigSpiSck, 5);
   pin_source!(Pa5, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkout, 6);
pin!(PA6, Pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, 6);
   pin_source!(Pa6, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pa6, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pa6, super::usart::Usart3, super::sig::SigCts, 7);
   pin_source!(Pa6, super::lpuart::Lpuart1, super::sig::SigCts, 8);
   pin_source!(Pa6, super::tim_gen::Tim16Ch1, super::sig::SigTim, 14);
pin!(PA7, Pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, 7);
   pin_source!(Pa7, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pa7, super::i2c::I2c3, super::sig::SigI2cScl, 4);
   pin_source!(Pa7, super::spi::Spi1, super::sig::SigSpiMosi, 5);
   pin_source!(Pa7, super::dfsdm::Dfsdm, super::sig::SigDfsdmDatin0, 6);
pin!(PA8, Pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, 8);
   pin_source!(Pa8, super::tim_adv::Tim1Ch1, super::sig::SigTim, 1);
   pin_source!(Pa8, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin1, 6);
   pin_source!(Pa8, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PA9, Pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, 9);
   pin_source!(Pa9, super::tim_adv::Tim1Ch2, super::sig::SigTim, 1);
   pin_source!(Pa9, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pa9, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PA10, Pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, 10);
   pin_source!(Pa10, super::tim_adv::Tim1Ch3, super::sig::SigTim, 1);
   pin_source!(Pa10, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pa10, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PA11, Pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, 11);
   pin_source!(Pa11, super::tim_adv::Tim1Ch4, super::sig::SigTim, 1);
   pin_source!(Pa11, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pa11, super::usart::Usart1, super::sig::SigCts, 7);
pin!(PA12, Pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, 12);
   pin_source!(Pa12, super::spi::Spi1, super::sig::SigSpiMosi, 5);
pin!(PA13, Pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, 13);
pin!(PA14, Pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, 14);
   pin_source!(Pa14, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
   pin_source!(Pa14, super::i2c::I2c4, super::sig::SigI2cSmba, 5);
pin!(PA15, Pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, 15);
   pin_source!(Pa15, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa15, super::usart::Usart2, super::sig::SigRx, 3);
   pin_source!(Pa15, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pa15, super::spi::Spi3, super::sig::SigSpiNss, 6);
pin!(PB0, Pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, 0);
   pin_source!(Pb0, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
   pin_source!(Pb0, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pb0, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin0, 6);
   pin_source!(Pb0, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PB1, Pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, 1);
   pin_source!(Pb1, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
   pin_source!(Pb1, super::dfsdm::Dfsdm, super::sig::SigDfsdmDatin0, 6);
pin!(PB2, Pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, 2);
   pin_source!(Pb2, super::i2c::I2c3, super::sig::SigI2cSmba, 4);
   pin_source!(Pb2, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin0, 6);
pin!(PB3, Pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, 3);
   pin_source!(Pb3, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pb3, super::spi::Spi1, super::sig::SigSpiSck, 5);
   pin_source!(Pb3, super::spi::Spi3, super::sig::SigSpiSck, 6);
pin!(PB4, Pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, 4);
   pin_source!(Pb4, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pb4, super::i2c::I2c3, super::sig::SigI2cSda, 4);
   pin_source!(Pb4, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pb4, super::spi::Spi3, super::sig::SigSpiMiso, 6);
   pin_source!(Pb4, super::usart::Usart1, super::sig::SigCts, 7);
pin!(PB5, Pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, 5);
   pin_source!(Pb5, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
   pin_source!(Pb5, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
   pin_source!(Pb5, super::spi::Spi1, super::sig::SigSpiMosi, 5);
   pin_source!(Pb5, super::spi::Spi3, super::sig::SigSpiMosi, 6);
   pin_source!(Pb5, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PB6, Pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, 6);
   pin_source!(Pb6, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pb6, super::i2c::I2c4, super::sig::SigI2cScl, 5);
   pin_source!(Pb6, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PB7, Pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, 7);
   pin_source!(Pb7, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pb7, super::i2c::I2c4, super::sig::SigI2cSda, 5);
   pin_source!(Pb7, super::usart::Usart1, super::sig::SigRx, 7);
   pin_source!(Pb7, super::usart::Uart4, super::sig::SigCts, 8);
pin!(PB8, Pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, 8);
   pin_source!(Pb8, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pb8, super::tim_gen::Tim16Ch1, super::sig::SigTim, 14);
pin!(PB9, Pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, 9);
   pin_source!(Pb9, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pb9, super::spi::Spi2, super::sig::SigSpiNss, 5);
pin!(PB10, Pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, 10);
   pin_source!(Pb10, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pb10, super::i2c::I2c4, super::sig::SigI2cScl, 3);
   pin_source!(Pb10, super::i2c::I2c2, super::sig::SigI2cScl, 4);
   pin_source!(Pb10, super::spi::Spi2, super::sig::SigSpiSck, 5);
   pin_source!(Pb10, super::usart::Usart3, super::sig::SigTx, 7);
   pin_source!(Pb10, super::lpuart::Lpuart1, super::sig::SigRx, 8);
pin!(PB11, Pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, 11);
   pin_source!(Pb11, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pb11, super::i2c::I2c4, super::sig::SigI2cSda, 3);
   pin_source!(Pb11, super::i2c::I2c2, super::sig::SigI2cSda, 4);
   pin_source!(Pb11, super::usart::Usart3, super::sig::SigRx, 7);
   pin_source!(Pb11, super::lpuart::Lpuart1, super::sig::SigTx, 8);
pin!(PB12, Pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, 12);
   pin_source!(Pb12, super::i2c::I2c2, super::sig::SigI2cSmba, 4);
   pin_source!(Pb12, super::spi::Spi2, super::sig::SigSpiNss, 5);
   pin_source!(Pb12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PB13, Pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, 13);
   pin_source!(Pb13, super::i2c::I2c2, super::sig::SigI2cScl, 4);
   pin_source!(Pb13, super::spi::Spi2, super::sig::SigSpiSck, 5);
   pin_source!(Pb13, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin1, 6);
   pin_source!(Pb13, super::usart::Usart3, super::sig::SigCts, 7);
   pin_source!(Pb13, super::lpuart::Lpuart1, super::sig::SigCts, 8);
pin!(PB14, Pb14, GPIOB, Gpiob, PB14_PIN, GpioPin, GPIOB_PERIPH, 14);
   pin_source!(Pb14, super::i2c::I2c2, super::sig::SigI2cSda, 4);
   pin_source!(Pb14, super::spi::Spi2, super::sig::SigSpiMiso, 5);
   pin_source!(Pb14, super::tim_gen::Tim15Ch1, super::sig::SigTim, 14);
pin!(PB15, Pb15, GPIOB, Gpiob, PB15_PIN, GpioPin, GPIOB_PERIPH, 15);
   pin_source!(Pb15, super::spi::Spi2, super::sig::SigSpiMosi, 5);
   pin_source!(Pb15, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin2, 6);
   pin_source!(Pb15, super::tim_gen::Tim15Ch2, super::sig::SigTim, 14);
pin!(PC0, Pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, 0);
   pin_source!(Pc0, super::i2c::I2c4, super::sig::SigI2cScl, 2);
   pin_source!(Pc0, super::i2c::I2c3, super::sig::SigI2cScl, 4);
   pin_source!(Pc0, super::lpuart::Lpuart1, super::sig::SigRx, 8);
pin!(PC1, Pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, 1);
   pin_source!(Pc1, super::i2c::I2c4, super::sig::SigI2cSda, 2);
   pin_source!(Pc1, super::i2c::I2c3, super::sig::SigI2cSda, 4);
   pin_source!(Pc1, super::lpuart::Lpuart1, super::sig::SigTx, 8);
pin!(PC2, Pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, 2);
   pin_source!(Pc2, super::spi::Spi2, super::sig::SigSpiMiso, 5);
   pin_source!(Pc2, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkout, 6);
pin!(PC3, Pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, 3);
   pin_source!(Pc3, super::spi::Spi2, super::sig::SigSpiMosi, 5);
pin!(PC4, Pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, 4);
   pin_source!(Pc4, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PC5, Pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, 5);
   pin_source!(Pc5, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PC6, Pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, 6);
   pin_source!(Pc6, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
   pin_source!(Pc6, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin3, 6);
pin!(PC7, Pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, 7);
   pin_source!(Pc7, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
pin!(PC8, Pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, 8);
   pin_source!(Pc8, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
pin!(PC9, Pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, 9);
   pin_source!(Pc9, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
pin!(PC10, Pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, 10);
   pin_source!(Pc10, super::spi::Spi3, super::sig::SigSpiSck, 6);
   pin_source!(Pc10, super::usart::Usart3, super::sig::SigTx, 7);
   pin_source!(Pc10, super::usart::Uart4, super::sig::SigTx, 8);
pin!(PC11, Pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, 11);
   pin_source!(Pc11, super::spi::Spi3, super::sig::SigSpiMiso, 6);
   pin_source!(Pc11, super::usart::Usart3, super::sig::SigRx, 7);
   pin_source!(Pc11, super::usart::Uart4, super::sig::SigRx, 8);
pin!(PC12, Pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, 12);
   pin_source!(Pc12, super::spi::Spi3, super::sig::SigSpiMosi, 6);
   pin_source!(Pc12, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PC13, Pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, 13);
pin!(PC14, Pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, 14);
pin!(PC15, Pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, 15);
pin!(PD0, Pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, 0);
   pin_source!(Pd0, super::spi::Spi2, super::sig::SigSpiNss, 5);
pin!(PD1, Pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, 1);
   pin_source!(Pd1, super::spi::Spi2, super::sig::SigSpiSck, 5);
pin!(PD2, Pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, 2);
pin!(PD3, Pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, 3);
   pin_source!(Pd3, super::spi::Spi2, super::sig::SigSpiMiso, 5);
   pin_source!(Pd3, super::dfsdm::Dfsdm, super::sig::SigDfsdmDatin0, 6);
   pin_source!(Pd3, super::usart::Usart2, super::sig::SigCts, 7);
pin!(PD4, Pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, 4);
   pin_source!(Pd4, super::spi::Spi2, super::sig::SigSpiMosi, 5);
   pin_source!(Pd4, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin0, 6);
pin!(PD5, Pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, 5);
   pin_source!(Pd5, super::usart::Usart2, super::sig::SigTx, 7);
pin!(PD6, Pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, 6);
   pin_source!(Pd6, super::usart::Usart2, super::sig::SigRx, 7);
pin!(PD7, Pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, 7);
   pin_source!(Pd7, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin1, 6);
   pin_source!(Pd7, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PD8, Pd8, GPIOD, Gpiod, PD8_PIN, GpioPin, GPIOD_PERIPH, 8);
   pin_source!(Pd8, super::usart::Usart3, super::sig::SigTx, 7);
pin!(PD9, Pd9, GPIOD, Gpiod, PD9_PIN, GpioPin, GPIOD_PERIPH, 9);
   pin_source!(Pd9, super::usart::Usart3, super::sig::SigRx, 7);
pin!(PD10, Pd10, GPIOD, Gpiod, PD10_PIN, GpioPin, GPIOD_PERIPH, 10);
   pin_source!(Pd10, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PD11, Pd11, GPIOD, Gpiod, PD11_PIN, GpioPin, GPIOD_PERIPH, 11);
   pin_source!(Pd11, super::i2c::I2c4, super::sig::SigI2cSmba, 4);
   pin_source!(Pd11, super::usart::Usart3, super::sig::SigCts, 7);
pin!(PD12, Pd12, GPIOD, Gpiod, PD12_PIN, GpioPin, GPIOD_PERIPH, 12);
   pin_source!(Pd12, super::i2c::I2c4, super::sig::SigI2cScl, 4);
pin!(PD13, Pd13, GPIOD, Gpiod, PD13_PIN, GpioPin, GPIOD_PERIPH, 13);
   pin_source!(Pd13, super::i2c::I2c4, super::sig::SigI2cSda, 4);
pin!(PD14, Pd14, GPIOD, Gpiod, PD14_PIN, GpioPin, GPIOD_PERIPH, 14);
pin!(PD15, Pd15, GPIOD, Gpiod, PD15_PIN, GpioPin, GPIOD_PERIPH, 15);
pin!(PE0, Pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, 0);
   pin_source!(Pe0, super::tim_gen::Tim16Ch1, super::sig::SigTim, 14);
pin!(PE1, Pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, 1);
pin!(PE2, Pe2, GPIOE, Gpioe, PE2_PIN, GpioPin, GPIOE_PERIPH, 2);
pin!(PE3, Pe3, GPIOE, Gpioe, PE3_PIN, GpioPin, GPIOE_PERIPH, 3);
   pin_source!(Pe3, super::tim_gen::Tim3Ch1, super::sig::SigTim, 2);
pin!(PE4, Pe4, GPIOE, Gpioe, PE4_PIN, GpioPin, GPIOE_PERIPH, 4);
   pin_source!(Pe4, super::tim_gen::Tim3Ch2, super::sig::SigTim, 2);
pin!(PE5, Pe5, GPIOE, Gpioe, PE5_PIN, GpioPin, GPIOE_PERIPH, 5);
   pin_source!(Pe5, super::tim_gen::Tim3Ch3, super::sig::SigTim, 2);
   pin_source!(Pe5, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin3, 6);
pin!(PE6, Pe6, GPIOE, Gpioe, PE6_PIN, GpioPin, GPIOE_PERIPH, 6);
   pin_source!(Pe6, super::tim_gen::Tim3Ch4, super::sig::SigTim, 2);
pin!(PE7, Pe7, GPIOE, Gpioe, PE7_PIN, GpioPin, GPIOE_PERIPH, 7);
pin!(PE8, Pe8, GPIOE, Gpioe, PE8_PIN, GpioPin, GPIOE_PERIPH, 8);
   pin_source!(Pe8, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkin2, 6);
pin!(PE9, Pe9, GPIOE, Gpioe, PE9_PIN, GpioPin, GPIOE_PERIPH, 9);
   pin_source!(Pe9, super::tim_adv::Tim1Ch1, super::sig::SigTim, 1);
   pin_source!(Pe9, super::dfsdm::Dfsdm, super::sig::SigDfsdmCkout, 6);
pin!(PE10, Pe10, GPIOE, Gpioe, PE10_PIN, GpioPin, GPIOE_PERIPH, 10);
pin!(PE11, Pe11, GPIOE, Gpioe, PE11_PIN, GpioPin, GPIOE_PERIPH, 11);
   pin_source!(Pe11, super::tim_adv::Tim1Ch2, super::sig::SigTim, 1);
pin!(PE12, Pe12, GPIOE, Gpioe, PE12_PIN, GpioPin, GPIOE_PERIPH, 12);
   pin_source!(Pe12, super::spi::Spi1, super::sig::SigSpiNss, 5);
pin!(PE13, Pe13, GPIOE, Gpioe, PE13_PIN, GpioPin, GPIOE_PERIPH, 13);
   pin_source!(Pe13, super::tim_adv::Tim1Ch3, super::sig::SigTim, 1);
   pin_source!(Pe13, super::spi::Spi1, super::sig::SigSpiSck, 5);
pin!(PE14, Pe14, GPIOE, Gpioe, PE14_PIN, GpioPin, GPIOE_PERIPH, 14);
   pin_source!(Pe14, super::tim_adv::Tim1Ch4, super::sig::SigTim, 1);
   pin_source!(Pe14, super::spi::Spi1, super::sig::SigSpiMiso, 5);
pin!(PE15, Pe15, GPIOE, Gpioe, PE15_PIN, GpioPin, GPIOE_PERIPH, 15);
   pin_source!(Pe15, super::spi::Spi1, super::sig::SigSpiMosi, 5);
pin!(PH0, Ph0, GPIOH, Gpioh, PH0_PIN, GpioPin, GPIOH_PERIPH, 0);
pin!(PH1, Ph1, GPIOH, Gpioh, PH1_PIN, GpioPin, GPIOH_PERIPH, 1);
pin!(PH3, Ph3, GPIOH, Gpioh, PH3_PIN, GpioPin, GPIOH_PERIPH, 3);
