#[allow(unused_imports)] use ::bobbin_common::*;
pub use ::bobbin_common::pin::*;
pub use ::bobbin_common::gate::*;

pub use super::gpio::*;

pin!(PA0, Pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, 0);
   pin_source!(Pa0, super::adc::Adc1Ch5, super::sig::SigAdc, 0);
   pin_source!(Pa0, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa0, super::usart::Usart2, super::sig::SigCts, 7);
   pin_source!(Pa0, super::tim_gen::Tim2, super::sig::SigEtr, 14);
pin!(PA1, Pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, 1);
   pin_source!(Pa1, super::adc::Adc1Ch6, super::sig::SigAdc, 0);
   pin_source!(Pa1, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pa1, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
   pin_source!(Pa1, super::spi::Spi1, super::sig::SigSpiSck, 5);
pin!(PA2, Pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, 2);
   pin_source!(Pa2, super::adc::Adc1Ch7, super::sig::SigAdc, 0);
   pin_source!(Pa2, super::tim_gen::Tim2Ch3, super::sig::SigTim, 1);
   pin_source!(Pa2, super::usart::Usart2, super::sig::SigTx, 7);
   pin_source!(Pa2, super::lpuart::Lpuart1, super::sig::SigTx, 8);
   pin_source!(Pa2, super::tim_gen::Tim15Ch1, super::sig::SigTim, 14);
pin!(PA3, Pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, 3);
   pin_source!(Pa3, super::adc::Adc1Ch8, super::sig::SigAdc, 0);
   pin_source!(Pa3, super::tim_gen::Tim2Ch4, super::sig::SigTim, 1);
   pin_source!(Pa3, super::usart::Usart2, super::sig::SigRx, 7);
   pin_source!(Pa3, super::lpuart::Lpuart1, super::sig::SigRx, 8);
   pin_source!(Pa3, super::tim_gen::Tim15Ch2, super::sig::SigTim, 14);
pin!(PA4, Pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, 4);
   pin_source!(Pa4, super::adc::Adc1Ch9, super::sig::SigAdc, 0);
   pin_source!(Pa4, super::dac::Dac1Ch1, super::sig::SigDac, 0);
   pin_source!(Pa4, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pa4, super::usart::Usart2, super::sig::SigCk, 7);
pin!(PA5, Pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, 5);
   pin_source!(Pa5, super::adc::Adc1Ch10, super::sig::SigAdc, 0);
   pin_source!(Pa5, super::dac::Dac1Ch2, super::sig::SigDac, 0);
   pin_source!(Pa5, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa5, super::tim_gen::Tim2, super::sig::SigEtr, 2);
   pin_source!(Pa5, super::spi::Spi1, super::sig::SigSpiSck, 5);
pin!(PA6, Pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, 6);
   pin_source!(Pa6, super::adc::Adc1Ch11, super::sig::SigAdc, 0);
   pin_source!(Pa6, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pa6, super::usart::Usart3, super::sig::SigCts, 7);
   pin_source!(Pa6, super::lpuart::Lpuart1, super::sig::SigCts, 8);
   pin_source!(Pa6, super::tim_gen::Tim16Ch1, super::sig::SigTim, 14);
pin!(PA7, Pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, 7);
   pin_source!(Pa7, super::adc::Adc1Ch12, super::sig::SigAdc, 0);
   pin_source!(Pa7, super::spi::Spi1, super::sig::SigSpiMosi, 5);
pin!(PA8, Pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, 8);
   pin_source!(Pa8, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PA9, Pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, 9);
   pin_source!(Pa9, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pa9, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PA10, Pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, 10);
   pin_source!(Pa10, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pa10, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PA11, Pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, 11);
   pin_source!(Pa11, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pa11, super::usart::Usart1, super::sig::SigCts, 7);
pin!(PA12, Pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, 12);
   pin_source!(Pa12, super::spi::Spi1, super::sig::SigSpiMosi, 5);
pin!(PA13, Pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, 13);
pin!(PA14, Pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, 14);
   pin_source!(Pa14, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
pin!(PA15, Pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, 15);
   pin_source!(Pa15, super::tim_gen::Tim2Ch1, super::sig::SigTim, 1);
   pin_source!(Pa15, super::tim_gen::Tim2, super::sig::SigEtr, 2);
   pin_source!(Pa15, super::usart::Usart2, super::sig::SigRx, 3);
   pin_source!(Pa15, super::spi::Spi1, super::sig::SigSpiNss, 5);
pin!(PB0, Pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, 0);
   pin_source!(Pb0, super::adc::Adc1Ch15, super::sig::SigAdc, 0);
   pin_source!(Pb0, super::spi::Spi1, super::sig::SigSpiNss, 5);
   pin_source!(Pb0, super::usart::Usart3, super::sig::SigCk, 7);
pin!(PB1, Pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, 1);
pin!(PB3, Pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, 3);
   pin_source!(Pb3, super::tim_gen::Tim2Ch2, super::sig::SigTim, 1);
   pin_source!(Pb3, super::spi::Spi1, super::sig::SigSpiSck, 5);
pin!(PB4, Pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, 4);
   pin_source!(Pb4, super::spi::Spi1, super::sig::SigSpiMiso, 5);
   pin_source!(Pb4, super::usart::Usart1, super::sig::SigCts, 7);
pin!(PB5, Pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, 5);
   pin_source!(Pb5, super::i2c::I2c1, super::sig::SigI2cSmba, 4);
   pin_source!(Pb5, super::spi::Spi1, super::sig::SigSpiMosi, 5);
   pin_source!(Pb5, super::usart::Usart1, super::sig::SigCk, 7);
pin!(PB6, Pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, 6);
   pin_source!(Pb6, super::i2c::I2c1, super::sig::SigI2cScl, 4);
   pin_source!(Pb6, super::usart::Usart1, super::sig::SigTx, 7);
pin!(PB7, Pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, 7);
   pin_source!(Pb7, super::i2c::I2c1, super::sig::SigI2cSda, 4);
   pin_source!(Pb7, super::usart::Usart1, super::sig::SigRx, 7);
pin!(PC0, Pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, 0);
   pin_source!(Pc0, super::lpuart::Lpuart1, super::sig::SigRx, 6);
pin!(PC14, Pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, 14);
pin!(PC15, Pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, 15);
pin!(PH3, Ph3, GPIOH, Gpioh, PH3_PIN, GpioPin, GPIOH_PERIPH, 3);
