[package]
name = "bobbin-cortexm"
version = "0.1.0"

[dependencies]
bobbin-bits = "0.1.1"
bobbin-mcu = { path = "../../lib/bobbin-mcu" }
bobbin-hal = { path = "../../lib/bobbin-hal" }
bobbin-sys = { path = "../../lib/bobbin-sys" }

[features]
no-heap = ["bobbin-sys/no-heap"]
default = []

