//! Interrupts
//!
//! The interrupt vector table is populated by `cortex-m-rt` crate with `DefaultHandler`s.
//! Board support crates should implement their `DefaultHandler` and pass an IRQ number to the IRQ dispatcher.

extern crate cortex_m_rt;
extern crate cortex_m;

::bobbin_mcu::irq_number!(IRQ_0, Irq0, 0);
::bobbin_mcu::irq_number!(IRQ_1, Irq1, 1);
::bobbin_mcu::irq_number!(IRQ_2, Irq2, 2);
::bobbin_mcu::irq_number!(IRQ_3, Irq3, 3);
::bobbin_mcu::irq_number!(IRQ_4, Irq4, 4);
::bobbin_mcu::irq_number!(IRQ_5, Irq5, 5);
::bobbin_mcu::irq_number!(IRQ_6, Irq6, 6);
::bobbin_mcu::irq_number!(IRQ_7, Irq7, 7);
::bobbin_mcu::irq_number!(IRQ_8, Irq8, 8);
::bobbin_mcu::irq_number!(IRQ_9, Irq9, 9);
::bobbin_mcu::irq_number!(IRQ_10, Irq10, 10);
::bobbin_mcu::irq_number!(IRQ_11, Irq11, 11);
::bobbin_mcu::irq_number!(IRQ_12, Irq12, 12);
::bobbin_mcu::irq_number!(IRQ_13, Irq13, 13);
::bobbin_mcu::irq_number!(IRQ_14, Irq14, 14);
::bobbin_mcu::irq_number!(IRQ_15, Irq15, 15);
::bobbin_mcu::irq_number!(IRQ_16, Irq16, 16);
::bobbin_mcu::irq_number!(IRQ_17, Irq17, 17);
::bobbin_mcu::irq_number!(IRQ_18, Irq18, 18);
::bobbin_mcu::irq_number!(IRQ_19, Irq19, 19);
::bobbin_mcu::irq_number!(IRQ_20, Irq20, 20);
::bobbin_mcu::irq_number!(IRQ_21, Irq21, 21);
::bobbin_mcu::irq_number!(IRQ_22, Irq22, 22);
::bobbin_mcu::irq_number!(IRQ_23, Irq23, 23);
::bobbin_mcu::irq_number!(IRQ_24, Irq24, 24);
::bobbin_mcu::irq_number!(IRQ_25, Irq25, 25);
::bobbin_mcu::irq_number!(IRQ_26, Irq26, 26);
::bobbin_mcu::irq_number!(IRQ_27, Irq27, 27);
::bobbin_mcu::irq_number!(IRQ_28, Irq28, 28);
::bobbin_mcu::irq_number!(IRQ_29, Irq29, 29);
::bobbin_mcu::irq_number!(IRQ_30, Irq30, 30);
::bobbin_mcu::irq_number!(IRQ_31, Irq31, 31);
::bobbin_mcu::irq_number!(IRQ_32, Irq32, 32);
::bobbin_mcu::irq_number!(IRQ_33, Irq33, 33);
::bobbin_mcu::irq_number!(IRQ_34, Irq34, 34);
::bobbin_mcu::irq_number!(IRQ_35, Irq35, 35);
::bobbin_mcu::irq_number!(IRQ_36, Irq36, 36);
::bobbin_mcu::irq_number!(IRQ_37, Irq37, 37);
::bobbin_mcu::irq_number!(IRQ_38, Irq38, 38);
::bobbin_mcu::irq_number!(IRQ_39, Irq39, 39);
::bobbin_mcu::irq_number!(IRQ_40, Irq40, 40);
::bobbin_mcu::irq_number!(IRQ_41, Irq41, 41);
::bobbin_mcu::irq_number!(IRQ_42, Irq42, 42);
::bobbin_mcu::irq_number!(IRQ_43, Irq43, 43);
::bobbin_mcu::irq_number!(IRQ_44, Irq44, 44);
::bobbin_mcu::irq_number!(IRQ_45, Irq45, 45);
::bobbin_mcu::irq_number!(IRQ_46, Irq46, 46);
::bobbin_mcu::irq_number!(IRQ_47, Irq47, 47);
::bobbin_mcu::irq_number!(IRQ_48, Irq48, 48);
::bobbin_mcu::irq_number!(IRQ_49, Irq49, 49);
::bobbin_mcu::irq_number!(IRQ_50, Irq50, 50);
::bobbin_mcu::irq_number!(IRQ_51, Irq51, 51);
::bobbin_mcu::irq_number!(IRQ_52, Irq52, 52);
::bobbin_mcu::irq_number!(IRQ_53, Irq53, 53);
::bobbin_mcu::irq_number!(IRQ_54, Irq54, 54);
::bobbin_mcu::irq_number!(IRQ_55, Irq55, 55);
::bobbin_mcu::irq_number!(IRQ_56, Irq56, 56);
::bobbin_mcu::irq_number!(IRQ_57, Irq57, 57);
::bobbin_mcu::irq_number!(IRQ_58, Irq58, 58);
::bobbin_mcu::irq_number!(IRQ_59, Irq59, 59);
::bobbin_mcu::irq_number!(IRQ_60, Irq60, 60);
::bobbin_mcu::irq_number!(IRQ_61, Irq61, 61);
::bobbin_mcu::irq_number!(IRQ_62, Irq62, 62);

::bobbin_mcu::irq_type!(IRQ_DMA, IrqDma);
::bobbin_mcu::irq_type!(IRQ_WWDG, IrqWwdg);
::bobbin_mcu::irq_type!(IRQ_I2C_EV, IrqI2cEv);
::bobbin_mcu::irq_type!(IRQ_I2C_ER, IrqI2cEr);
::bobbin_mcu::irq_type!(IRQ_ADC, IrqAdc);
::bobbin_mcu::irq_type!(IRQ_USART, IrqUsart);
::bobbin_mcu::irq_type!(IRQ_LPUART, IrqLpuart);
::bobbin_mcu::irq_type!(IRQ_SPI, IrqSpi);
::bobbin_mcu::irq_type!(IRQ_RTC, IrqRtc);
::bobbin_mcu::irq_type!(IRQ_EXTI, IrqExti);
::bobbin_mcu::irq_type!(IRQ_TIM, IrqTim);
::bobbin_mcu::irq_type!(IRQ_BRK, IrqBrk);
::bobbin_mcu::irq_type!(IRQ_UP, IrqUp);
::bobbin_mcu::irq_type!(IRQ_TRG_COM, IrqTrgCom);
::bobbin_mcu::irq_type!(IRQ_CC, IrqCc);
::bobbin_mcu::irq_type!(IRQ_USB, IrqUsb);
::bobbin_mcu::irq_type!(IRQ_RX, IrqRx);
::bobbin_mcu::irq_type!(IRQ_TX, IrqTx);
::bobbin_mcu::irq!(::dma::Dma1Ch1, ::bobbin_mcu::irq::IrqMain, Irq11);
::bobbin_mcu::irq!(::dma::Dma1Ch1, IrqDma, Irq11);
::bobbin_mcu::irq!(::dma::Dma1Ch2, ::bobbin_mcu::irq::IrqMain, Irq12);
::bobbin_mcu::irq!(::dma::Dma1Ch2, IrqDma, Irq12);
::bobbin_mcu::irq!(::dma::Dma1Ch3, ::bobbin_mcu::irq::IrqMain, Irq13);
::bobbin_mcu::irq!(::dma::Dma1Ch3, IrqDma, Irq13);
::bobbin_mcu::irq!(::dma::Dma1Ch4, ::bobbin_mcu::irq::IrqMain, Irq14);
::bobbin_mcu::irq!(::dma::Dma1Ch4, IrqDma, Irq14);
::bobbin_mcu::irq!(::dma::Dma1Ch5, ::bobbin_mcu::irq::IrqMain, Irq15);
::bobbin_mcu::irq!(::dma::Dma1Ch5, IrqDma, Irq15);
::bobbin_mcu::irq!(::dma::Dma1Ch6, ::bobbin_mcu::irq::IrqMain, Irq16);
::bobbin_mcu::irq!(::dma::Dma1Ch6, IrqDma, Irq16);
::bobbin_mcu::irq!(::dma::Dma1Ch7, ::bobbin_mcu::irq::IrqMain, Irq17);
::bobbin_mcu::irq!(::dma::Dma1Ch7, IrqDma, Irq17);
::bobbin_mcu::irq!(::dma::Dma2Ch1, ::bobbin_mcu::irq::IrqMain, Irq55);
::bobbin_mcu::irq!(::dma::Dma2Ch1, IrqDma, Irq55);
::bobbin_mcu::irq!(::dma::Dma2Ch2, ::bobbin_mcu::irq::IrqMain, Irq56);
::bobbin_mcu::irq!(::dma::Dma2Ch2, IrqDma, Irq56);
::bobbin_mcu::irq!(::dma::Dma2Ch3, ::bobbin_mcu::irq::IrqMain, Irq57);
::bobbin_mcu::irq!(::dma::Dma2Ch3, IrqDma, Irq57);
::bobbin_mcu::irq!(::dma::Dma2Ch4, ::bobbin_mcu::irq::IrqMain, Irq58);
::bobbin_mcu::irq!(::dma::Dma2Ch4, IrqDma, Irq58);
::bobbin_mcu::irq!(::dma::Dma2Ch5, ::bobbin_mcu::irq::IrqMain, Irq59);
::bobbin_mcu::irq!(::dma::Dma2Ch5, IrqDma, Irq59);
::bobbin_mcu::irq!(::dma::Dma2Ch6, ::bobbin_mcu::irq::IrqMain, Irq60);
::bobbin_mcu::irq!(::dma::Dma2Ch6, IrqDma, Irq60);
::bobbin_mcu::irq!(::dma::Dma2Ch7, ::bobbin_mcu::irq::IrqMain, Irq61);
::bobbin_mcu::irq!(::dma::Dma2Ch7, IrqDma, Irq61);
::bobbin_mcu::irq!(::wwdg::Wwdg, ::bobbin_mcu::irq::IrqMain, Irq0);
::bobbin_mcu::irq!(::i2c::I2c1, ::bobbin_mcu::irq::IrqMain, Irq30);
::bobbin_mcu::irq!(::i2c::I2c3, ::bobbin_mcu::irq::IrqMain, Irq32);
::bobbin_mcu::irq!(::rng::Rng, ::bobbin_mcu::irq::IrqMain, Irq53);
::bobbin_mcu::irq!(::rng::Rng, IrqRng, Irq53);
::bobbin_mcu::irq_type!(IRQ_RNG, IrqRng);
::bobbin_mcu::irq!(::adc::Adc1, ::bobbin_mcu::irq::IrqMain, Irq18);
::bobbin_mcu::irq!(::lptim::Lptim1, ::bobbin_mcu::irq::IrqMain, Irq47);
::bobbin_mcu::irq!(::lptim::Lptim1, IrqLptim, Irq47);
::bobbin_mcu::irq!(::lptim::Lptim2, ::bobbin_mcu::irq::IrqMain, Irq48);
::bobbin_mcu::irq!(::lptim::Lptim2, IrqLptim, Irq48);
::bobbin_mcu::irq_type!(IRQ_LPTIM, IrqLptim);
::bobbin_mcu::irq!(::usart::Usart1, ::bobbin_mcu::irq::IrqMain, Irq36);
::bobbin_mcu::irq!(::lpuart::Lpuart1, ::bobbin_mcu::irq::IrqMain, Irq37);
::bobbin_mcu::irq!(::spi::Spi1, ::bobbin_mcu::irq::IrqMain, Irq34);
::bobbin_mcu::irq!(::spi::Spi2, ::bobbin_mcu::irq::IrqMain, Irq35);
::bobbin_mcu::irq!(::rtc::Rtc, ::bobbin_mcu::irq::IrqMain, Irq41);
::bobbin_mcu::irq!(::exti::ExtiLine0, ::bobbin_mcu::irq::IrqMain, Irq6);
::bobbin_mcu::irq!(::exti::ExtiLine0, IrqExti, Irq6);
::bobbin_mcu::irq!(::exti::ExtiLine1, ::bobbin_mcu::irq::IrqMain, Irq7);
::bobbin_mcu::irq!(::exti::ExtiLine1, IrqExti, Irq7);
::bobbin_mcu::irq!(::exti::ExtiLine2, ::bobbin_mcu::irq::IrqMain, Irq8);
::bobbin_mcu::irq!(::exti::ExtiLine2, IrqExti, Irq8);
::bobbin_mcu::irq!(::exti::ExtiLine3, ::bobbin_mcu::irq::IrqMain, Irq9);
::bobbin_mcu::irq!(::exti::ExtiLine3, IrqExti, Irq9);
::bobbin_mcu::irq!(::exti::ExtiLine4, ::bobbin_mcu::irq::IrqMain, Irq10);
::bobbin_mcu::irq!(::exti::ExtiLine4, IrqExti, Irq10);
::bobbin_mcu::irq!(::exti::ExtiLine5, ::bobbin_mcu::irq::IrqMain, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine5, IrqExti, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine6, ::bobbin_mcu::irq::IrqMain, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine6, IrqExti, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine7, ::bobbin_mcu::irq::IrqMain, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine7, IrqExti, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine8, ::bobbin_mcu::irq::IrqMain, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine8, IrqExti, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine9, ::bobbin_mcu::irq::IrqMain, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine9, IrqExti, Irq23);
::bobbin_mcu::irq!(::exti::ExtiLine10, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine10, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine11, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine11, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine12, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine12, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine13, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine13, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine14, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine14, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine15, ::bobbin_mcu::irq::IrqMain, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine15, IrqExti, Irq40);
::bobbin_mcu::irq!(::exti::ExtiLine16, ::bobbin_mcu::irq::IrqMain, Irq1);
::bobbin_mcu::irq!(::exti::ExtiLine16, IrqExti, Irq1);
::bobbin_mcu::irq!(::exti::ExtiLine40, ::bobbin_mcu::irq::IrqMain, Irq21);
::bobbin_mcu::irq!(::exti::ExtiLine40, IrqExti, Irq21);
::bobbin_mcu::irq!(::dmamux::Dmamux1, ::bobbin_mcu::irq::IrqMain, Irq62);
::bobbin_mcu::irq!(::dmamux::Dmamux1, IrqDmamux, Irq62);
::bobbin_mcu::irq_type!(IRQ_DMAMUX, IrqDmamux);
::bobbin_mcu::irq!(::lcd::Lcd, ::bobbin_mcu::irq::IrqMain, Irq49);
::bobbin_mcu::irq!(::lcd::Lcd, IrqLcd, Irq49);
::bobbin_mcu::irq_type!(IRQ_LCD, IrqLcd);
::bobbin_mcu::irq!(::tsc::Tsc, ::bobbin_mcu::irq::IrqMain, Irq39);
::bobbin_mcu::irq!(::tsc::Tsc, IrqTsc, Irq39);
::bobbin_mcu::irq_type!(IRQ_TSC, IrqTsc);
::bobbin_mcu::irq!(::comp::Comp, ::bobbin_mcu::irq::IrqMain, Irq22);
::bobbin_mcu::irq!(::comp::Comp, IrqComp, Irq22);
::bobbin_mcu::irq_type!(IRQ_COMP, IrqComp);
::bobbin_mcu::irq!(::quadspi::Quadspi, ::bobbin_mcu::irq::IrqMain, Irq50);
::bobbin_mcu::irq!(::quadspi::Quadspi, IrqQuadspi, Irq50);
::bobbin_mcu::irq_type!(IRQ_QUADSPI, IrqQuadspi);
::bobbin_mcu::irq!(::aes1::Aes1, ::bobbin_mcu::irq::IrqMain, Irq51);
::bobbin_mcu::irq!(::aes1::Aes1, IrqAes1, Irq51);
::bobbin_mcu::irq!(::aes1::Aes2, ::bobbin_mcu::irq::IrqMain, Irq52);
::bobbin_mcu::irq!(::aes1::Aes2, IrqAes1, Irq52);
::bobbin_mcu::irq_type!(IRQ_AES1, IrqAes1);
::bobbin_mcu::irq!(::hardware_semaphore::Hsem, ::bobbin_mcu::irq::IrqMain, Irq46);
::bobbin_mcu::irq!(::hardware_semaphore::Hsem, IrqHardwareSemaphore, Irq46);
::bobbin_mcu::irq_type!(IRQ_HARDWARE_SEMAPHORE, IrqHardwareSemaphore);
::bobbin_mcu::irq!(::sai::Sai1, ::bobbin_mcu::irq::IrqMain, Irq38);
::bobbin_mcu::irq!(::sai::Sai1, IrqSai, Irq38);
::bobbin_mcu::irq_type!(IRQ_SAI, IrqSai);
::bobbin_mcu::irq!(::tim2::Tim2, ::bobbin_mcu::irq::IrqMain, Irq28);
::bobbin_mcu::irq!(::tim1::Tim1, ::bobbin_mcu::irq::IrqMain, Irq24);
::bobbin_mcu::irq!(::usb::Usb, ::bobbin_mcu::irq::IrqMain, Irq19);
::bobbin_mcu::irq!(::crs::Crs, ::bobbin_mcu::irq::IrqMain, Irq42);
::bobbin_mcu::irq!(::crs::Crs, IrqCrs, Irq42);
::bobbin_mcu::irq_type!(IRQ_CRS, IrqCrs);
::bobbin_mcu::irq!(::pka::Pka, ::bobbin_mcu::irq::IrqMain, Irq29);
::bobbin_mcu::irq!(::pka::Pka, IrqPka, Irq29);
::bobbin_mcu::irq_type!(IRQ_PKA, IrqPka);
::bobbin_mcu::irq!(::ipcc::Ipcc, ::bobbin_mcu::irq::IrqMain, Irq44);
::bobbin_mcu::irq!(::flash::Flash, ::bobbin_mcu::irq::IrqMain, Irq4);
::bobbin_mcu::irq!(::pwr::Pwr, ::bobbin_mcu::irq::IrqMain, Irq43);
::bobbin_mcu::irq!(::rcc::Rcc, ::bobbin_mcu::irq::IrqMain, Irq5);
