pub use super::gpio::*;

::bobbin_mcu::pin!(PA0, Pa0, pa0, GPIOA, Gpioa, PA0_PIN, GpioPin, GPIOA_PERIPH, PA0_OWNED, PA0_REF_COUNT, 0);
::bobbin_mcu::pin!(PA1, Pa1, pa1, GPIOA, Gpioa, PA1_PIN, GpioPin, GPIOA_PERIPH, PA1_OWNED, PA1_REF_COUNT, 1);
   ::bobbin_mcu::pin_source!(Pa1, super::i2c::I2c1, super::sig::SigI2cSmba, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pa1, super::spi::Spi1, super::sig::SigSpiSck, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PA2, Pa2, pa2, GPIOA, Gpioa, PA2_PIN, GpioPin, GPIOA_PERIPH, PA2_OWNED, PA2_REF_COUNT, 2);
   ::bobbin_mcu::pin_source!(Pa2, super::lpuart::Lpuart1, super::sig::SigTx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PA3, Pa3, pa3, GPIOA, Gpioa, PA3_PIN, GpioPin, GPIOA_PERIPH, PA3_OWNED, PA3_REF_COUNT, 3);
   ::bobbin_mcu::pin_source!(Pa3, super::lpuart::Lpuart1, super::sig::SigRx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PA4, Pa4, pa4, GPIOA, Gpioa, PA4_PIN, GpioPin, GPIOA_PERIPH, PA4_OWNED, PA4_REF_COUNT, 4);
   ::bobbin_mcu::pin_source!(Pa4, super::spi::Spi1, super::sig::SigSpiNss, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PA5, Pa5, pa5, GPIOA, Gpioa, PA5_PIN, GpioPin, GPIOA_PERIPH, PA5_OWNED, PA5_REF_COUNT, 5);
   ::bobbin_mcu::pin_source!(Pa5, super::spi::Spi1, super::sig::SigSpiSck, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PA6, Pa6, pa6, GPIOA, Gpioa, PA6_PIN, GpioPin, GPIOA_PERIPH, PA6_OWNED, PA6_REF_COUNT, 6);
   ::bobbin_mcu::pin_source!(Pa6, super::spi::Spi1, super::sig::SigSpiMiso, ::bobbin_bits::U4::B0101);
   ::bobbin_mcu::pin_source!(Pa6, super::lpuart::Lpuart1, super::sig::SigCts, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PA7, Pa7, pa7, GPIOA, Gpioa, PA7_PIN, GpioPin, GPIOA_PERIPH, PA7_OWNED, PA7_REF_COUNT, 7);
   ::bobbin_mcu::pin_source!(Pa7, super::spi::Spi1, super::sig::SigSpiMosi, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PA8, Pa8, pa8, GPIOA, Gpioa, PA8_PIN, GpioPin, GPIOA_PERIPH, PA8_OWNED, PA8_REF_COUNT, 8);
   ::bobbin_mcu::pin_source!(Pa8, super::usart::Usart1, super::sig::SigCk, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PA9, Pa9, pa9, GPIOA, Gpioa, PA9_PIN, GpioPin, GPIOA_PERIPH, PA9_OWNED, PA9_REF_COUNT, 9);
   ::bobbin_mcu::pin_source!(Pa9, super::i2c::I2c1, super::sig::SigI2cScl, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pa9, super::usart::Usart1, super::sig::SigTx, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PA10, Pa10, pa10, GPIOA, Gpioa, PA10_PIN, GpioPin, GPIOA_PERIPH, PA10_OWNED, PA10_REF_COUNT, 10);
   ::bobbin_mcu::pin_source!(Pa10, super::i2c::I2c1, super::sig::SigI2cSda, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pa10, super::usart::Usart1, super::sig::SigRx, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PA11, Pa11, pa11, GPIOA, Gpioa, PA11_PIN, GpioPin, GPIOA_PERIPH, PA11_OWNED, PA11_REF_COUNT, 11);
   ::bobbin_mcu::pin_source!(Pa11, super::spi::Spi1, super::sig::SigSpiMiso, ::bobbin_bits::U4::B0101);
   ::bobbin_mcu::pin_source!(Pa11, super::usart::Usart1, super::sig::SigCts, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PA12, Pa12, pa12, GPIOA, Gpioa, PA12_PIN, GpioPin, GPIOA_PERIPH, PA12_OWNED, PA12_REF_COUNT, 12);
   ::bobbin_mcu::pin_source!(Pa12, super::spi::Spi1, super::sig::SigSpiMosi, ::bobbin_bits::U4::B0101);
   ::bobbin_mcu::pin_source!(Pa12, super::lpuart::Lpuart1, super::sig::SigRx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PA13, Pa13, pa13, GPIOA, Gpioa, PA13_PIN, GpioPin, GPIOA_PERIPH, PA13_OWNED, PA13_REF_COUNT, 13);
::bobbin_mcu::pin!(PA14, Pa14, pa14, GPIOA, Gpioa, PA14_PIN, GpioPin, GPIOA_PERIPH, PA14_OWNED, PA14_REF_COUNT, 14);
   ::bobbin_mcu::pin_source!(Pa14, super::i2c::I2c1, super::sig::SigI2cSmba, ::bobbin_bits::U4::B0100);
::bobbin_mcu::pin!(PA15, Pa15, pa15, GPIOA, Gpioa, PA15_PIN, GpioPin, GPIOA_PERIPH, PA15_OWNED, PA15_REF_COUNT, 15);
   ::bobbin_mcu::pin_source!(Pa15, super::spi::Spi1, super::sig::SigSpiNss, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PB0, Pb0, pb0, GPIOB, Gpiob, PB0_PIN, GpioPin, GPIOB_PERIPH, PB0_OWNED, PB0_REF_COUNT, 0);
::bobbin_mcu::pin!(PB1, Pb1, pb1, GPIOB, Gpiob, PB1_PIN, GpioPin, GPIOB_PERIPH, PB1_OWNED, PB1_REF_COUNT, 1);
::bobbin_mcu::pin!(PB2, Pb2, pb2, GPIOB, Gpiob, PB2_PIN, GpioPin, GPIOB_PERIPH, PB2_OWNED, PB2_REF_COUNT, 2);
   ::bobbin_mcu::pin_source!(Pb2, super::spi::Spi1, super::sig::SigSpiNss, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PB3, Pb3, pb3, GPIOB, Gpiob, PB3_PIN, GpioPin, GPIOB_PERIPH, PB3_OWNED, PB3_REF_COUNT, 3);
   ::bobbin_mcu::pin_source!(Pb3, super::spi::Spi1, super::sig::SigSpiSck, ::bobbin_bits::U4::B0101);
::bobbin_mcu::pin!(PB4, Pb4, pb4, GPIOB, Gpiob, PB4_PIN, GpioPin, GPIOB_PERIPH, PB4_OWNED, PB4_REF_COUNT, 4);
   ::bobbin_mcu::pin_source!(Pb4, super::spi::Spi1, super::sig::SigSpiMiso, ::bobbin_bits::U4::B0101);
   ::bobbin_mcu::pin_source!(Pb4, super::usart::Usart1, super::sig::SigCts, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PB5, Pb5, pb5, GPIOB, Gpiob, PB5_PIN, GpioPin, GPIOB_PERIPH, PB5_OWNED, PB5_REF_COUNT, 5);
   ::bobbin_mcu::pin_source!(Pb5, super::i2c::I2c1, super::sig::SigI2cSmba, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pb5, super::spi::Spi1, super::sig::SigSpiMosi, ::bobbin_bits::U4::B0101);
   ::bobbin_mcu::pin_source!(Pb5, super::usart::Usart1, super::sig::SigCk, ::bobbin_bits::U4::B0111);
   ::bobbin_mcu::pin_source!(Pb5, super::lpuart::Lpuart1, super::sig::SigTx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PB6, Pb6, pb6, GPIOB, Gpiob, PB6_PIN, GpioPin, GPIOB_PERIPH, PB6_OWNED, PB6_REF_COUNT, 6);
   ::bobbin_mcu::pin_source!(Pb6, super::i2c::I2c1, super::sig::SigI2cScl, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pb6, super::usart::Usart1, super::sig::SigTx, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PB7, Pb7, pb7, GPIOB, Gpiob, PB7_PIN, GpioPin, GPIOB_PERIPH, PB7_OWNED, PB7_REF_COUNT, 7);
   ::bobbin_mcu::pin_source!(Pb7, super::i2c::I2c1, super::sig::SigI2cSda, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pb7, super::usart::Usart1, super::sig::SigRx, ::bobbin_bits::U4::B0111);
::bobbin_mcu::pin!(PB8, Pb8, pb8, GPIOB, Gpiob, PB8_PIN, GpioPin, GPIOB_PERIPH, PB8_OWNED, PB8_REF_COUNT, 8);
   ::bobbin_mcu::pin_source!(Pb8, super::i2c::I2c1, super::sig::SigI2cScl, ::bobbin_bits::U4::B0100);
::bobbin_mcu::pin!(PB9, Pb9, pb9, GPIOB, Gpiob, PB9_PIN, GpioPin, GPIOB_PERIPH, PB9_OWNED, PB9_REF_COUNT, 9);
   ::bobbin_mcu::pin_source!(Pb9, super::i2c::I2c1, super::sig::SigI2cSda, ::bobbin_bits::U4::B0100);
::bobbin_mcu::pin!(PB10, Pb10, pb10, GPIOB, Gpiob, PB10_PIN, GpioPin, GPIOB_PERIPH, PB10_OWNED, PB10_REF_COUNT, 10);
   ::bobbin_mcu::pin_source!(Pb10, super::lpuart::Lpuart1, super::sig::SigRx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PB11, Pb11, pb11, GPIOB, Gpiob, PB11_PIN, GpioPin, GPIOB_PERIPH, PB11_OWNED, PB11_REF_COUNT, 11);
   ::bobbin_mcu::pin_source!(Pb11, super::i2c::I2c1, super::sig::SigI2cSda, ::bobbin_bits::U4::B0100);
   ::bobbin_mcu::pin_source!(Pb11, super::lpuart::Lpuart1, super::sig::SigTx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PB12, Pb12, pb12, GPIOB, Gpiob, PB12_PIN, GpioPin, GPIOB_PERIPH, PB12_OWNED, PB12_REF_COUNT, 12);
::bobbin_mcu::pin!(PB13, Pb13, pb13, GPIOB, Gpiob, PB13_PIN, GpioPin, GPIOB_PERIPH, PB13_OWNED, PB13_REF_COUNT, 13);
   ::bobbin_mcu::pin_source!(Pb13, super::lpuart::Lpuart1, super::sig::SigCts, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PB14, Pb14, pb14, GPIOB, Gpiob, PB14_PIN, GpioPin, GPIOB_PERIPH, PB14_OWNED, PB14_REF_COUNT, 14);
::bobbin_mcu::pin!(PB15, Pb15, pb15, GPIOB, Gpiob, PB15_PIN, GpioPin, GPIOB_PERIPH, PB15_OWNED, PB15_REF_COUNT, 15);
::bobbin_mcu::pin!(PC0, Pc0, pc0, GPIOC, Gpioc, PC0_PIN, GpioPin, GPIOC_PERIPH, PC0_OWNED, PC0_REF_COUNT, 0);
   ::bobbin_mcu::pin_source!(Pc0, super::lpuart::Lpuart1, super::sig::SigRx, ::bobbin_bits::U4::B0110);
   ::bobbin_mcu::pin_source!(Pc0, super::lpuart::Lpuart1, super::sig::SigTx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PC1, Pc1, pc1, GPIOC, Gpioc, PC1_PIN, GpioPin, GPIOC_PERIPH, PC1_OWNED, PC1_REF_COUNT, 1);
   ::bobbin_mcu::pin_source!(Pc1, super::lpuart::Lpuart1, super::sig::SigTx, ::bobbin_bits::U4::B1000);
::bobbin_mcu::pin!(PC2, Pc2, pc2, GPIOC, Gpioc, PC2_PIN, GpioPin, GPIOC_PERIPH, PC2_OWNED, PC2_REF_COUNT, 2);
::bobbin_mcu::pin!(PC3, Pc3, pc3, GPIOC, Gpioc, PC3_PIN, GpioPin, GPIOC_PERIPH, PC3_OWNED, PC3_REF_COUNT, 3);
::bobbin_mcu::pin!(PC4, Pc4, pc4, GPIOC, Gpioc, PC4_PIN, GpioPin, GPIOC_PERIPH, PC4_OWNED, PC4_REF_COUNT, 4);
::bobbin_mcu::pin!(PC5, Pc5, pc5, GPIOC, Gpioc, PC5_PIN, GpioPin, GPIOC_PERIPH, PC5_OWNED, PC5_REF_COUNT, 5);
::bobbin_mcu::pin!(PC6, Pc6, pc6, GPIOC, Gpioc, PC6_PIN, GpioPin, GPIOC_PERIPH, PC6_OWNED, PC6_REF_COUNT, 6);
::bobbin_mcu::pin!(PC7, Pc7, pc7, GPIOC, Gpioc, PC7_PIN, GpioPin, GPIOC_PERIPH, PC7_OWNED, PC7_REF_COUNT, 7);
::bobbin_mcu::pin!(PC8, Pc8, pc8, GPIOC, Gpioc, PC8_PIN, GpioPin, GPIOC_PERIPH, PC8_OWNED, PC8_REF_COUNT, 8);
::bobbin_mcu::pin!(PC9, Pc9, pc9, GPIOC, Gpioc, PC9_PIN, GpioPin, GPIOC_PERIPH, PC9_OWNED, PC9_REF_COUNT, 9);
::bobbin_mcu::pin!(PC10, Pc10, pc10, GPIOC, Gpioc, PC10_PIN, GpioPin, GPIOC_PERIPH, PC10_OWNED, PC10_REF_COUNT, 10);
::bobbin_mcu::pin!(PC11, Pc11, pc11, GPIOC, Gpioc, PC11_PIN, GpioPin, GPIOC_PERIPH, PC11_OWNED, PC11_REF_COUNT, 11);
::bobbin_mcu::pin!(PC12, Pc12, pc12, GPIOC, Gpioc, PC12_PIN, GpioPin, GPIOC_PERIPH, PC12_OWNED, PC12_REF_COUNT, 12);
::bobbin_mcu::pin!(PC13, Pc13, pc13, GPIOC, Gpioc, PC13_PIN, GpioPin, GPIOC_PERIPH, PC13_OWNED, PC13_REF_COUNT, 13);
::bobbin_mcu::pin!(PC14, Pc14, pc14, GPIOC, Gpioc, PC14_PIN, GpioPin, GPIOC_PERIPH, PC14_OWNED, PC14_REF_COUNT, 14);
::bobbin_mcu::pin!(PC15, Pc15, pc15, GPIOC, Gpioc, PC15_PIN, GpioPin, GPIOC_PERIPH, PC15_OWNED, PC15_REF_COUNT, 15);
::bobbin_mcu::pin!(PD0, Pd0, pd0, GPIOD, Gpiod, PD0_PIN, GpioPin, GPIOD_PERIPH, PD0_OWNED, PD0_REF_COUNT, 0);
::bobbin_mcu::pin!(PD1, Pd1, pd1, GPIOD, Gpiod, PD1_PIN, GpioPin, GPIOD_PERIPH, PD1_OWNED, PD1_REF_COUNT, 1);
::bobbin_mcu::pin!(PD2, Pd2, pd2, GPIOD, Gpiod, PD2_PIN, GpioPin, GPIOD_PERIPH, PD2_OWNED, PD2_REF_COUNT, 2);
::bobbin_mcu::pin!(PD3, Pd3, pd3, GPIOD, Gpiod, PD3_PIN, GpioPin, GPIOD_PERIPH, PD3_OWNED, PD3_REF_COUNT, 3);
::bobbin_mcu::pin!(PD4, Pd4, pd4, GPIOD, Gpiod, PD4_PIN, GpioPin, GPIOD_PERIPH, PD4_OWNED, PD4_REF_COUNT, 4);
::bobbin_mcu::pin!(PD5, Pd5, pd5, GPIOD, Gpiod, PD5_PIN, GpioPin, GPIOD_PERIPH, PD5_OWNED, PD5_REF_COUNT, 5);
::bobbin_mcu::pin!(PD6, Pd6, pd6, GPIOD, Gpiod, PD6_PIN, GpioPin, GPIOD_PERIPH, PD6_OWNED, PD6_REF_COUNT, 6);
::bobbin_mcu::pin!(PD7, Pd7, pd7, GPIOD, Gpiod, PD7_PIN, GpioPin, GPIOD_PERIPH, PD7_OWNED, PD7_REF_COUNT, 7);
::bobbin_mcu::pin!(PD8, Pd8, pd8, GPIOD, Gpiod, PD8_PIN, GpioPin, GPIOD_PERIPH, PD8_OWNED, PD8_REF_COUNT, 8);
::bobbin_mcu::pin!(PD9, Pd9, pd9, GPIOD, Gpiod, PD9_PIN, GpioPin, GPIOD_PERIPH, PD9_OWNED, PD9_REF_COUNT, 9);
::bobbin_mcu::pin!(PD10, Pd10, pd10, GPIOD, Gpiod, PD10_PIN, GpioPin, GPIOD_PERIPH, PD10_OWNED, PD10_REF_COUNT, 10);
::bobbin_mcu::pin!(PD11, Pd11, pd11, GPIOD, Gpiod, PD11_PIN, GpioPin, GPIOD_PERIPH, PD11_OWNED, PD11_REF_COUNT, 11);
::bobbin_mcu::pin!(PD12, Pd12, pd12, GPIOD, Gpiod, PD12_PIN, GpioPin, GPIOD_PERIPH, PD12_OWNED, PD12_REF_COUNT, 12);
::bobbin_mcu::pin!(PD13, Pd13, pd13, GPIOD, Gpiod, PD13_PIN, GpioPin, GPIOD_PERIPH, PD13_OWNED, PD13_REF_COUNT, 13);
::bobbin_mcu::pin!(PD14, Pd14, pd14, GPIOD, Gpiod, PD14_PIN, GpioPin, GPIOD_PERIPH, PD14_OWNED, PD14_REF_COUNT, 14);
::bobbin_mcu::pin!(PD15, Pd15, pd15, GPIOD, Gpiod, PD15_PIN, GpioPin, GPIOD_PERIPH, PD15_OWNED, PD15_REF_COUNT, 15);
::bobbin_mcu::pin!(PE0, Pe0, pe0, GPIOE, Gpioe, PE0_PIN, GpioPin, GPIOE_PERIPH, PE0_OWNED, PE0_REF_COUNT, 0);
::bobbin_mcu::pin!(PE1, Pe1, pe1, GPIOE, Gpioe, PE1_PIN, GpioPin, GPIOE_PERIPH, PE1_OWNED, PE1_REF_COUNT, 0);
::bobbin_mcu::pin!(PE2, Pe2, pe2, GPIOE, Gpioe, PE2_PIN, GpioPin, GPIOE_PERIPH, PE2_OWNED, PE2_REF_COUNT, 0);
::bobbin_mcu::pin!(PE3, Pe3, pe3, GPIOE, Gpioe, PE3_PIN, GpioPin, GPIOE_PERIPH, PE3_OWNED, PE3_REF_COUNT, 0);
::bobbin_mcu::pin!(PE4, Pe4, pe4, GPIOE, Gpioe, PE4_PIN, GpioPin, GPIOE_PERIPH, PE4_OWNED, PE4_REF_COUNT, 0);
::bobbin_mcu::pin!(PH0, Ph0, ph0, GPIOH, Gpioh, PH0_PIN, GpioPin, GPIOH_PERIPH, PH0_OWNED, PH0_REF_COUNT, 0);
::bobbin_mcu::pin!(PH1, Ph1, ph1, GPIOH, Gpioh, PH1_PIN, GpioPin, GPIOH_PERIPH, PH1_OWNED, PH1_REF_COUNT, 1);
::bobbin_mcu::pin!(PH3, Ph3, ph3, GPIOH, Gpioh, PH3_PIN, GpioPin, GPIOH_PERIPH, PH3_OWNED, PH3_REF_COUNT, 3);
