//! Signals

pub trait Signal<T> {}


pub struct Slscl {}
pub struct Slsck {}
pub struct Clkout {}
pub struct Gpio0 {}
pub struct Mxscklb {}
pub struct M2sck {}
pub struct Mxscllb {}
pub struct M2scl {}
pub struct Slsda {}
pub struct Slmiso {}
pub struct Uart0tx {}
pub struct Gpio1 {}
pub struct Mxmisolb {}
pub struct M2mis0 {}
pub struct Mxsdalb {}
pub struct M2sda {}
pub struct Slwir3 {}
pub struct Slmosi {}
pub struct Uart0rx {}
pub struct Gpio2 {}
pub struct Mxmosilb {}
pub struct M2mosi {}
pub struct Mxwir3lb {}
pub struct M2wir3 {}
pub struct Ua0rts {}
pub struct Slnce {}
pub struct M1nce4 {}
pub struct Gpio3 {}
pub struct Mxncelb {}
pub struct M2nce0 {}
pub struct Trig1 {}
pub struct I2sWclk {}
pub struct Ua0cts {}
pub struct Slint {}
pub struct M0nce5 {}
pub struct Gpio4 {}
pub struct Slintgp {}
pub struct M2nce5 {}
pub struct Xt32khz {}
pub struct M0scl {}
pub struct M0sck {}
pub struct Gpio5 {}
pub struct M0scklb {}
pub struct M0scllb {}
pub struct M1nce2 {}
pub struct M0sda {}
pub struct M0miso {}
pub struct Gpio6 {}
pub struct Slmisolb {}
pub struct M1nce0 {}
pub struct Slsdalb {}
pub struct I2sDat {}
pub struct M0wir3 {}
pub struct M0mosi {}
pub struct Gpio7 {}
pub struct Trig0 {}
pub struct Slwir3lb {}
pub struct M1nce1 {}
pub struct M1scl {}
pub struct M1sck {}
pub struct M0nce4 {}
pub struct Gpio8 {}
pub struct M2nce4 {}
pub struct M1scklb {}
pub struct Uart1tx {}
pub struct M1scllb {}
pub struct M1sda {}
pub struct M1miso {}
pub struct Gpio9 {}
pub struct M4nce5 {}
pub struct Uart1rx {}
pub struct M1wir3 {}
pub struct M1mosi {}
pub struct M0nce6 {}
pub struct Gpio10 {}
pub struct M2nce6 {}
pub struct Ua1rts {}
pub struct M4nce4 {}
pub struct Adcse2 {}
pub struct M0nce0 {}
pub struct Gpio11 {}
pub struct M2nce7 {}
pub struct Ua1cts {}
pub struct PdmData {}
pub struct Adcd0nse9 {}
pub struct Tcta0 {}
pub struct Gpio12 {}
pub struct PdmClk {}
pub struct Adcd0pse8 {}
pub struct Tctb0 {}
pub struct Gpio13 {}
pub struct M2nce3 {}
pub struct Adcd1p {}
pub struct Gpio14 {}
pub struct M2nce1 {}
pub struct Swdck {}
pub struct Adcd1n {}
pub struct M1nce3 {}
pub struct Gpio15 {}
pub struct M2nce2 {}
pub struct Swdio {}
pub struct Swo {}
pub struct Adcse0 {}
pub struct Gpio16 {}
pub struct Cmpin0 {}
pub struct Cmprf1 {}
pub struct M0nce1 {}
pub struct Gpio17 {}
pub struct M4nce3 {}
pub struct Cmpin1 {}
pub struct M0nce2 {}
pub struct Tcta1 {}
pub struct Gpio18 {}
pub struct M4nce1 {}
pub struct Cmprf0 {}
pub struct M0nce3 {}
pub struct Tctb1 {}
pub struct Gpio19 {}
pub struct I2sBclk {}
pub struct M1nce5 {}
pub struct Tcta2 {}
pub struct Gpio20 {}
pub struct M1nce6 {}
pub struct Tctb2 {}
pub struct Gpio21 {}
pub struct M1nce7 {}
pub struct Tcta3 {}
pub struct Gpio22 {}
pub struct Tctb3 {}
pub struct Gpio23 {}
pub struct Cmpout {}
pub struct Gpio24 {}
pub struct M5nce0 {}
pub struct Gpio25 {}
pub struct M2miso {}
pub struct Gpio26 {}
pub struct M5nce1 {}
pub struct M3nce0 {}
pub struct Gpio27 {}
pub struct M2scklb {}
pub struct M2scllb {}
pub struct Gpio28 {}
pub struct M5nce3 {}
pub struct Adcse1 {}
pub struct Gpio29 {}
pub struct M4nce0 {}
pub struct Gpio30 {}
pub struct Adcse3 {}
pub struct Gpio31 {}
pub struct Adcse4 {}
pub struct Gpio32 {}
pub struct Adcse5 {}
pub struct Gpio33 {}
pub struct M3nce7 {}
pub struct Adcse6 {}
pub struct M0nce7 {}
pub struct Gpio34 {}
pub struct Cmprf2 {}
pub struct M3nce1 {}
pub struct M5nce2 {}
pub struct Adcse7 {}
pub struct Gpio35 {}
pub struct M4nce6 {}
pub struct M3nce2 {}
pub struct Gpio36 {}
pub struct M3nce3 {}
pub struct Trig2 {}
pub struct Gpio37 {}
pub struct M3nce4 {}
pub struct Trig3 {}
pub struct Gpio38 {}
pub struct M3wir3 {}
pub struct M3mosi {}
pub struct M4nce7 {}
pub struct Gpio39 {}
pub struct M4scl {}
pub struct M4sck {}
pub struct M4scklb {}
pub struct M4scllb {}
pub struct Gpio40 {}
pub struct M4sda {}
pub struct M4miso {}
pub struct Gpio41 {}
pub struct M3nce5 {}
pub struct M5nce7 {}
pub struct M4nce2 {}
pub struct Gpio42 {}
pub struct M3scl {}
pub struct M3sck {}
pub struct M3scklb {}
pub struct M3scllb {}
pub struct Gpio43 {}
pub struct M3sda {}
pub struct M3miso {}
pub struct Gpio44 {}
pub struct M4wir3 {}
pub struct M4mosi {}
pub struct M5nce6 {}
pub struct Gpio45 {}
pub struct M3nce6 {}
pub struct M5nce5 {}
pub struct Gpio46 {}
pub struct M5nce4 {}
pub struct Gpio47 {}
pub struct M5wir3 {}
pub struct M5mosi {}
pub struct Gpio48 {}
pub struct M5scl {}
pub struct M5sck {}
pub struct M5scklb {}
pub struct M5scllb {}
pub struct Gpio49 {}
pub struct M5sda {}
pub struct M5miso {}
