//! Signals

pub trait Signal<T> {}

pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Cts {}
pub trait SignalCts<T> {}
pub trait Rts {}
pub trait SignalRts<T> {}
pub trait Ck {}
pub trait SignalCk<T> {}
pub trait Adc {}
pub trait SignalAdc<T> {}
pub trait Tim {}
pub trait SignalTim<T> {}
pub trait Timn {}
pub trait SignalTimn<T> {}

pub struct Usart1Tx {}
pub struct Usart1Rx {}
pub struct Usart1Cts {}
pub struct Usart1Rts {}
pub struct Usart1Ck {}
pub struct Usart2Tx {}
pub struct Usart2Rx {}
pub struct Usart2Cts {}
pub struct Usart2Rts {}
pub struct Usart2Ck {}
pub struct Usart3Tx {}
pub struct Usart3Rx {}
pub struct Usart3Cts {}
pub struct Usart3Rts {}
pub struct Usart3Ck {}
pub struct Uart4Tx {}
pub struct Uart4Rx {}
pub struct Uart4Cts {}
pub struct Uart4Rts {}
pub struct Uart4Ck {}
pub struct Uart5Tx {}
pub struct Uart5Rx {}
pub struct Uart5Cts {}
pub struct Uart5Rts {}
pub struct Uart5Ck {}
pub struct Adc1In1 {}
pub struct Adc1In2 {}
pub struct Adc1In3 {}
pub struct Adc1In4 {}
pub struct Adc1In5 {}
pub struct Adc1In6 {}
pub struct Adc1In7 {}
pub struct Adc1In8 {}
pub struct Adc1In9 {}
pub struct Adc1In10 {}
pub struct Adc1In11 {}
pub struct Adc1In12 {}
pub struct Adc1In13 {}
pub struct Adc1In14 {}
pub struct Adc1In15 {}
pub struct Tim2Ch1 {}
pub struct Tim2Ch2 {}
pub struct Tim2Ch3 {}
pub struct Tim2Ch4 {}
pub struct Tim3Ch1 {}
pub struct Tim3Ch2 {}
pub struct Tim3Ch3 {}
pub struct Tim3Ch4 {}
pub struct Tim4Ch1 {}
pub struct Tim4Ch2 {}
pub struct Tim4Ch3 {}
pub struct Tim4Ch4 {}
pub struct Tim15Ch1 {}
pub struct Tim15Ch2 {}
pub struct Tim16Ch1 {}
pub struct Tim16Ch1n {}
pub struct Tim17Ch1 {}
pub struct Tim17Ch1n {}
pub struct Tim1Ch1 {}
pub struct Tim1Ch2 {}
pub struct Tim1Ch3 {}
pub struct Tim1Ch4 {}
pub struct Tim8Ch1 {}
pub struct Tim8Ch2 {}
pub struct Tim8Ch3 {}
pub struct Tim8Ch4 {}
pub struct Tim20Ch1 {}
pub struct Tim20Ch2 {}
pub struct Tim20Ch3 {}
pub struct Tim20Ch4 {}
pub struct Tim2Etr {}
pub struct TscG1Io1 {}
pub struct Eventout {}
pub struct RtcRefin {}
pub struct TscG1Io2 {}
pub struct Usart2RtsDe {}
pub struct Tim15Ch1n {}
pub struct TscG1Io3 {}
pub struct Comp2Out {}
pub struct TscG1Io4 {}
pub struct TscG2Io1 {}
pub struct Spi3Nss {}
pub struct I2s3Ws {}
pub struct TscG2Io2 {}
pub struct TscG2Io3 {}
pub struct Tim1Bkin {}
pub struct TscG2Io4 {}
pub struct Tim1Ch1n {}
pub struct Mco {}
pub struct I2c3Scl {}
pub struct I2c2Smbal {}
pub struct I2s2Mck {}
pub struct I2c3Smbal {}
pub struct TscG4Io1 {}
pub struct I2c2Scl {}
pub struct I2s3Mck {}
pub struct Tim15Bkin {}
pub struct Tim17Bkin {}
pub struct TscG4Io2 {}
pub struct I2c2Sda {}
pub struct Spi2Miso {}
pub struct I2s2extSd {}
pub struct Comp6Out {}
pub struct Spi2Mosi {}
pub struct I2s2Sd {}
pub struct CanRx {}
pub struct Tim1Bkin2 {}
pub struct I2sckin {}
pub struct Tim1Ch2n {}
pub struct Usart1RtsDe {}
pub struct CanTx {}
pub struct Tim1Etr {}
pub struct Swdat {}
pub struct Jtms {}
pub struct TscG4Io3 {}
pub struct IrOut {}
pub struct Swclk {}
pub struct Jtck {}
pub struct TscG4Io4 {}
pub struct I2c1Sda {}
pub struct Jtdi {}
pub struct TscSync {}
pub struct I2c1Scl {}
pub struct TscG3Io2 {}
pub struct TscG3Io3 {}
pub struct Tim1Ch3n {}
pub struct Comp4Out {}
pub struct TscG3Io4 {}
pub struct Jtdo {}
pub struct Traceswo {}
pub struct TscG5Io1 {}
pub struct Spi3Sck {}
pub struct I2s3Ck {}
pub struct Jtrst {}
pub struct TscG5Io2 {}
pub struct Spi3Miso {}
pub struct I2s3Sd {}
pub struct Tim16Bkin {}
pub struct I2c1Smbal {}
pub struct Spi3Mosi {}
pub struct I2s3extSd {}
pub struct I2c3Sda {}
pub struct TscG5Io3 {}
pub struct TscG5Io4 {}
pub struct TscG6Io1 {}
pub struct TscG6Io2 {}
pub struct Spi2Nss {}
pub struct I2s2Ws {}
pub struct TscG6Io3 {}
pub struct Spi2Sck {}
pub struct I2s2Ck {}
pub struct TscG6Io4 {}
pub struct Usart3RtsDe {}
pub struct TscG3Io1 {}
