//! Signals

pub trait Signal<T> {}

pub trait Ain {}
pub trait SignalAin<T> {}
pub trait Wo0 {}
pub trait SignalWo0<T> {}
pub trait Wo1 {}
pub trait SignalWo1<T> {}
pub trait Wo2 {}
pub trait SignalWo2<T> {}
pub trait Wo3 {}
pub trait SignalWo3<T> {}
pub trait Wo4 {}
pub trait SignalWo4<T> {}
pub trait Wo5 {}
pub trait SignalWo5<T> {}
pub trait Wo6 {}
pub trait SignalWo6<T> {}
pub trait Wo7 {}
pub trait SignalWo7<T> {}
pub trait Wo {}
pub trait SignalWo<T> {}
pub trait Pad0 {}
pub trait SignalPad0<T> {}
pub trait Pad1 {}
pub trait SignalPad1<T> {}
pub trait Pad2 {}
pub trait SignalPad2<T> {}
pub trait Pad3 {}
pub trait SignalPad3<T> {}

pub struct Ain0 {}
pub struct Ain1 {}
pub struct Ain2 {}
pub struct Ain3 {}
pub struct Ain4 {}
pub struct Ain5 {}
pub struct Ain6 {}
pub struct Ain7 {}
pub struct Ain8 {}
pub struct Ain9 {}
pub struct Ain10 {}
pub struct Ain11 {}
pub struct Ain12 {}
pub struct Ain13 {}
pub struct Ain14 {}
pub struct Ain15 {}
pub struct Ain16 {}
pub struct Ain17 {}
pub struct Ain18 {}
pub struct Ain19 {}
pub struct Tcc0Wo0 {}
pub struct Tcc0Wo1 {}
pub struct Tcc0Wo2 {}
pub struct Tcc0Wo3 {}
pub struct Tcc0Wo4 {}
pub struct Tcc0Wo5 {}
pub struct Tcc0Wo6 {}
pub struct Tcc0Wo7 {}
pub struct Tcc1Wo0 {}
pub struct Tcc1Wo1 {}
pub struct Tcc1Wo2 {}
pub struct Tcc1Wo3 {}
pub struct Tcc2Wo0 {}
pub struct Tcc2Wo1 {}
pub struct Tc3Wo0 {}
pub struct Tc3Wo1 {}
pub struct Tc4Wo0 {}
pub struct Tc4Wo1 {}
pub struct Tc5Wo0 {}
pub struct Tc5Wo1 {}
pub struct Sercom0Pad0 {}
pub struct Sercom0Pad1 {}
pub struct Sercom0Pad2 {}
pub struct Sercom0Pad3 {}
pub struct Sercom1Pad0 {}
pub struct Sercom1Pad1 {}
pub struct Sercom1Pad2 {}
pub struct Sercom1Pad3 {}
pub struct Sercom2Pad0 {}
pub struct Sercom2Pad1 {}
pub struct Sercom2Pad2 {}
pub struct Sercom2Pad3 {}
pub struct Sercom3Pad0 {}
pub struct Sercom3Pad1 {}
pub struct Sercom3Pad2 {}
pub struct Sercom3Pad3 {}
pub struct Sercom4Pad0 {}
pub struct Sercom4Pad1 {}
pub struct Sercom4Pad2 {}
pub struct Sercom4Pad3 {}
pub struct Sercom5Pad0 {}
pub struct Sercom5Pad1 {}
pub struct Sercom5Pad2 {}
pub struct Sercom5Pad3 {}
pub struct Extint0 {}
pub struct Extint1 {}
pub struct Extint2 {}
pub struct Y0 {}
pub struct Vout {}
pub struct Extint3 {}
pub struct Adc {}
pub struct Vrefadac {}
pub struct Vrefa {}
pub struct Y1 {}
pub struct Extint4 {}
pub struct Vrefb {}
pub struct Y2 {}
pub struct Extint5 {}
pub struct Y3 {}
pub struct Extint6 {}
pub struct Y4 {}
pub struct Extint7 {}
pub struct Y5 {}
pub struct I2sSd0 {}
pub struct Nmi {}
pub struct X0 {}
pub struct I2sSd1 {}
pub struct Extint9 {}
pub struct X1 {}
pub struct I2sMck0 {}
pub struct Extint10 {}
pub struct X2 {}
pub struct I2sSck0 {}
pub struct GclkIo4 {}
pub struct Extint11 {}
pub struct X3 {}
pub struct I2sFs0 {}
pub struct GclkIo5 {}
pub struct Extint12 {}
pub struct AcCmp0 {}
pub struct Extint13 {}
pub struct AcCmp1 {}
pub struct Extint14 {}
pub struct GclkIo0 {}
pub struct Extint15 {}
pub struct GclkIo1 {}
pub struct X4 {}
pub struct GclkIo2 {}
pub struct X5 {}
pub struct GclkIo3 {}
pub struct X6 {}
pub struct X7 {}
pub struct X8 {}
pub struct Tc7Wo0 {}
pub struct X9 {}
pub struct Tc7Wo1 {}
pub struct X10 {}
pub struct GclkIo6 {}
pub struct X11 {}
pub struct UsbSof1khz {}
pub struct GclkIo7 {}
pub struct UsbDm {}
pub struct UsbDp {}
pub struct Extint8 {}
pub struct Swclk {}
pub struct Swdio {}
pub struct Y6 {}
pub struct Y7 {}
pub struct Y8 {}
pub struct Tc6Wo0 {}
pub struct Y9 {}
pub struct Tc6Wo1 {}
pub struct Y10 {}
pub struct Y11 {}
pub struct Y12 {}
pub struct Y13 {}
pub struct Y14 {}
pub struct Y15 {}
pub struct I2sMck1 {}
pub struct I2sSck1 {}
pub struct X12 {}
pub struct I2sFs1 {}
pub struct X13 {}
pub struct X14 {}
pub struct X15 {}
