[package]
name = "bobbin-stm32f746zg-example"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "blinky"
path = "src/blinky.rs"
doc = false

[[bin]]
name = "console"
path = "src/console.rs"
doc = false

[dependencies]
cortex-m-rt = "0.6"
panic-abort = "0.3"

[dependencies.stm32f74x]
path = "../../mcu/bobbin-stm32/stm32f74x"
features = ["STM32F74xxG"]

[profile.dev]
panic = "abort"
opt-level = "s"
incremental = false
lto = true

[profile.release]
panic = "abort"
opt-level = "s"
debug = true
incremental = false
lto = true