//! Signals

pub trait Signal<T> {}

pub trait SigDcmiHsync {}
pub trait SignalSigDcmiHsync<T> {}
pub trait SigDcmiVsync {}
pub trait SignalSigDcmiVsync<T> {}
pub trait SigDcmiPixclk {}
pub trait SignalSigDcmiPixclk<T> {}
pub trait SigDcmiD0 {}
pub trait SignalSigDcmiD0<T> {}
pub trait SigDcmiD1 {}
pub trait SignalSigDcmiD1<T> {}
pub trait SigDcmiD2 {}
pub trait SignalSigDcmiD2<T> {}
pub trait SigDcmiD3 {}
pub trait SignalSigDcmiD3<T> {}
pub trait SigDcmiD4 {}
pub trait SignalSigDcmiD4<T> {}
pub trait SigDcmiD5 {}
pub trait SignalSigDcmiD5<T> {}
pub trait SigDcmiD6 {}
pub trait SignalSigDcmiD6<T> {}
pub trait SigDcmiD7 {}
pub trait SignalSigDcmiD7<T> {}
pub trait SigDcmiD8 {}
pub trait SignalSigDcmiD8<T> {}
pub trait SigDcmiD9 {}
pub trait SignalSigDcmiD9<T> {}
pub trait SigDcmiD10 {}
pub trait SignalSigDcmiD10<T> {}
pub trait SigDcmiD11 {}
pub trait SignalSigDcmiD11<T> {}
pub trait SigDcmiD12 {}
pub trait SignalSigDcmiD12<T> {}
pub trait SigDcmiD13 {}
pub trait SignalSigDcmiD13<T> {}
pub trait Tim {}
pub trait SignalTim<T> {}
pub trait Adc {}
pub trait SignalAdc<T> {}
pub trait SpiNss {}
pub trait SignalSpiNss<T> {}
pub trait SpiMiso {}
pub trait SignalSpiMiso<T> {}
pub trait SpiMosi {}
pub trait SignalSpiMosi<T> {}
pub trait SpiSck {}
pub trait SignalSpiSck<T> {}
pub trait I2cScl {}
pub trait SignalI2cScl<T> {}
pub trait I2cSda {}
pub trait SignalI2cSda<T> {}
pub trait I2cSmbal {}
pub trait SignalI2cSmbal<T> {}
pub trait Tx {}
pub trait SignalTx<T> {}
pub trait Rx {}
pub trait SignalRx<T> {}
pub trait Cts {}
pub trait SignalCts<T> {}
pub trait Rts {}
pub trait SignalRts<T> {}
pub trait Ck {}
pub trait SignalCk<T> {}

pub struct DcmiHsync {}
pub struct DcmiVsync {}
pub struct DcmiPixclk {}
pub struct DcmiD0 {}
pub struct DcmiD1 {}
pub struct DcmiD2 {}
pub struct DcmiD3 {}
pub struct DcmiD4 {}
pub struct DcmiD5 {}
pub struct DcmiD6 {}
pub struct DcmiD7 {}
pub struct DcmiD8 {}
pub struct DcmiD9 {}
pub struct DcmiD10 {}
pub struct DcmiD11 {}
pub struct DcmiD12 {}
pub struct DcmiD13 {}
pub struct Tim2Ch1 {}
pub struct Tim2Ch2 {}
pub struct Tim2Ch3 {}
pub struct Tim2Ch4 {}
pub struct Tim3Ch1 {}
pub struct Tim3Ch2 {}
pub struct Tim3Ch3 {}
pub struct Tim3Ch4 {}
pub struct Tim4Ch1 {}
pub struct Tim4Ch2 {}
pub struct Tim4Ch3 {}
pub struct Tim4Ch4 {}
pub struct Tim5Ch1 {}
pub struct Tim5Ch2 {}
pub struct Tim5Ch3 {}
pub struct Tim5Ch4 {}
pub struct Tim9Ch1 {}
pub struct Tim9Ch2 {}
pub struct Tim10Ch1 {}
pub struct Tim11Ch1 {}
pub struct Tim12Ch1 {}
pub struct Tim12Ch2 {}
pub struct Tim13Ch1 {}
pub struct Tim14Ch1 {}
pub struct Tim1Ch1 {}
pub struct Tim1Ch2 {}
pub struct Tim1Ch3 {}
pub struct Tim1Ch4 {}
pub struct Tim8Ch1 {}
pub struct Tim8Ch2 {}
pub struct Tim8Ch3 {}
pub struct Tim8Ch4 {}
pub struct Adc1In0 {}
pub struct Adc1In1 {}
pub struct Adc1In2 {}
pub struct Adc1In3 {}
pub struct Adc1In4 {}
pub struct Adc1In5 {}
pub struct Adc1In6 {}
pub struct Adc1In7 {}
pub struct Adc1In8 {}
pub struct Adc1In9 {}
pub struct Adc1In10 {}
pub struct Adc1In11 {}
pub struct Adc1In12 {}
pub struct Adc1In13 {}
pub struct Adc1In14 {}
pub struct Adc1In15 {}
pub struct Adc2In0 {}
pub struct Adc2In1 {}
pub struct Adc2In2 {}
pub struct Adc2In3 {}
pub struct Adc2In4 {}
pub struct Adc2In5 {}
pub struct Adc2In6 {}
pub struct Adc2In7 {}
pub struct Adc2In8 {}
pub struct Adc2In9 {}
pub struct Adc2In10 {}
pub struct Adc2In11 {}
pub struct Adc2In12 {}
pub struct Adc2In13 {}
pub struct Adc2In14 {}
pub struct Adc2In15 {}
pub struct Adc3In0 {}
pub struct Adc3In1 {}
pub struct Adc3In2 {}
pub struct Adc3In3 {}
pub struct Adc3In4 {}
pub struct Adc3In5 {}
pub struct Adc3In6 {}
pub struct Adc3In7 {}
pub struct Adc3In8 {}
pub struct Adc3In9 {}
pub struct Adc3In10 {}
pub struct Adc3In11 {}
pub struct Adc3In12 {}
pub struct Adc3In13 {}
pub struct Adc3In14 {}
pub struct Adc3In15 {}
pub struct Spi1Nss {}
pub struct Spi1Miso {}
pub struct Spi1Mosi {}
pub struct Spi1Sck {}
pub struct Spi2Nss {}
pub struct Spi2Miso {}
pub struct Spi2Mosi {}
pub struct Spi2Sck {}
pub struct Spi3Nss {}
pub struct Spi3Miso {}
pub struct Spi3Mosi {}
pub struct Spi3Sck {}
pub struct Spi4Nss {}
pub struct Spi4Miso {}
pub struct Spi4Mosi {}
pub struct Spi4Sck {}
pub struct Spi5Nss {}
pub struct Spi5Miso {}
pub struct Spi5Mosi {}
pub struct Spi5Sck {}
pub struct Spi6Nss {}
pub struct Spi6Miso {}
pub struct Spi6Mosi {}
pub struct Spi6Sck {}
pub struct I2c1Scl {}
pub struct I2c1Sda {}
pub struct I2c1Smbal {}
pub struct I2c2Scl {}
pub struct I2c2Sda {}
pub struct I2c2Smbal {}
pub struct I2c3Scl {}
pub struct I2c3Sda {}
pub struct I2c3Smbal {}
pub struct I2c4Scl {}
pub struct I2c4Sda {}
pub struct I2c4Smbal {}
pub struct Usart1Tx {}
pub struct Usart1Rx {}
pub struct Usart1Cts {}
pub struct Usart1Rts {}
pub struct Usart1Ck {}
pub struct Usart2Tx {}
pub struct Usart2Rx {}
pub struct Usart2Cts {}
pub struct Usart2Rts {}
pub struct Usart2Ck {}
pub struct Usart3Tx {}
pub struct Usart3Rx {}
pub struct Usart3Cts {}
pub struct Usart3Rts {}
pub struct Usart3Ck {}
pub struct Uart4Tx {}
pub struct Uart4Rx {}
pub struct Uart4Cts {}
pub struct Uart4Rts {}
pub struct Uart4Ck {}
pub struct Uart5Tx {}
pub struct Uart5Rx {}
pub struct Uart5Cts {}
pub struct Uart5Rts {}
pub struct Uart5Ck {}
pub struct Usart6Tx {}
pub struct Usart6Rx {}
pub struct Usart6Cts {}
pub struct Usart6Rts {}
pub struct Usart6Ck {}
pub struct Uart7Tx {}
pub struct Uart7Rx {}
pub struct Uart7Cts {}
pub struct Uart7Rts {}
pub struct Uart7Ck {}
pub struct Uart8Tx {}
pub struct Uart8Rx {}
pub struct Uart8Cts {}
pub struct Uart8Rts {}
pub struct Uart8Ck {}
pub struct Tim2Etr {}
pub struct Tim8Etr {}
pub struct Sai2SdB {}
pub struct EthMiiCrs {}
pub struct Eventout {}
pub struct QuadspiBk1Io3 {}
pub struct Sai2MckB {}
pub struct EthMiiRxClk {}
pub struct EthRmiiRefClk {}
pub struct LcdR2 {}
pub struct Sai2SckB {}
pub struct EthMdio {}
pub struct MdiosMdio {}
pub struct LcdR1 {}
pub struct LcdB2 {}
pub struct OtgHsUlpiD0 {}
pub struct EthMiiCol {}
pub struct LcdB5 {}
pub struct I2s1Ws {}
pub struct I2s3Ws {}
pub struct OtgHsSof {}
pub struct LcdVsync {}
pub struct Tim8Ch1n {}
pub struct I2s1Ck {}
pub struct OtgHsUlpiCk {}
pub struct LcdR4 {}
pub struct Tim1Bkin {}
pub struct Tim8Bkin {}
pub struct MdiosMdc {}
pub struct LcdG2 {}
pub struct Tim1Ch1n {}
pub struct I2s1Sd {}
pub struct EthMiiRxDv {}
pub struct EthRmiiCrsDv {}
pub struct FmcSdnwe {}
pub struct Mco1 {}
pub struct Tim8Bkin2 {}
pub struct OtgFsSof {}
pub struct Can3Rx {}
pub struct LcdB3 {}
pub struct LcdR6 {}
pub struct I2c3Smba {}
pub struct I2s2Ck {}
pub struct LcdR5 {}
pub struct LcdB4 {}
pub struct OtgFsId {}
pub struct LcdB1 {}
pub struct I2s2Ws {}
pub struct Can1Rx {}
pub struct OtgFsDm {}
pub struct Tim1Etr {}
pub struct Sai2FsB {}
pub struct Can1Tx {}
pub struct OtgFsDp {}
pub struct Jtms {}
pub struct Swdio {}
pub struct Jtck {}
pub struct Swclk {}
pub struct Jtdi {}
pub struct HdmiCec {}
pub struct Can3Tx {}
pub struct Tim1Ch2n {}
pub struct Tim8Ch2n {}
pub struct Dfsdm1Ckout {}
pub struct LcdR3 {}
pub struct OtgHsUlpiD1 {}
pub struct EthMiiRxd2 {}
pub struct LcdG1 {}
pub struct Tim1Ch3n {}
pub struct Tim8Ch3n {}
pub struct Dfsdm1Datin1 {}
pub struct OtgHsUlpiD2 {}
pub struct EthMiiRxd3 {}
pub struct LcdG0 {}
pub struct Sai1SdA {}
pub struct I2s3Sd {}
pub struct QuadspiClk {}
pub struct Dfsdm1Ckin1 {}
pub struct Jtdo {}
pub struct Traceswo {}
pub struct I2s3Ck {}
pub struct Sdmmc2D2 {}
pub struct Njtrst {}
pub struct Sdmmc2D3 {}
pub struct I2c1Smba {}
pub struct Can2Rx {}
pub struct OtgHsUlpiD7 {}
pub struct EthPpsOut {}
pub struct FmcSdcke1 {}
pub struct LcdG7 {}
pub struct Dfsdm1Datin5 {}
pub struct Can2Tx {}
pub struct QuadspiBk1Ncs {}
pub struct FmcSdne1 {}
pub struct Dfsdm1Ckin5 {}
pub struct I2s4Sda {}
pub struct FmcNl {}
pub struct Dfsdm1Ckin7 {}
pub struct Sdmmc2D4 {}
pub struct EthMiiTxd3 {}
pub struct SdmmcD4 {}
pub struct LcdB6 {}
pub struct Dfsdm1Datin7 {}
pub struct Sdmmc2D5 {}
pub struct I2c4Smba {}
pub struct SdmmcD5 {}
pub struct LcdB7 {}
pub struct OtgHsUlpiD3 {}
pub struct EthMiiRxEr {}
pub struct LcdG4 {}
pub struct OtgHsUlpiD4 {}
pub struct EthMiiTxEn {}
pub struct EthRmiiTxEn {}
pub struct DsiTe {}
pub struct LcdG5 {}
pub struct I2c2Smba {}
pub struct OtgHsUlpiD5 {}
pub struct EthMiiTxd0 {}
pub struct EthRmiiTxd0 {}
pub struct OtgHsId {}
pub struct OtgHsUlpiD6 {}
pub struct EthMiiTxd1 {}
pub struct EthRmiiTxd1 {}
pub struct Dfsdm1Datin2 {}
pub struct Sdmmc2D0 {}
pub struct OtgHsDm {}
pub struct RtcRefin {}
pub struct I2s2Sd {}
pub struct Dfsdm1Ckin2 {}
pub struct Sdmmc2D1 {}
pub struct OtgHsDp {}
pub struct Dfsdm1Ckin0 {}
pub struct Dfsdm1Datin4 {}
pub struct OtgHsUlpiStp {}
pub struct Traced0 {}
pub struct Dfsdm1Datain0 {}
pub struct Dfsdm1Ckin4 {}
pub struct EthMdc {}
pub struct OtgHsUlpiDir {}
pub struct EthMiiTxd2 {}
pub struct FmcSdne0 {}
pub struct Dfsdm1Datain1 {}
pub struct OtgHsUlpiNxt {}
pub struct EthMiiTxClk {}
pub struct FmcSdcke0 {}
pub struct I2s1Mck {}
pub struct SpdifRx2 {}
pub struct EthMiiRxd0 {}
pub struct EthRmiiRxd0 {}
pub struct Dfsdm1Datain2 {}
pub struct SpdifRx3 {}
pub struct EthMiiRxd1 {}
pub struct EthRmiiRxd1 {}
pub struct I2s2Mck {}
pub struct Dfsdm1Ckin3 {}
pub struct FmcNwait {}
pub struct Sdmmc2D6 {}
pub struct SdmmcD6 {}
pub struct LcdHsync {}
pub struct I2s3Mck {}
pub struct Dfsdm1Datain3 {}
pub struct FmcNe1 {}
pub struct Sdmmc2D7 {}
pub struct SdmmcD7 {}
pub struct LcdG6 {}
pub struct Traced1 {}
pub struct FmcNe2 {}
pub struct FmcNce {}
pub struct SdmmcD0 {}
pub struct Mco2 {}
pub struct I2sCkin {}
pub struct QuadspiBk1Io0 {}
pub struct LcdG3 {}
pub struct SdmmcD1 {}
pub struct QuadspiBk1Io1 {}
pub struct SdmmcD2 {}
pub struct Dfsdm1Datain5 {}
pub struct QuadspiBk2Ncs {}
pub struct SdmmcD3 {}
pub struct Traced3 {}
pub struct SdmmcCk {}
pub struct Dfsdm1Ckin6 {}
pub struct Dfsdm1Datain7 {}
pub struct FmcD2 {}
pub struct Dfsdm1Datain6 {}
pub struct FmcD3 {}
pub struct Traced2 {}
pub struct Tim3Etr {}
pub struct SdmmcCmd {}
pub struct FmcClk {}
pub struct FmcNoe {}
pub struct FmcNwe {}
pub struct Sdmmc2Ck {}
pub struct Dfsdm1Datain4 {}
pub struct SpdifRx0 {}
pub struct Sdmmc2Cmd {}
pub struct SpdifRx1 {}
pub struct FmcD13 {}
pub struct FmcD14 {}
pub struct FmcD15 {}
pub struct Sai2SdA {}
pub struct FmcA16 {}
pub struct FmcCle {}
pub struct Lptim1In1 {}
pub struct Sai2FsA {}
pub struct FmcA17 {}
pub struct FmcAle {}
pub struct Lptim1Out {}
pub struct Sai2SckA {}
pub struct FmcA18 {}
pub struct FmcD0 {}
pub struct FmcD1 {}
pub struct Tim4Etr {}
pub struct Lptim1Etr {}
pub struct Sai2MckA {}
pub struct FmcNbl0 {}
pub struct Lptim1In2 {}
pub struct FmcNbl1 {}
pub struct Traceclk {}
pub struct Sai1MclkA {}
pub struct QuadspiBk1Io2 {}
pub struct FmcA23 {}
pub struct Sai1SdB {}
pub struct FmcA19 {}
pub struct Sai1FsA {}
pub struct FmcA20 {}
pub struct LcdB0 {}
pub struct Sai1SckA {}
pub struct FmcA21 {}
pub struct Tim1Bkin2 {}
pub struct FmcA22 {}
pub struct QuadspiBk2Io0 {}
pub struct FmcD4 {}
pub struct QuadspiBk2Io1 {}
pub struct FmcD5 {}
pub struct QuadspiBk2Io2 {}
pub struct FmcD6 {}
pub struct QuadspiBk2Io3 {}
pub struct FmcD7 {}
pub struct FmcD8 {}
pub struct FmcD9 {}
pub struct FmcD10 {}
pub struct LcdDe {}
pub struct FmcD11 {}
pub struct LcdClk {}
pub struct FmcD12 {}
pub struct LcdR7 {}
pub struct FmcA0 {}
pub struct FmcA1 {}
pub struct FmcA2 {}
pub struct FmcA3 {}
pub struct FmcA4 {}
pub struct FmcA5 {}
pub struct Sai1MclkB {}
pub struct Sai1SckB {}
pub struct Sai1FsB {}
pub struct FmcSdnras {}
pub struct FmcA6 {}
pub struct FmcA7 {}
pub struct FmcA8 {}
pub struct FmcA9 {}
pub struct FmcA10 {}
pub struct FmcA11 {}
pub struct FmcA12 {}
pub struct FmcA13 {}
pub struct FmcA14 {}
pub struct FmcBa0 {}
pub struct FmcA15 {}
pub struct FmcBa1 {}
pub struct FmcNe3 {}
pub struct FmcInt {}
pub struct FmcSdclk {}
pub struct FmcNe4 {}
pub struct FmcA24 {}
pub struct LcdR0 {}
pub struct FmcA25 {}
pub struct FmcSdncas {}
pub struct FmcD16 {}
pub struct FmcD17 {}
pub struct FmcD18 {}
pub struct FmcD19 {}
pub struct FmcD20 {}
pub struct FmcD21 {}
pub struct FmcD22 {}
pub struct FmcD23 {}
pub struct FmcD24 {}
pub struct FmcD25 {}
pub struct FmcD26 {}
pub struct FmcD27 {}
pub struct FmcNbl2 {}
pub struct FmcNbl3 {}
pub struct FmcD28 {}
pub struct FmcD29 {}
pub struct FmcD30 {}
pub struct FmcD31 {}
